#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Merged_NSForestmarkers_curation"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_Fullmerge_Test_SCT.rds")
MC1.use <- WhichCells(mySeurat, idents=c("17","28"))
mySeurat <- SetIdent(mySeurat, cells=MC1.use, value="MC1")
MC2.use <- WhichCells(mySeurat, idents=c("2","36"))
mySeurat <- SetIdent(mySeurat, cells=MC2.use, value="MC2")
MC3.use <- WhichCells(mySeurat, idents=c("29","38"))
mySeurat <- SetIdent(mySeurat, cells=MC3.use, value="MC3")
MC4.use <- WhichCells(mySeurat, idents=c("10","18"))
mySeurat <- SetIdent(mySeurat, cells=MC4.use, value="MC4")
MC5.use <- WhichCells(mySeurat, idents=c("4","14"))
mySeurat <- SetIdent(mySeurat, cells=MC5.use, value="MC5")
MC6.use <- WhichCells(mySeurat, idents=c("20","35"))
mySeurat <- SetIdent(mySeurat, cells=MC6.use, value="MC6")
MC7.use <- WhichCells(mySeurat, idents=c("37","6"))
mySeurat <- SetIdent(mySeurat, cells=MC7.use, value="MC7")
MC8.use <- WhichCells(mySeurat, idents=c("5","31"))
mySeurat <- SetIdent(mySeurat, cells=MC8.use, value="MC8")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=FALSE) + NoLegend()
dev.off()
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features="Esr1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:30)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(file=paste0(output,"_9130024F11Rik_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("9130024F11Rik"))
dev.off()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Samd3Vln.pdf"), width=14, height=4)
VlnPlot(mySeurat, features=c("Samd3"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_NSForestmarkers.pdf"), width=20, height=250)
VlnPlot(mySeurat, features=c("Zeb2","Gm45194","Foxp2","Zfp521","Prdm16","Otx2os1","March3","Cpne8","Pcdh11x","Frmd6","Fam19a1","Slc17a6","Tmem163","Nfib","Satb1","St18","Fgf13","Chrm3","Utrn","Ntng1","Zfhx4","Arhgap24","Sim1","Angpt1","Lhx8","Cdh23","Clstn2","B3gat2","Ptprt","Il1rapl2","Otof","Stk32b","Slc17a8","Gm2164","Zfhx4","Plekhg1","Sulf1","Esr2","Trpc6","St18","Gldn","Nxph2","Stxbp6","Sox6","Fign","Prox1","Iqschfp","Gm32647","Gm2164","Ebf1","Mpped1","Pde11a","Lhx8","Tmem132","Tacr3","Slit3","Bcl11a","Foxp2","Slc4a4","Tacr1","Shisal2b","Satb1","Sim1","Sim2","Moxd1","Sox6","Kcnmb2","Grik1","Satb2","Gm28928","Zfp521","Gfra1","Satb2","Nfib","Stxbp6","Lhx8","Col6a1","Drd2","Tac1","Esr2","Pbx3","Bnc2","Pbx3","Pgm5","Cbln2","Hs3st4","Dpf3","Gm13481","Hdac9","Sox5","Dach2","Dlk1","Tmem178","Adamts6","Wipf3","Pou6f2","Nts2","Kchnh8","Rarb","Ust","Foxp2","Ebf2","Col18a1"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Klhl14","Tac1","Dleu2","Cdh23","Car8","Slc17a8","Crh","Zeb2","Avp","Svil","Nup62cl","Haus4","Tac1","Prdm16","Sytl4","Sim1","Trp73","Ebf1","Ramp1","Dock5","Npffr2","Nxph2","Rbpms","Nts","C1ql3","Tac2","Acvr1c"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(mySeurat, file=(paste0(output, ".rds")))