#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Primed_Curated_40pcsstart"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_Primed_40pcs_res1.5_lowthresh_Primed.rds")
#excitatory.use <- WhichCells(mySeurat, idents=c("3","16","18"))
#mySeurat <- SetIdent(mySeurat, cells=excitatory.use, value="Slc17a6")
#Cdh23.use <- WhichCells(mySeurat, idents=c("4","10","18"))
#mySeurat <- SetIdent(mySeurat, cells=Cdh23.use, value="Cdh23")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2_Crh")
#Idents.Avp <- WhichCells(mySeurat, idents=c("25"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Avp, value="Avp")
#Idents.Slc17a8 <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Slc17a8, value="Slc17a8")
#Idents.Trp73 <- WhichCells(mySeurat, idents=c("17"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Trp73, value="Trp73")
#Idents.Sim1 <- WhichCells(mySeurat, idents=c("2","15"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sim1, value="Sim1")
#Idents.Car8 <- WhichCells(mySeurat, idents=c("12"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Car8, value="Car8")
#Idents.Nup62cl <- WhichCells(mySeurat, idents=c("28"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nup62cl, value="Nup62cl")
#Idents.Ebf1 <- WhichCells(mySeurat, idents=c("14"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ebf1, value="Ebf1")
#Idents.Haus4 <- WhichCells(mySeurat, idents=c("0","26"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Haus4, value="Haus4")
#Idents.Tac1 <- WhichCells(mySeurat, idents=c("23"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Tac1, value="Tac1_Cyp19a1")
#Idents.Prdm16 <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prdm16, value="Prdm16")
#Idents.Sytl4 <- WhichCells(mySeurat, idents=c("1"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sytl4, value="Sytl4")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("11","24"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Ramp1")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("3"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2_Crh")
#Npffr2.use <- WhichCells(mySeurat, idents=c("27"))
#mySeurat <- SetIdent(mySeurat, cells=Npffr2.use, value="Npffr2")
#Dock5.use <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Dock5.use, value="Dock5")
#Nxph2.use <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Nxph2.use, value="Nxph2_Cyp19a1")
#Rbpms.use <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=Rbpms.use, value="Rbpms_Cyp19a1")
#Nts.use <- WhichCells(mySeurat, idents=c("6"))
#mySeurat <- SetIdent(mySeurat, cells=Nts.use, value="Nts")
#C1ql3.use <- WhichCells(mySeurat, idents=c("9"))
#mySeurat <- SetIdent(mySeurat, cells=C1ql3.use, value="C1ql3")
#Tac2.use <- WhichCells(mySeurat, idents=c("16"))
#mySeurat <- SetIdent(mySeurat, cells=Tac2.use, value="Tac2")

pdf(file=paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Avp")
dev.off()
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:10)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Samd3Vln.pdf"), width=14, height=4)
VlnPlot(mySeurat, features=c("Samd3"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=70)
VlnPlot(mySeurat, features=c("Samd3","Klhl14","Tac1","Dleu2","Cdh23","Car8","Slc17a8","Crh","Zeb2","Avp","Svil","Nup62cl","Haus4","Tac1","Prdm16","Sytl4","Sim1","Trp73","Ebf1","Ramp1","Dock5","Npffr2","Nxph2","Rbpms","Nts","C1ql3","Tac2","Acvr1c","Tac1"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindMarkers(mySeurat, only.pos=TRUE, ident.1="Sytl4", min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_Unknownallposmarkers.csv"))