#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Intact_Curated_30ps"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1__Intact.rds")
#excitatory.use <- WhichCells(mySeurat, idents=c("3","16","18"))
#mySeurat <- SetIdent(mySeurat, cells=excitatory.use, value="Slc17a6")
#Cdh23.use <- WhichCells(mySeurat, idents=c("10","15"))
#mySeurat <- SetIdent(mySeurat, cells=Cdh23.use, value="Cdh23")
#Idents.Unknown <- WhichCells(mySeurat, idents=c("4","17"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Unknown, value="Zeb2")
#Idents.Cdh24 <- WhichCells(mySeurat, idents=c("7","8","22"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Cdh24, value="Cdh24")
#Idents.Slc17a8 <- WhichCells(mySeurat, idents=c("6"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Slc17a8, value="Slc17a8")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("12"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Ramp1")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Avp")
#Idents.Sytl4 <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sytl4, value="Sytl4")
#Idents.Nup62cl <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nup62cl, value="Nxph2_Nup62cl")
#Idents.Dleu2 <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Dleu2, value="Dleu2")
#Idents.Nox4 <- WhichCells(mySeurat, idents=c("14"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nox4, value="Nox4")
#Idents.Svil <- WhichCells(mySeurat, idents=c("9"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Svil, value="Svil")
#Idents.Gpr39 <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Gpr39, value="Gpr39")
#Idents.Prox1 <- WhichCells(mySeurat, idents=c("1"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prox1, value="Prox1")
#Idents.Nxph2 <- WhichCells(mySeurat, idents=c("0"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nxph2, value="Nxph2_Cyp19a1")
#Idents.Lhx5 <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Lhx5, value="Lhx5")
#Mystery.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Mystery.use, value="9130024F11Rik")
pdf(file=paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Avp")
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:10)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Slc17a6","Cdh24","Zeb2","Cdh23","Slc17a8","Ramp1","Avp","Sytl4","Nup62cl","Dleu2","Nox4","Svil","Gpr39","Prox1","Nxph2","Lhx5","9130024F11Rik"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindMarkers(mySeurat, ident.1="Nxph2", only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_Nxph2mergedallposmarkers.csv"))