output <- "Seurat/BNST_IndependentAnalysis/BNST_Fullmerge_Test_CCAtestallstandardscale_filtered2_res1.2"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

BNST.comb <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_Fullmerge_Test_CCAtestallstandardscaleDEGenforce_filtered1CCAscaledata.rds")
BNST.comb <- subset(BNST.comb, idents=c("37","41"), invert=TRUE) 


DefaultAssay(BNST.comb) <- "integrated"
BNST.comb <- ScaleData(BNST.comb, vars.to.regress="orig.ident")
BNST.comb <- RunPCA(BNST.comb)
BNST.comb <- RunUMAP(BNST.comb, reduction="pca", dims=1:30)
BNST.comb <- FindNeighbors(BNST.comb, reduction="pca", dims=1:30)
BNST.comb <- FindClusters(BNST.comb, resolution=1.2)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(BNST.comb, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(BNST.comb, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(BNST.comb, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(BNST.comb, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(BNST.comb, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
DefaultAssay(BNST.comb) <- "RNA"
BNST.comb <- NormalizeData(BNST.comb)
pdf(file=paste0(output,"MarkerVln.pdf"), width=40, height=20)
VlnPlot(BNST.comb, features=c("Esr1","Pgr","Slc17a6","Gad1","Cyp19a1","Tac1"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output,"_Tac1vln.pdf"), width=20)
VlnPlot(BNST.comb, features=c("Tac1"), split.by="sex", pt.size=0)
dev.off()
t <- prop.table(table(Idents(BNST.comb), BNST.comb$Hormone), margin=2)
write.csv(t, file=paste0(output,"props.csv"))
mySeurat.markers <- FindAllMarkers(BNST.comb, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25, test.use="MAST")
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
#top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
#DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
#dev.off()
saveRDS(BNST.comb, file=paste0(output,"CCAscaledata.rds"))