#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Intact_Curated_40pcsstart"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_40pcs_res1_lowthresh_res1.5_Intact.rds")
#Car8.use <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Car8.use, value="Car8_Cyp19a1")
#Cdh23.use <- WhichCells(mySeurat, idents=c("8"))
#mySeurat <- SetIdent(mySeurat, cells=Cdh23.use, value="Cdh23")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("2","23"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2")
#Slc17a8.use <- WhichCells(mySeurat, idents=c("15"))
#mySeurat <- SetIdent(mySeurat, cells=Slc17a8.use, value="Slc17a8")
#Ebf1.use <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Ebf1.use, value="Ebf1")
#Idents.Prdm16 <- WhichCells(mySeurat, idents=c("10"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prdm16, value="Prdm16")
#Idents.Avp <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Avp, value="Avp")
#Prdm16.use <- WhichCells(mySeurat, idents=c("4","16"))
#mySeurat <- SetIdent(mySeurat, cells=Prdm16.use, value="Haus4_Cyp19a1")
#Idents.Sim1 <- WhichCells(mySeurat, idents=c("0","19"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sim1, value="Sim1")
#Idents.Sytl4 <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sytl4, value="Sytl4")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Ramp1")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2")
#Idents.Gpr39 <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Gpr39, value="Gpr39")
#Idents.Prox1 <- WhichCells(mySeurat, idents=c("1"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prox1, value="Prox1")
#Idents.Nxph2 <- WhichCells(mySeurat, idents=c("0"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nxph2, value="Nxph2_Cyp19a1")
#Idents.Lhx5 <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Lhx5, value="Lhx5")
#Mystery.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Mystery.use, value="9130024F11Rik")
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Avp")
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:10)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Samd3Vln.pdf"), width=14, height=4)
VlnPlot(mySeurat, features=c("Samd3"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Tac1","Klhl14","Dleu2","Car8","Cdh23","Slc17a8","Zeb2","Crh","Ramp1","Gal","Nup62cl","Prdm16","Avp","Haus4","Sim1","Ebf1","Sytl4","Nxph2","Acvr1c","Tac1"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindMarkers(mySeurat, only.pos=TRUE, ident.1="Avp", min.pct=0, min.diff.pct=0, logfc.threshold = 0, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_Avpmergedallposmarkers.csv"))