#!/usr/bin/env Rscript

output <- "Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_Unprimed_0.8res_10pcs_res1"

library(BUSpaRse)
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Unprimed <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1__Unprimed.rds")
Unprimed <- SCTransform(Unprimed, verbose=TRUE)
Unprimed <- RunPCA(Unprimed)
warnings()
Unprimed <- FindNeighbors(Unprimed, dims=1:10)
Unprimed <- FindClusters(Unprimed, resolution=0.8)

Unprimed <- RunUMAP(Unprimed, dims=1:10)
pdf(paste0(output,"_Unprimed_UMAP.pdf"))
DimPlot(Unprimed, reduction="umap", label=TRUE)
dev.off()
Unprimed <- BuildClusterTree(Unprimed, dims=1:10)
pdf(paste0(output,"_Unprimed_clustertree.pdf"))
PlotClusterTree(object=Unprimed)
dev.off()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(Unprimed, features=c("Esr1", "Slc17a6","Gad1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
Unprimed.markers <- FindAllMarkers(Unprimed, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Unprimed.markers, file=paste0(output,"_Unprimed_allposmarkers.csv"))
pdf(paste0(output,"_Unprimed_TopMarkerheatmap.pdf"))
top10 <- Unprimed.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Unprimed, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Unprimed, file=(paste0(output, "_Unprimed.rds")))
