#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Primed_Curated_40PCs_NSForest_revised"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_Primed_40pcs_res1.5_lowthresh_Primed.rds")
Tacr3.use <- WhichCells(mySeurat, idents=c("17","24"))
mySeurat <- SetIdent(mySeurat, cells=Tacr3.use, value="Tacr3")
#Unclear2.use <- WhichCells(mySeurat, idents=c("16","19"))
#mySeurat <- SetIdent(mySeurat, cells=Unclear2.use, value="Unclear2")
Cdh23.use <- WhichCells(mySeurat, idents=c("10","13","27"))
mySeurat <- SetIdent(mySeurat, cells=Cdh23.use, value="Cdh23")
Slc17a8.use <- WhichCells(mySeurat, idents=c("7"))
mySeurat <- SetIdent(mySeurat, cells=Slc17a8.use, value="Slc17a8")
Gm27199.use <- WhichCells(mySeurat, idents=c("5","9"))
mySeurat <- SetIdent(mySeurat, cells=Gm27199.use, value="Gm27199")
St18.use <- WhichCells(mySeurat, idents=c("4","11","31"))
mySeurat <- SetIdent(mySeurat, cells=St18.use, value="St18")
Unclear.use <- WhichCells(mySeurat, idents=c("2","29","18"))
mySeurat <- SetIdent(mySeurat, cells=Unclear.use, value="Unclear")
Zeb2.use <- WhichCells(mySeurat, idents=c("1","14"))
mySeurat <- SetIdent(mySeurat, cells=Zeb2.use, value="Zeb2")
Unclear3.use <- WhichCells(mySeurat, idents=c("0","12"))
mySeurat <- SetIdent(mySeurat, cells=Unclear3.use, value="Unclear3")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2_Crh")
#Idents.Avp <- WhichCells(mySeurat, idents=c("25"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Avp, value="Avp")
#Idents.Slc17a8 <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Slc17a8, value="Slc17a8")
#Idents.Trp73 <- WhichCells(mySeurat, idents=c("17"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Trp73, value="Trp73")
#Idents.Sim1 <- WhichCells(mySeurat, idents=c("2","15"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sim1, value="Sim1")
#Idents.Car8 <- WhichCells(mySeurat, idents=c("12"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Car8, value="Car8")
#Idents.Nup62cl <- WhichCells(mySeurat, idents=c("28"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nup62cl, value="Nup62cl")
#Idents.Ebf1 <- WhichCells(mySeurat, idents=c("14"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ebf1, value="Ebf1")
#Idents.Haus4 <- WhichCells(mySeurat, idents=c("0","26"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Haus4, value="Haus4")
#Idents.Tac1 <- WhichCells(mySeurat, idents=c("23"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Tac1, value="Tac1_Cyp19a1")
#Idents.Prdm16 <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prdm16, value="Prdm16")
#Idents.Sytl4 <- WhichCells(mySeurat, idents=c("1"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sytl4, value="Sytl4")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("11","24"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Ramp1")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("3"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2_Crh")
#Npffr2.use <- WhichCells(mySeurat, idents=c("27"))
#mySeurat <- SetIdent(mySeurat, cells=Npffr2.use, value="Npffr2")
#Dock5.use <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Dock5.use, value="Dock5")
#Nxph2.use <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Nxph2.use, value="Nxph2_Cyp19a1")
#Rbpms.use <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=Rbpms.use, value="Rbpms_Cyp19a1")
#Nts.use <- WhichCells(mySeurat, idents=c("6"))
#mySeurat <- SetIdent(mySeurat, cells=Nts.use, value="Nts")
#C1ql3.use <- WhichCells(mySeurat, idents=c("9"))
#mySeurat <- SetIdent(mySeurat, cells=C1ql3.use, value="C1ql3")
#Tac2.use <- WhichCells(mySeurat, idents=c("16"))
#mySeurat <- SetIdent(mySeurat, cells=Tac2.use, value="Tac2")

pdf(file=paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Avp")
dev.off()
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:10)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=10, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1","Chodl","Rfx3","Kmt2a"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_NSForestVln.pdf"), width=14, height=120)
VlnPlot(mySeurat, features=c("Grik1","Sox2ot","Sulf1","Gm45194","Zeb2","Fgf13","Grm1","Khdrbs3","Angpt1","Sim1","Nfib","Kcnmb2","Gm27199","Ntng1","Ebf1","Pantr1","Slc17a8","Zfp804b","Plekhg1","Ptprk","Cdh23","Spon1","Nfix","St18","Adamts6","Nrg1","Cpne8","Sema3a","Gli3","Gm32647","Gm2164","Lypd6b","Samd3","Slc17a6","Sox6","Col18a1","Tacr3","Slit3","Zfp521","Gfra1","Iqschfp","Gulp1","Gm29478","Arhgap24","Angpt1","Otx2os1","Prdm16","Esr2","Bmpr1b","Satb2","Stk32b","Ankrd33b","Rarb","Pgm5","Avp","Slc4a4","B020031H02Rik","Trpm3","Gm13481","Rorb","Col18a1","Ebf2","Bnc2","Scml4","Dach2","Gm41414","Sfta3-ps","Arhgap31","St18","Hdac9","Sox5"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=60)
VlnPlot(mySeurat, features=c("Dleu2","Cdh23","Car8","Slc17a8","Crh","Zeb2","Avp","Svil","Nup62cl","Haus4","Tac1","Prdm16","Sytl4","Sim1","Trp73","Ebf1","Ramp1","Dock5","Npffr2","Nxph2","Rbpms","Nts","C1ql3","Tac2","Acvr1c","Tac1"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_llposmarkers.csv"))