#!/usr/bin/env Rscript

output <- "Seurat/BNST_IndependentAnalysis/BNST_Fullmerge_Test_SCT10pcsres1redo"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
PrimedBNST <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_Primed_40pcs_res1.5_lowthresh_Primed.rds")
MaleBNST <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_40pcs_res1_lowthresh_res1.5_Intact.rds")
UnprimedBNST <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered2_Unprimed_30pcs_nothresh_res1__Unprimed.rds")
#PrimedBNST <- SCTransform(PrimedBNST)
#MaleBNST <- SCTransform(MaleBNST)
#UnprimedBNST <- SCTransform(UnprimedBNST)
MaleBNST$sex <- "Male"
MaleBNST$Hormone <- "Intact"
PrimedBNST$sex <- "Female"
PrimedBNST$Hormone <- "Primed"
UnprimedBNST$sex <- "Female"
UnprimedBNST$Hormone <- "Unprimed"
list <- c(MaleBNST,UnprimedBNST,PrimedBNST)
BNST.features <- SelectIntegrationFeatures(object.list=list, nfeatures=3000)
BNST.list <- PrepSCTIntegration(list, anchor.features=BNST.features, verbose=TRUE)
BNST.anchors <- FindIntegrationAnchors(BNST.list, normalization.method="SCT", anchor.features=BNST.features, verbose=TRUE)
mySeurat <- IntegrateData(anchorset=BNST.anchors, normalization.method="SCT", verbose=FALSE)
mySeurat <- RunPCA(mySeurat)
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:10)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:10)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"Tac1_Vln.pdf"), width=40)
VlnPlot(mySeurat, features=c("Tac1"), pt.size=0)
dev.off()
pdf(file=paste0(output,"Esr1_Vln.pdf"), width=40)
VlnPlot(mySeurat, features=c("Esr1"), pt.size=0)
dev.off()
pdf(file=paste0(output,"Tac1_Vlnsplit.pdf"), width=40)
VlnPlot(mySeurat, features=c("Tac1"), pt.size=0, split.by="Hormone")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.20)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
#top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
#DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
#dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))