#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Intact_Curated_40pcs_NSForestanalysis_Raw"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered1_40pcs_res1_lowthresh_res1.5_Intact.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpMale <- read.table("Genelists/BNST_MvP_Upmale_latest.txt")
unlist(UpMale)
UpMale <- as.matrix(UpMale)
UpMale.filtered <- intersect(UpMale, genes.10x)
#Avp.use <- WhichCells(mySeurat, idents=c("24"))
#mySeurat <- SetIdent(mySeurat, cells=Avp.use, value="Avp")
#Ramp1.use <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Ramp1.use, value="Ramp1")
#Bnc2.use <- WhichCells(mySeurat, idents=c("18"))
#mySeurat <- SetIdent(mySeurat, cells=Bnc2.use, value="Bnc2")
#Slc17a8.use <- WhichCells(mySeurat, idents=c("16"))
#mySeurat <- SetIdent(mySeurat, cells=Slc17a8.use, value="Slc17a8")
#Satb2.use <- WhichCells(mySeurat, idents=c("14"))
#mySeurat <- SetIdent(mySeurat, cells=Satb2.use, value="Satb2")
##Isl1.use <- WhichCells(mySeurat, idents=c("13","19"))
##mySeurat <- SetIdent(mySeurat, cells=Isl1.use, value="Isl1")
#Ebf1.use <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Ebf1.use, value="Ebf1")
#Lhx8.use <- WhichCells(mySeurat, idents=c("10","23"))
#mySeurat <- SetIdent(mySeurat, cells=Lhx8.use, value="Lhx8")
#Maml2.use <- WhichCells(mySeurat, idents=c("9","25"))
#mySeurat <- SetIdent(mySeurat, cells=Maml2.use, value="Maml2_Syne2")
#Prdm16.use <- WhichCells(mySeurat, idents=c("8"))
#mySeurat <- SetIdent(mySeurat, cells=Prdm16.use, value="Prdm16")
#Gm27199.use <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Gm27199.use, value="Gm27199")
#Nxph2.use <- WhichCells(mySeurat, idents=c("6","21"))
#mySeurat <- SetIdent(mySeurat, cells=Nxph2.use, value="Nxph2")
#Cpne8.use <- WhichCells(mySeurat, idents=c("4","12"))
#mySeurat <- SetIdent(mySeurat, cells=Cpne8.use, value="Cpne8")
#Sim1Sim2.use <- WhichCells(mySeurat, idents=c("3","17","20"))
#mySeurat <- SetIdent(mySeurat, cells=Sim1Sim2.use, value="Sim1_Sim2")
#Bcl11b.use <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=Bcl11b.use, value="Bcl11b")
#Idents.Zeb2 <- WhichCells(mySeurat, idents=c("1","26"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2")
#St18.use <- WhichCells(mySeurat, idents=c("0","15"))
#mySeurat <- SetIdent(mySeurat, cells=St18.use, value="St18")
#Slc17a8.use <- WhichCells(mySeurat, idents=c("15"))
#mySeurat <- SetIdent(mySeurat, cells=Slc17a8.use, value="Slc17a8")
#Ebf1.use <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Ebf1.use, value="Ebf1")
#Idents.Prdm16 <- WhichCells(mySeurat, idents=c("10"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prdm16, value="Prdm16")
#Idents.Avp <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Avp, value="Avp")
#Prdm16.use <- WhichCells(mySeurat, idents=c("4","16"))
#mySeurat <- SetIdent(mySeurat, cells=Prdm16.use, value="Haus4_Cyp19a1")
#Idents.Sim1 <- WhichCells(mySeurat, idents=c("0","19"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sim1, value="Sim1")
#Idents.Sytl4 <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Sytl4, value="Sytl4")
#Idents.Ramp1 <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Ramp1, value="Ramp1")
##Idents.Zeb2 <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Zeb2, value="Zeb2")
#Idents.Gpr39 <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Gpr39, value="Gpr39")
#Idents.Prox1 <- WhichCells(mySeurat, idents=c("1"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Prox1, value="Prox1")
#Idents.Nxph2 <- WhichCells(mySeurat, idents=c("0"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Nxph2, value="Nxph2_Cyp19a1")
#Idents.Lhx5 <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Lhx5, value="Lhx5")
#Mystery.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Mystery.use, value="9130024F11Rik")
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Avp")
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:40)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
Pct <- DotPlot(mySeurat, features=UpMale.filtered)
sink(file=paste0(output,"_pctSDEGbyclust.txt"), append=FALSE, type=c("output","message"), split=FALSE)
Pct$data
sink()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_NSForest_Vln.pdf"), width=8, height=120)
VlnPlot(mySeurat, features=c("St18","Moxd1","Mpped2","Adarb2","Sfta3-ps","Necab1","Bcl11b","Cnih3","Fam19a1","Tmem163","Car10","Gm32647","Cadps2","Grik1","Sox2ot","Synpr","Moxd1","Nfib","Sorcs2","Fign","Hs3st4","Gm27199","Zfhx4","Prdm16","Zfp521","Maml2","Syne2","Lhx8","Fam19a1","Ebf1","Mpped1","Cpne8","Grik1","Sntb1","Isl1","Nxn","Chrm3","Satb2","Gm28928","Tox","Slc17a8","Rnf207","Sim1","Pbx3","Bnc2","Zfp521","Nkain3","Gfra1","Angpt1","Sim2","Qrfpr","Prox1","Stac2","Rarb","Sh3rf2","Rorb","Gm13481","Avp","Shisal2b","Fign","Zeb2","Foxp2"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_NSForest_CondensedVln.pdf"), width=8, height=40)
VlnPlot(mySeurat, features=c("St18", "Zeb2","Bcl11b","Sim1","Cpne8","Nxph2","Gm27199","Prdm16","Maml2","Lnx8","Ebf1","Satb2","Slc17a8","Bnc2","Avp","Isl1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Chodl","Dleu2","Car8","Cdh23","Slc17a8","Zeb2","Crh","Ramp1","Gal","Nup62cl","Prdm16","Avp","Haus4","Sim1","Ebf1","Sytl4","Nxph2","Acvr1c","Tac1"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_NSForestCuratedallposmarkers.csv"))
saveRDS(mySeurat, file=(paste0(output, ".rds")))