#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_IndependentAnalysis/BNST_Unprimed_Curated_40ps_res1.5_NSForest_Revised2"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/BNST_IndependentAnalysis/BNST_IndependentFiltered2_Unprimed_40pcs_nothresh_res1.5__Unprimed.rds")

Ramp1.use <- WhichCells(mySeurat, idents=c("33","24"))
mySeurat <- SetIdent(mySeurat, cells=Ramp1.use, value="Ramp1")
Kcnmb2.use <- WhichCells(mySeurat, idents=c("19","21","23"))
mySeurat <- SetIdent(mySeurat, cells=Kcnmb2.use, value="Kcnmb2")
Calcr.use <- WhichCells(mySeurat, idents=c("15","20"))
mySeurat <- SetIdent(mySeurat, cells=Calcr.use, value="Calcr")
Slc17a8.use <- WhichCells(mySeurat, idents=c("14"))
mySeurat <- SetIdent(mySeurat, cell=Slc17a8.use, value="Slc17a8")
Satb2.use <- WhichCells(mySeurat, idents=c("13"))
mySeurat <- SetIdent(mySeurat, cell=Satb2.use, value="Satb2")
Cpne8.use <- WhichCells(mySeurat, idents=c("10","12"))
mySeurat <- SetIdent(mySeurat, cells=Cpne8.use, value="Cpne8")
Ebf1.use <- WhichCells(mySeurat, idents=c("11","18"))
mySeurat <- SetIdent(mySeurat, cell=Ebf1.use, value="Ebf1")
#Gypa.use <- WhichCells(mySeurat, idents=c("10","12"))
#mySeurat <- SetIdent(mySeurat, cells=Gypa.use, value="Gypa")
Sim1.use <- WhichCells(mySeurat, idents=c("8","25"))
mySeurat <- SetIdent(mySeurat, cells=Sim1.use, value="Sim1")
Nxph2.use <- WhichCells(mySeurat, idents=c("7","16","17"))
mySeurat <- SetIdent(mySeurat, cells=Nxph2.use, value="Nxph2")
St18.use <- WhichCells(mySeurat, idents=c("6"))
mySeurat <- SetIdent(mySeurat, cells=St18.use, value="St18")
Bcl11b.use <- WhichCells(mySeurat, idents=c("5","27"))
mySeurat <- SetIdent(mySeurat, cells=Bcl11b.use, value="Bcl11b")
Prdm16.use <- WhichCells(mySeurat, idents=c("4"))
mySeurat <- SetIdent(mySeurat, cells=Prdm16.use, value="Prdm16")
Isl1.use <- WhichCells(mySeurat, idents=c("3","22"))
mySeurat <- SetIdent(mySeurat, cells=Isl1.use, value="Isl1")
Cdh23.use <- WhichCells(mySeurat, idents=c("2","29"))
mySeurat <- SetIdent(mySeurat, cells=Cdh23.use, value="Cdh23")
Gm27199.use <- WhichCells(mySeurat, idents=c("1","34"))
mySeurat <- SetIdent(mySeurat, cells=Gm27199.use, value="Gm27199")
Zeb2.use <- WhichCells(mySeurat, idents=c("0","9"))
mySeurat <- SetIdent(mySeurat, cells=Zeb2.use, value="Zeb2")
#mySeurat <- SetIdent(mySeurat, cells=Slc17a8.use, value="Slc17a8")
#Idents.Lhx5 <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Idents.Lhx5, value="Lhx5")
#Sim1.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Sim1.use, value="Sim1")
#Zeb2.use <- WhichCells(mySeurat, idents=c("3"))
#mySeurat <- SetIdent(mySeurat, cells=Zeb2.use, value="Zeb2")
#Haus4.use <- WhichCells(mySeurat, idents=c("9"))
#mySeurat <- SetIdent(mySeurat, cells=Haus4.use, value="Haus4")
#Tac2.use <- WhichCells(mySeurat, idents=c("5"))
#mySeurat <- SetIdent(mySeurat, cells=Tac2.use, value="Tac2")
#Prdm16.use <- WhichCells(mySeurat, idents=c("10"))
#mySeurat <- SetIdent(mySeurat, cells=Prdm16.use, value="Prdm16")
#Ramp1.use <- WhichCells(mySeurat, idents=c("8"))
#mySeurat <- SetIdent(mySeurat, cells=Ramp1.use, value="Ramp1")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=FALSE) + NoLegend()
dev.off()
pdf(file=paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, features="Cyp19a1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features="Esr1", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Acvr1c", cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Tac1featureplot.pdf"))
FeaturePlot(mySeurat, features="Tac1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:40)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(file=paste0(output,"_9130024F11Rik_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("9130024F11Rik"))
dev.off()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Samd3Vln.pdf"), width=14, height=4)
VlnPlot(mySeurat, features=c("Samd3"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_NSForestmarkers.pdf"), width=14, height=200)
VlnPlot(mySeurat, features=c("Gm45194","Zeb2","Cacna2d1","Car10","Cdh23","Lhx8","Fgf13","Utrn","Isl1","Prdm16","Cpne4","Bcl11b","Meis2","St18","Csgalnact1","March3","Cpne8","Nrg1","Sim1","Gm39185","Sfta3-ps","Gm2164","Gm32647","Rgs6","Ebf1","Gm2824","Clstn2","Sox5","Satb2","Slc17a8","Meis2","Calcr","Rgs6","Nxph2","Stxbp6","Fign","Iqschfp","Satb2","Il1rapl2","Tac2","Kcnmb2","Ntng1","Pbx3","Shisal2b","Satb1","Esr2","Meis2","Pbx3","Ecel1","Esr2","Moxd1","Ramp1","AC060761.1","Sim1","Sim2","Trp73","B020031H02Rik","6530403H02Rik","Hdac9","Sox5","Prdm16","Rorb","Gm12082","Npas1","E130114P18Rik","Sel1l3","Gbx1","Ust","Rarb","Map3k15"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Klhl14","Tac1","Dleu2","Cdh23","Car8","Slc17a8","Crh","Zeb2","Avp","Svil","Nup62cl","Haus4","Tac1","Prdm16","Sytl4","Sim1","Trp73","Ebf1","Ramp1","Dock5","Npffr2","Nxph2","Rbpms","Nts","C1ql3","Tac2","Acvr1c"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(mySeurat, file=(paste0(output, ".rds")))