#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/MeA_IndependentAnalysis/MeA_Intact_Curated_30pcs_Mergetest"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/MeA_IndependentAnalysis/MeA_IndependentFiltered3_Intact_30pcs_1res_Intact.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpMalevPrimed <- read.table("Genelists/MeA_MalevPrimed_Localnew.txt")
unlist(UpMalevPrimed)
UpMalevPrimed <- as.matrix(UpMalevPrimed)
UpMalevPrimed.filtered <- intersect(UpMalevPrimed, genes.10x)
UpMale <- read.table("Genelists/MeA_MalevFemaleAll_Localnew.txt")
unlist(UpMale)
UpMale <- as.matrix(UpMale)
UpMale.filtered <- intersect(UpMale, genes.10x)
Cluster1.use <- WhichCells(mySeurat, idents=c("1","2","6","21"))
mySeurat <- SetIdent(mySeurat, cells=Cluster1.use, value="Cluster1")
Cluster2.use <- WhichCells(mySeurat, idents=c("3"))
mySeurat <- SetIdent(mySeurat, cells=Cluster2.use, value="Cluster2")
Cluster3.use <- WhichCells(mySeurat, idents=c("4","11"))
mySeurat <- SetIdent(mySeurat, cells=Cluster3.use, value="Cluster3")
Cluster4.use <- WhichCells(mySeurat, idents=c("5","20"))
mySeurat <- SetIdent(mySeurat, cells=Cluster4.use, value="Cluster4")
Cluster5.use <- WhichCells(mySeurat, idents=c("7","24"))
mySeurat <- SetIdent(mySeurat, cells=Cluster5.use, value="Cluster5")
Cluster6.use <- WhichCells(mySeurat, idents=c("8","19","22"))
mySeurat <- SetIdent(mySeurat, cells=Cluster6.use, value="Cluster6")
Cluster7.use <- WhichCells(mySeurat, idents=c("9","15","18"))
mySeurat <- SetIdent(mySeurat, cells=Cluster7.use, value="Cluster7")
Cluster8.use <- WhichCells(mySeurat, idents=c("10"))
mySeurat <- SetIdent(mySeurat, cells=Cluster8.use, value="Cluster8")
Cluster9.use <- WhichCells(mySeurat, idents=c("12"))
mySeurat <- SetIdent(mySeurat, cells=Cluster9.use, value="Cluster9")
Cluster10.use <- WhichCells(mySeurat, idents=c("13"))
mySeurat <- SetIdent(mySeurat, cells=Cluster10.use, value="Cluster10")
Cluster11.use <- WhichCells(mySeurat, idents=c("14","27"))
mySeurat <- SetIdent(mySeurat, cells=Cluster11.use, value="Cluster11")
Cluster12.use <- WhichCells(mySeurat, idents=c("16"))
mySeurat <- SetIdent(mySeurat, cells=Cluster12.use, value="Cluster12")
Cluster13.use <- WhichCells(mySeurat, idents=c("17"))
mySeurat <- SetIdent(mySeurat, cells=Cluster13.use, value="Cluster13")
Cluster14.use <- WhichCells(mySeurat, idents=c("23"))
mySeurat <- SetIdent(mySeurat, cells=Cluster14.use, value="Cluster14")
Cluster15.use <- WhichCells(mySeurat, idents=c("25"))
mySeurat <- SetIdent(mySeurat, cells=Cluster15.use, value="Cluster15")
Cluster16.use <- WhichCells(mySeurat, idents=c("26"))
mySeurat <- SetIdent(mySeurat, cells=Cluster16.use, value="Cluster16")
Cluster17.use <- WhichCells(mySeurat, idents=c("28"))
mySeurat <- SetIdent(mySeurat, cells=Cluster17.use, value="Cluster17")
Cluster18.use <- WhichCells(mySeurat, idents=c("29"))
mySeurat <- SetIdent(mySeurat, cells=Cluster18.use, value="Cluster18")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=18)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1","Gad1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_SstFeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Sst"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Slc17a6Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Gad1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Esr1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Cyp19a1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Cyp19a1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Slc1a3Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc1a3"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_2600014E21RikFeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("2600014E21Rik"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Gm27199.pdf"))
FeaturePlot(mySeurat, features=c("Gm27199"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Sox6.pdf"))
FeaturePlot(mySeurat, features=c("Sox6"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Frem3.pdf"))
FeaturePlot(mySeurat, features=c("Frem3"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Grik3.pdf"))
FeaturePlot(mySeurat, features=c("Grik3"), reduction="umap")
dev.off()
mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpMale.filtered),
name = 'Upmale.score'
)
pdf(paste0(output,"_UMAP_Upmalemodule.pdf"))
FeaturePlot(mySeurat, features="Upmale.score1", cols = c("light blue", "red"))
dev.off()
mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpMalevPrimed.filtered),
name = 'UpmalevPrimed.score'
)
pdf(paste0(output,"_UMAP_UpmalevPrimedmodule.pdf"))
FeaturePlot(mySeurat, features="UpmalevPrimed.score1", cols = c("light blue", "red"))
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:30)
pdf(paste0(output,"_Intact_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
Pct <- DotPlot(mySeurat, features=UpMale.filtered)
sink(file=paste0(output,"_pctSDEGbyclust.txt"), append=FALSE, type=c("output","message"), split=FALSE)
Pct$data
sink()
pdf(file=paste0(output,"NSForest_Vln.pdf"), width=14, height=120)
VlnPlot(mySeurat, features=c("Nxph2", "Foxp2","Adarb2","Il1rapl2","Sox2ot","Stac2","6530403H02Rik","9330185C12Rik","Adarb2","Il1rapl2","Sox2ot","Zfhx4","Meis2","Chn2","Gm32647","Dock11","Sox2ot","Trhde","Sim1","Gm32647","Foxp2","Fam19a1","Hs3st4","Meis1","St18","Moxd1","Pde11a","Slc1a3","Zfpm2","Angpt1","Cntnap5c","Ptprk","Sfta3-ps","Esr2","Zfhx3","Gm48749","Sash1","Meis2","Adarb2","Arhgap24","Il1rapl2","Moxd1","Kcnmb2","Plagl1","Gfra1","Satb1","Hs3st4","Col19a1","Sema3a","Chst9","Meis2","Foxp2","Pde3a","Adarb2","Gpc3","Col18a1","Gm28928","Stxbp6","Fam19a1","Zfhx3","Reln","Hs6st3","Sntb1","Sim1","Fam19a2","Gm29771","Rasef","Sema3e","Spata13","Stk32a","Pgm5","E130114P18Rik","Ebf2","Pappa2","Gli3"), ncol=1, pt.size=0)
dev.off()
#pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=60)

#VlnPlot(mySeurat, features=c("Pappa2","Tac1","Vmn1r206","Ebf3","B020031H02Rik","Shisal2b","Gm27199","Slc1a3","Dcdc5","Frem3","Colgalt2","Sst","Ebf2","Avp","Eya4","Col5a1","Pde5a","Rspo2","Angpt1","Chd7","Sox6","Pde3a","Meis1","Eepd1"), pt.size=0, ncol=1)
#dev.off()
NSforest.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(NSforest.markers, file=paste0(output,"_NSForestmergeposmarkers.csv"))
#Node27.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="27", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node27.markers, file=paste0(output,"_Node27posmarkers.csv"))
#Node29.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="29", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node29.markers, file=paste0(output,"_Node29posmarkers.csv"))
#Node33.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="33", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node33.markers, file=paste0(output,"_Node33posmarkers.csv"))
#Node30.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="30", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node30.markers, file=paste0(output,"_Node30posmarkers.csv"))
#Node31.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="31", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node31.markers, file=paste0(output,"_Node31posmarkers.csv"))
#Node32.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="32", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node32.markers, file=paste0(output,"_Node32posmarkers.csv"))
#Node34.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="34", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node32.markers, file=paste0(output,"_Node34posmarkers.csv"))
#Node36.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="36", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node36.markers, file=paste0(output,"_Node36posmarkers.csv"))
#Node39.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="39", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node39.markers, file=paste0(output,"_Node39posmarkers.csv"))
#Node37.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="37", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Node37.markers, file=paste0(output,"_Node37posmarkers.csv"))
saveRDS(mySeurat, file=paste0(output,"Intact_Merged.rds"))