#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/MeA_IndependentAnalysis/MeA_Primed_Curated_40pcs"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/MeA_IndependentAnalysis/MeA_IndependentFiltered2_Primed_40pcs_Res1_Intact.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpPrimed <- read.table("Genelists/MeA_UpPrimedAll_Localnew.txt")
unlist(UpPrimed)
UpPrimed <- as.matrix(UpPrimed)
UpPrimed.filtered <- intersect(UpPrimed, genes.10x)
#Pappa2.use <- WhichCells(mySeurat, idents=c("29"))
#mySeurat <- SetIdent(mySeurat, cells=Pappa2.use, value="Pappa2")
#Tac1.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Tac1.use, value="Tac1")
#Vmn1r206.use <- WhichCells(mySeurat, idents=c("18"))
#mySeurat <- SetIdent(mySeurat, cells=Vmn1r206.use, value="Vmn1r206")
#Ebf3.use <- WhichCells(mySeurat, idents=c("24"))
#mySeurat <- SetIdent(mySeurat, cells=Ebf3.use, value="Ebf3")
#Slc1a3.use <- WhichCells(mySeurat, idents=c("4","11"))
#mySeurat <- SetIdent(mySeurat, cells=Slc1a3.use, value="Slc1a3")
#B020031H020Rik.use <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=B020031H020Rik.use, value="B020031H020Rik")
#Shisal2b.use <- WhichCells(mySeurat, idents=c("10","17"))
#mySeurat <- SetIdent(mySeurat, cells=Shisal2b.use, value="Shisal2b")
#Gm27199.use <- WhichCells(mySeurat, idents=c("8","22","19"))
#mySeurat <- SetIdent(mySeurat, cells=Gm27199.use, value="Gm27199")
#Dcdc5.use <- WhichCells(mySeurat, idents=c("5","14"))
#mySeurat <- SetIdent(mySeurat, cells=Dcdc5.use, value="Dcdc5")
#Frem3.use <- WhichCells(mySeurat, idents=c("6","1"))
#mySeurat <- SetIdent(mySeurat, cells=Frem3.use, value="Frem3")
#Colgalt2.use <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Colgalt2.use, value="Colgalt2")
#Sst.use <- WhichCells(mySeurat, idents=c("16"))
#mySeurat <- SetIdent(mySeurat, cells=Sst.use, value="Sst")
#Megf10.use <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=Megf10.use, value="Megf10")
#Ebf2.use <- WhichCells(mySeurat, idents=c("28"))
#mySeurat <- SetIdent(mySeurat, cells=Ebf2.use, value="Ebf2")
#Avp.use <- WhichCells(mySeurat, idents=c("27"))
#mySeurat <- SetIdent(mySeurat, cells=Avp.use, value="Avp")
#Eya4.use <- WhichCells(mySeurat, idents=c("26"))
#mySeurat <- SetIdent(mySeurat, cells=Eya4.use, value="Eya4")
#Col5a1.use <- WhichCells(mySeurat, idents=c("25"))
#mySeurat <- SetIdent(mySeurat, cells=Col5a1.use, value="Col5a1")
#Pde5a.use <- WhichCells(mySeurat, idents=c("23"))
#mySeurat <- SetIdent(mySeurat, cells=Pde5a.use, value="Pde5a")
#Rspo2.use <- WhichCells(mySeurat, idents=c("21"))
#mySeurat <- SetIdent(mySeurat, cells=Rspo2.use, value="Cyp19a1_Rspo2")
#Angpt1.use <- WhichCells(mySeurat, idents=c("12"))
#mySeurat <- SetIdent(mySeurat, cells=Angpt1.use, value="Angpt1_Chd7")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=18)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Slc32a1","Cyp19a1","Gad1"), pt.size=0, ncol=1)
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:30)
pdf(paste0(output,"_Intact_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(file=paste0(output,"_SstFeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Sst"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Slc17a6Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Gad1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Esr1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Cyp19a1Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Cyp19a1"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Slc1a3Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc1a3"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_SstFeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Sst"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Gm27199Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gm27199"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_Frem3Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Frem3"), reduction="umap")
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()

mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpPrimed.filtered),
name = 'UpPrimed.score'
)
pdf(paste0(output,"_UMAP_Upmalemodule.pdf"))
FeaturePlot(mySeurat, features="UpPrimed.score1", cols = c("light blue", "red"))
dev.off()
Node31.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="31", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Node31.markers, file=paste0(output,"_Node31posmarkers.csv"))
Node24.markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="24", only.pos=FALSE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Node31.markers, file=paste0(output,"_Node24posmarkers.csv"))
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=60)
VlnPlot(mySeurat, features=c("Pappa2","Tac1","Vmn1r206","Ebf3","B020031H02Rik","Shisal2b","Gm27199","Slc1a3","Dcdc5","Frem3","Colgalt2","Sst","Ebf2","Avp","Eya4","Col5a1","Pde5a","Rspo2","Angpt1","Chd7","Sox6","Pde3a","Meis1","Eepd1"), pt.size=0, ncol=1)
dev.off()
Ebf3.markers <- FindMarkers(mySeurat, ident.1="Ebf3", only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
write.csv(Ebf3.markers, file=paste0(output,"_Ebf3posmarkers.csv"))
#saveRDS(mySeurat, file=paste0(output,"Intact_Merged.rds"))