output <- "Seurat/POA_IndependentAnalysis/POA_Fullmerge_Test_CCAtestallstandardscaleDEGenforced_filtered2"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)


POA.comb <- readRDS("Seurat/POA_IndependentAnalysis/POA_Fullmerge_Test_CCAtestallstandardscaleDEGenforced_filtered1CCAscaledata_DEGsonly.rds")
POA.comb <- subset(POA.comb, idents=c("20"), invert=TRUE) 


DefaultAssay(POA.comb) <- "integrated"
POA.comb <- ScaleData(POA.comb, vars.to.regress="orig.ident")
POA.comb <- RunPCA(POA.comb)
POA.comb <- RunUMAP(POA.comb, reduction="pca", dims=1:30)
POA.comb <- FindNeighbors(POA.comb, reduction="pca", dims=1:30)
POA.comb <- FindClusters(POA.comb, resolution=1.2)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(POA.comb, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(POA.comb, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(POA.comb, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(POA.comb, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(POA.comb, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
t <- prop.table(table(Idents(POA.comb), POA.comb$Hormone), margin=2)
write.csv(t, file=paste0(output,"props.csv"))
DefaultAssay(POA.comb) <- "RNA"
POA.comb <- NormalizeData(POA.comb)
pdf(file=paste0(output,"MarkerVln.pdf"), width=32, height=20)
VlnPlot(POA.comb, features=c("Esr1","Pgr","Slc17a6","Gad1","Kiss1"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output,"_Kiss1vln.pdf"), width=20)
VlnPlot(POA.comb, features=c("Kiss1"), split.by="sex", pt.size=0)
dev.off()
mySeurat.markers <- FindAllMarkers(POA.comb, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25, test.use="MAST")
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
#top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
#DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
#dev.off()
saveRDS(POA.comb, file=paste0(output,"CCAscaledata_DEGsonly.rds"))