#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_IndependentAnalysis/POA_Primed_Curated_30PCs"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/POA_IndependentAnalysis/POA_IndependentFiltered2_30pcs_res1_Primed.rds")
Moxd1markers <- FindMarkers(mySeurat, ident.1="clustertree", ident.2="35")
write.csv(Moxd1markers, file=paste0(output,"Moxd1markers.csv"))
#Opn5.use <- WhichCells(mySeurat, idents=c("0"))
#mySeurat <- SetIdent(mySeurat, cells=Opn5.use, value="Opn5")
#Moxd1.use <- WhichCells(mySeurat, idents=c("12","25"))
#mySeurat <- SetIdent(mySeurat, cells=Moxd1.use, value="Moxd1")
#Elf4.use <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=Elf4.use, value="Elf4")
#Gbx1.use <- WhichCells(mySeurat, idents=c("4","25"))
#mySeurat <- SetIdent(mySeurat, cells=Gbx1.use, value="Gbx1")
#Thbs4.use <- WhichCells(mySeurat, idents=c("7"))
#mySeurat <- SetIdent(mySeurat, cells=Thbs4.use, value="Thbs4")
#Crym.use <- WhichCells(mySeurat, idents=c("8"))
#mySeurat <- SetIdent(mySeurat, cells=Crym.use, value="Crym")
#Ppfibp2.use <- WhichCells(mySeurat, idents=c("12"))
#mySeurat <- SetIdent(mySeurat, cells=Ppfibp2.use, value="Ppfibp2")
#Skor2.use <- WhichCells(mySeurat, idents=c("13"))
#mySeurat <- SetIdent(mySeurat, cells=Skor2.use, value="Skor2")
#Sim1.use <- WhichCells(mySeurat, idents=c("14"))
#mySeurat <- SetIdent(mySeurat, cells=Sim1.use, value="Sim1")
#Tcf7l2.use <- WhichCells(mySeurat, idents=c("15"))
#mySeurat <- SetIdent(mySeurat, cells=Tcf7l2.use, value="Tcf7l2")
#Lix1.use <- WhichCells(mySeurat, idents=c("18"))
#mySeurat <- SetIdent(mySeurat, cells=Lix1.use, value="Lix1")
#Smoc2.use <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=Smoc2.use, value="Smoc2")
#Nr2f1.use <- WhichCells(mySeurat, idents=c("20"))
#mySeurat <- SetIdent(mySeurat, cells=Nr2f1.use, value="Nr2f1")
#Zeb2.use <- WhichCells(mySeurat, idents=c("5","12"))
#mySeurat <- SetIdent(mySeurat, cells=Zeb2.use, value="Zeb2")
#Plod2.use <- WhichCells(mySeurat, idents=c("6","10"))
#mySeurat <- SetIdent(mySeurat, cells=Plod2.use, value="Plod2")
#Folh1.use <- WhichCells(mySeurat, idents=c("22"))
#mySeurat <- SetIdent(mySeurat, cells=Folh1.use, value="Folh1")
#Chat.use <- WhichCells(mySeurat, idents=c("23"))
#mySeurat <- SetIdent(mySeurat, cells=Chat.use, value="Chat1")
#Gldc.use <- WhichCells(mySeurat, idents=c("9","28"))
#mySeurat <- SetIdent(mySeurat, cells=Gldc.use, value="Gldc")
#Fam20a.use <- WhichCells(mySeurat, idents=c("11"))
#mySeurat <- SetIdent(mySeurat, cells=Fam20a.use, value="Fam20a")
#Tgfbi.use <- WhichCells(mySeurat, idents=c("27"))
#mySeurat <- SetIdent(mySeurat, cells=Tgfbi.use, value="Tgfbi")
#Ret.use <- WhichCells(mySeurat, idents=c("11","18"))
#mySeurat <- SetIdent(mySeurat, cell=Ret.use, value="Ret")
#Svil.use <- WhichCells(mySeurat, idents=c("1","17"))
#mySeurat <- SetIdent(mySeurat, cells=Svil.use, value="Svil")
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:30)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(paste0(output,"_Fbn2.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Fbn2"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Esr1.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Esr1"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Thbs4.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Thbs4"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Esr2.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Esr2"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Bmp3.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Bmp3"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Abtb2.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Abtb2"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Th.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Th"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Cd24a.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Cd24a"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Slc18a2.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Slc18a2"),cols = c("light blue", "red"))
dev.off()
pdf(paste0(output,"_Th.pdf"))
FeaturePlot(mySeurat, reduction="umap", features=c("Th"),cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Exph5Vln.pdf"), width=14, height=4)
VlnPlot(mySeurat, features=c("Exph5"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr2","Esr1", "Slc17a6","Slc32a1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=80)
VlnPlot(mySeurat, features=c("Abtb2","Exph5","Sytl4","Th","Bmp3","Slc18a2","Esr2","Fbn2","Svil","Tgfbi","Fam20a","Gldc","Chat","Folh1","Plod2","Zeb2","Nr2f1","Smoc2","Lix1","Tcf7l2","Sim1","Skor2","Ppfibp2","Crym","Thbs4","Gbx1","Elf4","Moxd1","Opn5"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindMarkers(mySeurat, ident.1="Unknown", only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_Unknownposmarkers.csv"))