#!/usr/bin/env Rscript

output <- "Seurat/POA_IndependentAnalysis/POA_Fullmerge_Test_SCT"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
PrimedPOA <- readRDS("Seurat/POA_IndependentAnalysis/POA_IndependentFiltered2_30pcs_res1_Primed.rds")
MalePOA <- readRDS("Seurat/POA_IndependentAnalysis/POA_IndependentFiltered7_40pcs_res1.5_Intact.rds")
UnprimedPOA <- readRDS("Seurat/POA_IndependentAnalysis/POA_IndependentFiltered2_30pcs_Unprimed_res1_Unprimed.rds")
#PrimedPOA <- SCTransform(PrimedPOA)
#MalePOA <- SCTransform(MalePOA)
#UnprimedPOA <- SCTransform(UnprimedPOA)
MalePOA$sex <- "Male"
MalePOA$Hormone <- "Intact"
PrimedPOA$sex <- "Female"
PrimedPOA$Hormone <- "Primed"
UnprimedPOA$sex <- "Female"
UnprimedPOA$Hormone <- "Unprimed"
list <- c(MalePOA,UnprimedPOA,PrimedPOA)
POA.features <- SelectIntegrationFeatures(object.list=list, nfeatures=3000)
POA.list <- PrepSCTIntegration(list, anchor.features=POA.features, verbose=TRUE)
POA.anchors <- FindIntegrationAnchors(POA.list, normalization.method="SCT", anchor.features=POA.features, verbose=TRUE)
mySeurat <- IntegrateData(anchorset=POA.anchors, normalization.method="SCT", verbose=FALSE)
mySeurat <- RunPCA(mySeurat)
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))