#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_IndependentAnalysis/POA_Merge_Paperplots"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/POA_IndependentAnalysis/POA_Fullmerge_Test.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpMale <- read.table("Genelists/POA_MvP_UpMale1.5.txt")
unlist(UpMale)
UpMale <- as.matrix(UpMale)
UpMale.filtered <- intersect(UpMale, genes.10x)
mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpMale.filtered),
name = 'UpMale.score'
)
UpPrimed <- read.table("Genelists/POA_PvU_UpPrimed1.5.txt")
unlist(UpPrimed)
UpPrimed <- as.matrix(UpPrimed)
UpPrimed.filtered <- intersect(UpPrimed, genes.10x)
mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpPrimed.filtered),
name = 'UpPrimed.score'
)
UpFemale <- read.table("Genelists/POA_MvP_UpFemale1.5.txt")
unlist(UpFemale)
UpFemale <- as.matrix(UpFemale)
UpFemale.filtered <- intersect(UpFemale, genes.10x)
mySeurat <- AddModuleScore(
object = mySeurat,
features = list(UpFemale.filtered),
name = 'UpFemale.score'
)
pdf(paste0(output,"_upmale_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpMale.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upmale_hormonesplit.pdf"))
FeaturePlot(mySeurat, features=c("UpMale.score1"), split.by="Hormone", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upmale_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpMale.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upmale.pdf"))
FeaturePlot(mySeurat, features=c("UpMale.score1"), col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"upmaleVln.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpMale.score1"), pt.size=0)
dev.off()
pdf(paste0(output,"upmaleVln_sexsplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpMale.score1"), split.by="sex", pt.size=0)
dev.off()
pdf(paste0(output,"upmaleVln_hormonesplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpMale.score1"), split.by="Hormone", pt.size=0)
dev.off()
pdf(paste0(output,"_upfemale_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpFemale.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upfemale_hormonesplit.pdf"))
FeaturePlot(mySeurat, features=c("UpFemale.score1"), split.by="Hormone", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upfemale_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpFemale.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upfemale.pdf"))
FeaturePlot(mySeurat, features=c("UpFemale.score1"), col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"upfemaleVln.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpFemale.score1"), pt.size=0)
dev.off()
pdf(paste0(output,"upfemaleVln_sexsplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpFemale.score1"), split.by="sex", pt.size=0)
dev.off()
pdf(paste0(output,"upfemaleVln_hormonesplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpFemale.score1"), split.by="Hormone", pt.size=0)
dev.off()
pdf(paste0(output,"nUMI.pdf"), width=20)
VlnPlot(mySeurat, features=c("nCount_RNA"), split.by="Hormone", pt.size=0)
dev.off()
pdf(paste0(output,"_upprimed_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpPrimed.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upprimed_hormonesplit.pdf"))
FeaturePlot(mySeurat, features=c("UpPrimed.score1"), split.by="Hormone", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upprimed_sexsplit.pdf"))
FeaturePlot(mySeurat, features=c("UpPrimed.score1"), split.by="sex", col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"_upprimed.pdf"))
FeaturePlot(mySeurat, features=c("UpPrimed.score1"), col=c("blue","orange"), order=TRUE)
dev.off()
pdf(paste0(output,"upprimedVln.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpPrimed.score1"), pt.size=0)
dev.off()
pdf(paste0(output,"upprimedVln_sexsplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpPrimed.score1"), split.by="sex", pt.size=0)
dev.off()
pdf(paste0(output,"upprimedVln_hormonesplit.pdf"), width=20)
VlnPlot(mySeurat, features=c("UpPrimed.score1"), split.by="Hormone", pt.size=0)
dev.off()