#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filteyellow_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimedMerged_Exploratory/Doubletsremoved_fullfilteyellow_plots"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_doubletsremoved_filteyellow3.rds")
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(mySeurat, cols=c("grey","yellow"), features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(mySeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(mySeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(mySeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(mySeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(mySeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(mySeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(mySeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(mySeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(mySeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(mySeurat, features = c("percent.mt"), pt.size=0)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
