#!/usr/bin/env Rscript

output <- "Seurat/FullPOA_Integrated/FullPOA_exploratory_"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
MalePOA.data <- Read10X(data.dir = "MalePOAIntact/outs/filtered_feature_bc_matrix")
PrimedPOA.data <- Read10X(data.dir = "FemalePOAPrimed/outs/filtered_feature_bc_matrix")
UnprimedPOA.data <- Read10X(data.dir = "FemalePOAPrimed/outs/filtered_feature_bc_matrix")
MalePOA <- CreateSeuratObject(counts = MalePOA.data, project="MalePOA", min.cells=3, min.features=200)
PrimedPOA <- CreateSeuratObject(counts = PrimedPOA.data, project="UnprimedPOA", min.cells=3, min.features=200)
UnprimedPOA <- CreateSeuratObject(counts = UnprimedPOA.data, project="UnprimedPOA", min.cells=3, min.features=200)
MalePOA <- subset(MalePOA, subset=nCount_RNA < 60000)
UnprimedPOA <- subset(UnprimedPOA, subset=nCount_RNA <55000)
PrimedPOA <- subset(PrimedPOA, subset=nCount_RNA < 55000)
MalePOA <- SCTransform(MalePOA, verbose=TRUE)
PrimedPOA <- SCTransform(PrimedPOA, verbose=TRUE)
UnprimedPOA <- SCTransform(UnprimedPOA, verbose=TRUE)
MalePOA$state <- "Intact"
PrimedPOA$state <- "Primed"
UnprimedPOA$state <- "Unprimed"
MalePOA$sex <- "Male"
PrimedPOA$sex <- "Female"
UnprimedPOA$sex <- "Female"
Shared.features <- SelectIntegrationFeatures(object.list=list(MalePOA,PrimedPOA,UnprimedPOA), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(MalePOA,PrimedPOA,UnprimedPOA), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
Full.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=FALSE, features.to.integrate=rownames(Full.integrated))
Full.integrated <- RunPCA(Full.integrated, verbose=TRUE)
Full.integrated <- RunUMAP(Full.integrated, dims=1:30)
Full.integrated <- FindNeighbors(Full.integrated, dims=1:30)
Full.integrated <- FindClusters(Full.integrated, resolution=0.5)
pdf("Seurat/Seurat_10x1stpast_FullUmap_Sctransform.pdf")
DimPlot(Full.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output, "umap_sexsplit.pdf"))
DimPlot(Full.integrated, reduction="umap", split.by="sex", label=TRUE)
dev.off()
pdf(paste0(output, "umap_statesplit.pdf"))
DimPlot(Full.integrated, reduction="umap", split.by="state", label=TRUE)
dev.off()
pdf(paste0(output, "umap_sexlabel.pdf"))
DimPlot(Full.integrated, reduction="umap", group.by="sex")
dev.off()
pdf(paste0(output, "umap_statelabel.pdf"))
DimPlot(Full.integrated, reduction="umap", group.by="state")
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Full.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Full.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
Full.integrated.markers <- FindAllMarkers(Full.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Full.integrated.markers, file=paste0(output, "cluster_markers.csv"))
top10 <- Full.integrated.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
pdf(paste0(output, "topmarkerheatmap"))
DoHeatmap(Full.integrated, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Full.integrated, file=(paste0(output, ".rds")))
