#!/usr/bin/env Rscript
output <- "Seurat/VMH_SCTpostmerge/VMH_SCTpostmerge"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(Matrix)
library(matrixStats)
library(qlcMatrix)
library(igraph)
library(RANN)
MaleVMH.data <- Read10X(data.dir = "FemalePOAPrimed_Putative2/outs/filtered_feature_bc_matrix")
MaleVMH <- CreateSeuratObject(counts = MaleVMH.data, project = "MaleVMH", min.cells=3, min.features=200)
PrimedVMH.data <- Read10X(data.dir= "FemaleVMHPrimed/outs/filtered_feature_bc_matrix")
PrimedVMH <- CreateSeuratObject(counts = PrimedVMH.data, project = "PrimedVMH", min.cells=3, min.features=200)
MaleVMH$sex <- "Male"
PrimedVMH$sex <- "Female"
mySeurat <- merge(MaleVMH, y=c(PrimedVMH), add.cell.ids=c("MaleVMH","PrimedVMH"), project="Merged")
mySeurat <- subset(mySeurat, subset=nCount_RNA < 60000)
mySeurat <- SCTransform(mySeurat, verbose=TRUE, vars.to.regress="orig.ident")
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat))
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1.5)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat,reduction="umap", label=TRUE, group.by="sex")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))


