#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/BNST_MalevUnprimed_Exploratory/Doubletsremoved_fullfiltered_plots"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
mySeurat <- readRDS("Seurat/BNST_MalevUnprimed_Exploratory/BNST_MalevUnprimed_doubletsremoved_filtered2.rds")
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc18a2"))
dev.off()
pdf(paste0(output,"_Smoc2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Smoc2"))
dev.off()
pdf(paste0(output,"_Opn5featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Opn5"))
dev.off()
pdf(paste0(output,"_Elf4featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Elf4"))
dev.off()
pdf(paste0(output,"_St18featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("St18"))
dev.off()
pdf(paste0(output,"_Trp73featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Trp73"))
dev.off()
pdf(paste0(output,"_Zeb2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Zeb2"))
dev.off()
pdf(paste0(output,"_Penkfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Penk"))
dev.off()
pdf(paste0(output,"_Gbx1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gbx1"))
dev.off()
pdf(paste0(output,"_Skor2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Skor2"))
dev.off()
pdf(paste0(output,"_Meis2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Meis2"))
dev.off()
pdf(paste0(output,"_Npsr1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Npsr1"))
dev.off()
pdf(paste0(output,"_Lgr5featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Lgr5"))
dev.off()
pdf(paste0(output,"_Meis1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Meis1"))
dev.off()
pdf(paste0(output,"_Lcp1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Lcp1"))
dev.off()
pdf(paste0(output,"_Meox2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Meox2"))
dev.off()
pdf(paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Cyp19a1"))
dev.off()
pdf(paste0(output,"_Tac1.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Tac1"))
dev.off()
pdf(paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Cckar"))
dev.off()
pdf(paste0(output,"_Cckfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Cck"))
dev.off()
pdf(paste0(output,"_Pappafeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Pappa"))
dev.off()
pdf(paste0(output,"_Hbbbsfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Hbb-bs"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(mySeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(mySeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(mySeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(mySeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(mySeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(mySeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(mySeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(mySeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(mySeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(mySeurat, features = c("percent.mt"), pt.size=0)
saveRDS(mySeurat, file=(paste0(output, ".rds")))
