#!/usr/bin/env Rscript

output <- "Seurat/MeA_SCTPostMerge/MeA_SCTpostmerge_filter1"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Sex.integrated <- readRDS("Seurat/MeA_SCTPostMerge/MeA_SCTpostmerge.rds")
Sex.integrated <- subset(Sex.integrated, idents=c("38","32","27","26"), invert=TRUE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=1.5)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(Sex.integrated,reduction="umap", label=TRUE, group.by="sex")
dev.off()
Sex.integrated.markers <- FindAllMarkers(Sex.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Sex.integrated.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- Sex.integrated.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Sex.integrated, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
