#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/UnprimedBNST_Preprocessing/UnprimedBNST_preprocessing_TRAPtest"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Seurat.data <- Read10X(data.dir = "FemaleBNSTUnprimed/outs/filtered_feature_bc_matrix")
mySeurat <- CreateSeuratObject(counts = Seurat.data, project = sampleID, min.cells=3, min.features=200)
pdf(paste0(output, "_basic_counts.pdf"))
VlnPlot(mySeurat, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(mySeurat, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
pdf(paste0(output, "_Esr1counts.pdf"))
VlnPlot(mySeurat, features = c("Esr1"))
dev.off()
mySeurat <- subset(mySeurat, subset=nFeature_RNA < 55000)
mySeurat <- SCTransform(mySeurat, verbose=TRUE)
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat))
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=0.5)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat2 <- RunTSNE(mySeurat, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(mySeurat2, reduction="tsne", do.label=TRUE)
dev.off()
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(mySeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(mySeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(mySeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(mySeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(mySeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(mySeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(mySeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(mySeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(mySeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(mySeurat, features = c("percent.mt"), pt.size=0)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
head(mySeurat[[]])
head(mySeurat)
mySeurat[["cluster"]] <- Idents(object = mySeurat)
Idents(mySeurat) <- '1'
MaleTRAP <- read.table("Genelists/BNST_MalevUnprimed_Upmale.txt")
MaleTRAP <- unlist(MaleTRAP)
FemaleTRAP <- read.table("Genelists/BNST_MalevUnprimed_UpUnprimed.txt")
FemaleTRAP <- unlist(FemaleTRAP)
genes <- rownames(mySeurat)
genes <- as.matrix(genes)
Maleup.present <- intersect(genes,MaleTRAP)
dim(Maleup.present)
Femaleup.present <- intersect(genes,FemaleTRAP)
FemaleTRAP.exp <- AverageExpression(mySeurat, features=Femaleup.present, verbose=TRUE)
mySeurat[["FemaleTRAP.exp"]] <- FemaleTRAP.exp
pdf(paste0(output,"FemaleTRAP.pdf"))
FeaturePlot(mySeurat, features=c("FemaleTRAP.score"))
dev.off()
MaleTRAP.exp <- AverageExpression(mySeurat, features=Maleup.present, slot="counts", verbose=TRUE, return.seurat=TRUE)
mySeurat[["MaleTRAP.exp"]] <- MaleTRAP.exp
FemaleTRAP.exp <- AverageExpression(mySeurat, features=Femaleup.present, slot="counts", verbose=TRUE, return.seurat=TRUE)
mySeurat[["FemaleTRAP.exp"]] <- FemaleTRAP.exp
pdf(paste0(output,"MaleTRAP.pdf"))
FeaturePlot(mySeurat, features=c("MaleTRAP.score"))
dev.off()
pdf(paste0(output,"FemaleTRAP.pdf"))
FeaturePlot(mySeurat, features=c("FemaleTRAP.score"))
dev.off()
pdf(paste0(output,"CombinedTRAP.pdf"))
FeaturePlot(mySeurat, features=c("MaleTRAP.score", "FemaleTRAP.score"), blend=TRUE, cols=c("grey","blue","pink")
dev.off()
Idents(mySeurat) <- 'cluster'
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
