#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/Anderson/RealGroupHoused_"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Rep1.data <- Read10X(data.dir = "2019_0325")
Rep1 <- CreateSeuratObject(counts = Rep1.data, project = "GroupRep1", min.cells=3, min.features=200)
Rep1 <- SCTransform(Rep1, verbose=TRUE)
Rep1 <- RunPCA(Rep1, verbose=TRUE)
Rep1 <- FindNeighbors(Rep1, dims=1:30)
Rep1 <- FindClusters(Rep1, resolution=1)
Rep1 <- RunUMAP(Rep1, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Rep1, reduction="umap", do.label=TRUE)
dev.off()
Rep12 <- RunTSNE(Rep1, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(Rep12, reduction="tsne", do.label=TRUE)
dev.off()
DefaultAssay(Rep1) <- "RNA"
NormalizeData(Rep1)
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(Rep1, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(Rep1, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(Rep1, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Th"))
dev.off()
pdf(paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Avp"))
dev.off()
pdf(paste0(output,"_Hcrtfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Hcrt"))
dev.off()
pdf(paste0(output,"_Gnrh1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Gnrh1"))
dev.off()
pdf(paste0(output,"_Trhfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Trh"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(Rep1, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(Rep1, features=c("Slc18a2"))
dev.off()
pdf(paste0(output,"_Nr5a1featureplot.pdf"))
FeaturePlot(Rep1, features=c("Nr5a1"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(Rep1, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(Rep1, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(Rep1, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(Rep1, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Avp.pdf"))
VlnPlot(Rep1, features = c("Avp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Qfrp.pdf"))
VlnPlot(Rep1, features = c("Qrfp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Trh.pdf"))
VlnPlot(Rep1, features = c("Trh"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Nr5a1.pdf"))
VlnPlot(Rep1, features = c("Nr5a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Hcrt.pdf"))
VlnPlot(Rep1, features = c("Hcrt"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gnrh1.pdf"))
VlnPlot(Rep1, features = c("Gnrh1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(Rep1, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(Rep1, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(Rep1, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(Rep1, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(Rep1, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Rep1, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Rep1, features = c("nFeature_RNA"), pt.size=0)
dev.off()
Rep1[["percent.mt"]] <- PercentageFeatureSet(Rep1, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(Rep1, features = c("percent.mt"), pt.size=0)
dev.off()
Rep1.markers <- FindAllMarkers(Rep1, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Rep1.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- Rep1.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Rep1, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Rep1, file=(paste0(output, ".rds")))
