#!/usr/bin/env Rscript

output <- "Seurat/BNST_MalevUnprimed_Exploratory/BNST_MalevUnprimed_Exploratory_doubletsremoved"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Male <- readRDS(file = "Seurat/MaleBNST_Preprocessing/MaleBNST_Doubletfinder_doublets.RDS")
UpdateSeuratObject(Male)
Male <- subset(Male, subset.name="DF.classifications_0.25_0.09_27", accept.value="Singlet")
Unprimed <- readRDS(file = "Seurat/UnprimedBNST_Preprocessing/UnprimedBNST_doubletsremoved_.rds")
head(Male)
head(Unprimed)
head(Male[[]])
head(Unprimed[[]])
Male$sex <- "Male"
Unprimed$sex <- "Female"
Shared.features <- SelectIntegrationFeatures(object.list=list(Male,Unprimed), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(Male,Unprimed), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
Sex.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=FALSE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=1.5)
pdf(paste0(output,"_UMAP_1.5.pdf"))
DimPlot(Sex.integrated, reduction="umap", do.label=TRUE)
dev.off()
Sex.integrated.markers <- FindAllMarkers(Sex.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Sex.integrated.markers, file=paste0(output, "_allposmarkers.csv"))
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
