#!/usr/bin/env Rscript
output <- "Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate_filtered1_ExcludeDE_Niraoplots_1res_20pcs"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate.rds")
mySeurat <- subset(mySeurat, idents=c("0","39","36","26","25"), invert=TRUE)
genelist <- read.table("Genelists/Sexchrom.txt", header=FALSE)
genelist
genelist <- unlist(genelist)
genelist
genelist <- as.matrix(genelist)
genelist
DE <- read.table("Genelists/VMH_allDEnew.txt", header=FALSE)
DE <- unlist(DE)
DE <- as.matrix(DE)
mySeurat
head(mySeurat[[]])
hvg <- mySeurat@assays$SCT@var.features
hvg <- unlist(hvg)
hvg
hvg <- as.matrix(hvg)
hvg.1 <- setdiff(hvg, genelist)
hvg.final <- setdiff(hvg.1, DE)
hvg.final
mySeurat <- RunPCA(mySeurat, features=hvg.final)
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:20)
mySeurat <- FindClusters(mySeurat, resolution=1)
mySeurat <- RunUMAP(mySeurat, dims=1:20)
mySeurat <- RunTSNE(mySeurat, dims=1:20)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_TSNE.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_umap.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="umap", cols=c("yellow","purple"), label=FALSE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_tsne.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="tsne", cols=c("yellow","purple"),  label=FALSE)
dev.off()
pdf(file=paste0(output, "Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1","Pgr","Cckar"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat,reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_statussplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="status")
dev.off()
pdf(paste0(output,"_UMAP_statuslabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="status")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))

