#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
Esr1BNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_antisenseGFP_v3-1_local_long/outs/filtered_feature_bc_matrix")
LigerMale3a.data <- Read10X(data.dir= "BNST_LIGER_Male3a/outs/filtered_feature_bc_matrix")
Esr1BNST <- CreateSeuratObject(counts = Esr1BNST.data, project ="MaleBNST", min.cells=3, min.features=200)
LigerMale3 <- CreateSeuratObject(counts = LigerMale3a.data, project="LIGER", min.cells=3, min.features=200)
Esr1BNST <- NormalizeData(Esr1BNST, verbose=TRUE)
Esr1BNST <- FindVariableFeatures(Esr1BNST, selection.method= "vst", nfeatures=2000) 
LigerMale3 <- NormalizeData(LigerMale3, verbose=TRUE)
LigerMale3 <- FindVariableFeatures(LigerMale3, selection.method= "vst", nfeatures=2000)
Esr1BNST$library <- "Shah"
LigerMale3$library <- "Liger"
BNST.anchors <- FindIntegrationAnchors(object.list=list(Esr1BNST,LigerMale3), dims=1:30)
BNST.integrated <- IntegrateData(anchorset = BNST.anchors, dims=1:30)
DefaultAssay(BNST.integrated) <- "integrated"
BNST.integrated <- ScaleData(BNST.integrated, verbose=TRUE)
BNST.integrated <- RunPCA(BNST.integrated, npcs=30, verbose=TRUE)
BNST.integrated <- RunUMAP(BNST.integrated, reduction="pca", dim=1:30)
BNST.integrated <- FindNeighbors(BNST.integrated, reduction ="pca", dims=1:30)
BNST.integrated <- FindClusters(BNST.integrated, resolution=0.5)
pdf(file="Seurat_BNSTintegrated_Test.pdf")
p1 <- DimPlot(BNST.integrated, reduction="umap", group.by ="library")
p2 <- DimPlot(BNST.integrated, reduction="umap", label=TRUE)
plot_grid(p1, p2)
dev.off()
pdf(file="Seurat_BNSTintegrated_Sidebyside.pdf")
DimPlot(BNST.integrated, reduction="umap", split.by="library")
dev.off()
DefaultAssay(BNST.integrated) <- "RNA"
BNST.markers <- FindConservedMarkers(BNST.integrated, ident.1= 5, grouping.var = "library", verbose=TRUE)
head(BNST.markers)
BNST.integrated$celltype.library <- paste(Idents(BNST.integrated), BNST.integrated$library, sep="_")
BNST.integrated$celltype <- Idents(BNST.integrated)
Idents(BNST.integrated) <- "celltype.library"
library.diff5 <- FindMarkers(BNST.integrated, ident.1 = "5_Shah", ident.2="5_Liger", verbose=FALSE)
write.csv(library.diff5, file="Seurat_out/LIGERtest/cluster5Male_libdiffs.csv")
library.diff17 <- FindMarkers(BNST.integrated, ident.1 = "17_Shah", ident.2="17_Liger", verbose=FALSE)
write.csv(library.diff17, file="Seurat_out/LIGERtest/cluster17Male_libdiffs.csv")
library.diff8 <- FindMarkers(BNST.integrated, ident.1 = "8_Shah", ident.2="8_Liger", verbose=FALSE)
write.csv(library.diff8, file="Seurat_out/LIGERtest/cluster8Male_libdiffs.csv")
library.diff9 <- FindMarkers(BNST.integrated, ident.1 = "9_Shah", ident.2="9_Liger", verbose=FALSE)
write.csv(library.diff9, file="Seurat_out/LIGERtest/cluster9Male_libdiffs.csv")
library.diff3 <- FindMarkers(BNST.integrated, ident.1 = "3_Shah", ident.2="3_Liger", verbose=FALSE)
write.csv(library.diff3, file="Seurat_out/LIGERtest/cluster3Male_libdiffs.csv")
library.diff4 <- FindMarkers(BNST.integrated, ident.1 = "4_Shah", ident.2="4_Liger", verbose=FALSE)
write.csv(library.diff4, file="Seurat_out/LIGERtest/cluster4Male_libdiffs.csv")
library.diff6 <- FindMarkers(BNST.integrated, ident.1 = "6_Shah", ident.2="6_Liger", verbose=FALSE)
write.csv(library.diff6, file="Seurat_out/LIGERtest/cluster6Male_libdiffs.csv")
library.diff7 <- FindMarkers(BNST.integrated, ident.1 = "7_Shah", ident.2="7_Liger", verbose=FALSE)
write.csv(library.diff7, file="Seurat_out/LIGERtest/cluster7Male_libdiffs.csv")
library.diff14 <- FindMarkers(BNST.integrated, ident.1 = "14_Shah", ident.2="14_Liger", verbose=FALSE)
write.csv(library.diff14, file="Seurat_out/LIGERtest/cluster14Male_libdiffs.csv")
library.diff11 <- FindMarkers(BNST.integrated, ident.1 = "11_Shah", ident.2="11_Liger", verbose=FALSE)
write.csv(library.diff14, file="Seurat_out/LIGERtest/cluster11Male_libdiffs.csv")
library.diff14 <- FindMarkers(BNST.integrated, ident.1 = "14_Shah", ident.2="14_Liger", verbose=FALSE)
write.csv(library.diff14, file="Seurat_out/LIGERtest/cluster14Male_libdiffs.csv")
library.diff10 <- FindMarkers(BNST.integrated, ident.1 = "10_Shah", ident.2="10_Liger", verbose=FALSE)
write.csv(library.diff10, file="Seurat_out/LIGERtest/cluster10Male_libdiffs.csv")
library.diff15 <- FindMarkers(BNST.integrated, ident.1 = "15_Shah", ident.2="15_Liger", verbose=FALSE)
write.csv(library.diff15, file="Seurat_out/LIGERtest/cluster15Male_libdiffs.csv")
library.diff18 <- FindMarkers(BNST.integrated, ident.1 = "18_Shah", ident.2="18_Liger", verbose=FALSE)
write.csv(library.diff18, file="Seurat_out/LIGERtest/cluster18Male_libdiffs.csv")
library.diff2 <- FindMarkers(BNST.integrated, ident.1 = "2_Shah", ident.2="2_Liger", verbose=FALSE)
write.csv(library.diff2, file="Seurat_out/LIGERtest/cluster2Male_libdiffs.csv")
pdf("Seurat_candidates_1.pdf")
FeaturePlot(BNST.integrated, features = c("Pappa", "Cyp19a1", "Ar"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_2.pdf")
FeaturePlot(BNST.integrated, features = c("Cckar", "Greb1", "Sytl4"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_3.pdf")
FeaturePlot(BNST.integrated, features = c("Esr1", "Brs3", "Ecel1"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_4.pdf")
FeaturePlot(BNST.integrated, features = c("Cartpt", "Pak3", "Glra3"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_5.pdf")
FeaturePlot(BNST.integrated, features = c("St18", "Herc1", "Moxd1"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_6.pdf")
FeaturePlot(BNST.integrated, features = c("Gpr88", "Ezr", "Cd24a"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()

