#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(sctransform)
library(ggplot2)
MaleBNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_antisenseGFP_v3-1_local_long/outs/filtered_feature_bc_matrix")
LigerFemale2a.data <- Read10X(data.dir= "BNST_LIGER_Female2a/outs/filtered_feature_bc_matrix")
LigerFemale3a.data <- Read10X(data.dir= "BNST_LIGER_Female3a/outs/filtered_feature_bc_matrix")
Male <- CreateSeuratObject(counts = MaleBNST.data, project ="MaleBNST", min.cells=3, min.features=200)
Male$Sex <- "MALE"
Female2 <- CreateSeuratObject(counts = LigerFemale2a.data, project="LIGER", min.cells=3, min.features=200)
Female2$Sex <- "FEMALE"
Female3 <- CreateSeuratObject(counts = LigerFemale3a.data, project="LIGER", min.cells=3, min.features=200)
Female3$Sex <- "FEMALE"
Male <- subset(Male, subset = nFeature_RNA > 500)
Male <- NormalizeData(Male, verbose=TRUE)
Male <- FindVariableFeatures(Male, selection.method= "vst", nfeatures=2000)
top20male <- head(VariableFeatures(Male), 20)
pdf(file="Seurat_BNSTMaleVariablefeatures.pdf")
plot1 <- VariableFeaturePlot(Male)
LabelPoints(plot=plot1, points=top20male, repel=TRUE)
dev.off()
Female2 <- subset(Female2, subset = nFeature_RNA > 500) 
Female2 <- NormalizeData(Female2, verbose=TRUE)
Female2 <- FindVariableFeatures(Female2, selection.method= "vst", nfeatures=2000)
top20female2 <- head(VariableFeatures(Female2), 20)
pdf(file="Seurat_LIGERFemale2Variablefeatures.pdf")
plot2 <- VariableFeaturePlot(Female2)
LabelPoints(plot=plot1, points=top20female2, repel=TRUE)
dev.off()
Female3 <- subset(Female3, subset = nFeature_RNA > 500)
Female3 <- NormalizeData(Female3, verbose=TRUE)
Female3 <- FindVariableFeatures(Female3, selection.method= "vst", nfeatures=2000)
top20female3 <- head(VariableFeatures(Female3), 20)
pdf(file="Seurat_LIGERFemale3Variablefeatures.pdf")
plot3 <- VariableFeaturePlot(Female3)
LabelPoints(plot=plot1, points=top20female3, repel=TRUE)
dev.off()
sex.anchors <- FindIntegrationAnchors(object.list=list(Male,Female2,Female3), dims=1:20)
sex.combined <- IntegrateData(anchorset = sex.anchors, dims=1:20)
DefaultAssay(sex.combined) <- "integrated"
sex.combined <- ScaleData(sex.combined, verbose=TRUE)
sex.combined <- RunPCA(sex.combined, npcs=30, verbose=TRUE)
sex.combined <- RunUMAP(sex.combined, reduction="pca", dim=1:20)
sex.combined <- FindNeighbors(sex.combined, reduction ="pca", dims=1:20)
sex.combined <- FindClusters(sex.combined, resolution=0.5)
pdf(file="Seurat_Sex_Combined_Test_extended.pdf")
p1 <- DimPlot(sex.combined, reduction="umap", group.by ="Sex")
p2 <- DimPlot(sex.combined, reduction="umap", label=TRUE)
plot_grid(p1, p2)
dev.off()
pdf(file="Seurat_Sidebyside_extended.pdf")
DimPlot(sex.combined, reduction="umap", split.by="Sex")
dev.off()
DefaultAssay(sex.combined) <- "RNA"
sex.markers <- FindConservedMarkers(sex.combined, ident.1= 5, grouping.var = "Sex", verbose=TRUE)
head(sex.markers)
pdf(file="Seurat_Featureplot_extended.pdf")
FeaturePlot(sex.combined, features = c("Pappa","Cyp19a1","Esr1","Greb1","St18","Moxd1","Ar","Rps6ka6","Cckar","Brs3","Crim1","Pgr","Ecel1"))
dev.off()
sex.combined$celltype.sex <- paste(Idents(sex.combined), sex.combined$Sex, sep="_")
sex.combined$celltype <- Idents(sex.combined)
Idents(sex.combined) <- "celltype.sex"
sex.dimorphism5 <- FindMarkers(sex.combined, ident.1 = "5_MALE", ident.2="5_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism5, file="Seurat_out/LIGERtest/cluster5dimorphisms.csv")
sex.dimorphism17 <- FindMarkers(sex.combined, ident.1 = "17_MALE", ident.2="17_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism17, file="Seurat_out/LIGERtest/cluster17dimorphisms.csv")
sex.dimorphism8 <- FindMarkers(sex.combined, ident.1 = "8_MALE", ident.2="8_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism8, file="Seurat_out/LIGERtest/cluster8dimorphisms.csv")
sex.dimorphism9 <- FindMarkers(sex.combined, ident.1 = "9_MALE", ident.2="9_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism9, file="Seurat_out/LIGERtest/cluster9dimorphisms.csv")
sex.dimorphism3 <- FindMarkers(sex.combined, ident.1 = "3_MALE", ident.2="3_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism3, file="Seurat_out/LIGERtest/cluster3dimorphisms.csv")
sex.dimorphism4 <- FindMarkers(sex.combined, ident.1 = "4_MALE", ident.2="4_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism4, file="Seurat_out/LIGERtest/cluster4dimorphisms.csv")
sex.dimorphism6 <- FindMarkers(sex.combined, ident.1 = "6_MALE", ident.2="6_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism6, file="Seurat_out/LIGERtest/cluster6dimorphisms.csv")
sex.dimorphism7 <- FindMarkers(sex.combined, ident.1 = "7_MALE", ident.2="7_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism7, file="Seurat_out/LIGERtest/cluster7dimorphisms.csv")
sex.dimorphism14 <- FindMarkers(sex.combined, ident.1 = "14_MALE", ident.2="14_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism14, file="Seurat_out/LIGERtest/cluster14dimorphisms.csv")
sex.dimorphism11 <- FindMarkers(sex.combined, ident.1 = "11_MALE", ident.2="11_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism14, file="Seurat_out/LIGERtest/cluster11dimorphisms.csv")
sex.dimorphism14 <- FindMarkers(sex.combined, ident.1 = "14_MALE", ident.2="14_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism14, file="Seurat_out/LIGERtest/cluster14dimorphisms.csv")
sex.dimorphism10 <- FindMarkers(sex.combined, ident.1 = "10_MALE", ident.2="10_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism10, file="Seurat_out/LIGERtest/cluster10dimorphisms.csv")
sex.dimorphism15 <- FindMarkers(sex.combined, ident.1 = "15_MALE", ident.2="15_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism15, file="Seurat_out/LIGERtest/cluster15dimorphisms.csv")
sex.dimorphism18 <- FindMarkers(sex.combined, ident.1 = "18_MALE", ident.2="18_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism18, file="Seurat_out/LIGERtest/cluster18dimorphisms.csv")
sex.dimorphism2 <- FindMarkers(sex.combined, ident.1 = "2_MALE", ident.2="2_FEMALE", verbose=FALSE)
write.csv(sex.dimorphism18, file="Seurat_out/LIGERtest/cluster2dimorphisms.csv")
pdf("Seurat_candidates_1.pdf")
FeaturePlot(sex.combined, features = c("Pappa", "Cyp19a1", "Ar"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_2.pdf")
FeaturePlot(sex.combined, features = c("Cckar", "Greb1", "Sytl4"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_3.pdf")
FeaturePlot(sex.combined, features = c("Esr1", "Brs3", "Ecel1"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_4.pdf")
FeaturePlot(sex.combined, features = c("Cartpt", "Pak3", "Glra3"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_5.pdf")
FeaturePlot(sex.combined, features = c("St18", "Herc1", "Moxd1"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_6.pdf")
FeaturePlot(sex.combined, features = c("Gpr88", "Ezr", "Cd24a"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_candidates_7.pdf")
FeaturePlot(sex.combined, features = c("Akap9", "Pcp4", "Vip"), split.by = "Sex" , max.cutoff=3, cols = c("grey", "red"))
dev.off()
pdf("Seurat_violin_1.pdf")
plots1 <- VlnPlot(sex.combined, features= c("Ar", "Cyp19a1", "Pappa"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots1, ncol=1)
dev.off()
pdf("Seurat_violin_2.pdf")
plots2 <- VlnPlot(sex.combined, features= c("St18", "Herc1", "Moxd1"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots2, ncol=1)
dev.off()
pdf("Seurat_violin_3.pdf")
plots3 <- VlnPlot(sex.combined, features= c("Esr1", "Brs3", "Glra3"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots3, ncol=1)
dev.off()
pdf("Seurat_violin_4.pdf")
plots4 <- VlnPlot(sex.combined, features= c("Cckar", "Greb1", "Sytl4"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots4, ncol=1)
dev.off()
pdf("Seurat_violin_5.pdf")
plots5 <- VlnPlot(sex.combined, features= c("Gpr88", "Ezr", "Cd24a"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots5, ncol=1)
dev.off()
pdf("Seurat_violin_6.pdf")
plots6 <- VlnPlot(sex.combined, features= c("Fam135a", "Akap9", "Socs2"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots6, ncol=1)
dev.off()
pdf("Seurat_violin_7.pdf")
plots7 <- VlnPlot(sex.combined, features= c("Pcp4", "Hexim2", "Slc48a1"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots7, ncol=1)
dev.off()
pdf("Seurat_violin_8.pdf")
plots8 <- VlnPlot(sex.combined, features= c("Rps6", "Rpl7", "Rpl36al"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots8, ncol=1)
dev.off()
pdf("Seurat_violin_9.pdf")
plots9 <- VlnPlot(sex.combined, features= c("Nnat", "Pgr", "Gpr165"), split.by="Sex", group.by ="celltype", pt.size=0, combine=FALSE)
CombinePlots(plots =plots9, ncol=1)
dev.off()
