#!/usr/bin/env Rscript

output <- "Seurat/VMH_MalevPrimedMerged_Exploratory/VMH_MalevPrimed_Exploratory"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

MaleVMH <- readRDS("Seurat/MaleVMH_Preprocessing/MaleVMH_Preprocessing.rds")
PrimedVMH <- readRDS("Seurat/VMHPrimed_Preprocessing/FemaleVMHPrimed_Preprocessing.rds")
MaleVMH$sex <- "Male"
PrimedVMH$sex <- "Female"
MaleVMH <- subset(MaleVMH, idents=c("2"), invert=TRUE)
PrimedVMH <- subset(PrimedVMH, idents=c("0"), invert=TRUE)
Shared.features <- SelectIntegrationFeatures(object.list=list(MaleVMH,PrimedVMH), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(MaleVMH,PrimedVMH), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, dims=1:30, verbose=TRUE)
Sex.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=TRUE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=1.5)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(Sex.integrated,reduction="umap", label=TRUE, group.by="sex")
dev.off()
Sex.integrated.markers <- FindAllMarkers(Sex.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Sex.integrated.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- Sex.integrated.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Sex.integrated, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
