output <- "Seurat/VMH_PrimedvMale_AparnaNorm/VMH_filter0testplots_newvarextravars"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(Matrix)
library(matrixStats)
library(qlcMatrix)
library(igraph)
library(RANN)

mySeurat <- readRDS("Seurat/VMH_PrimedvMale_AparnaNorm/VMH_MalevPrimed_aparnanorm_filter0test_newvarextravars.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(paste0(output, "_Gad1.pdf"))
VlnPlot(mySeurat, features=c("Gad1"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output, "_Gad2.pdf"))
VlnPlot(mySeurat, features=c("Gad2"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output, "_Slc17a6.pdf"))
VlnPlot(mySeurat, features=c("Slc17a6"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output, "_NRs1.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(0:6), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs2.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(7:12), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs3.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(13:18), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs4.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(19:25), split.by="sex")
dev.off()
pdf(paste0(output, "_markers1.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(0:6), split.by="sex")
dev.off()
pdf(paste0(output, "_markers2.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(7:12), split.by="sex")
dev.off()
pdf(paste0(output, "_markers3.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(13:18), split.by="sex")
dev.off()
pdf(paste0(output, "_markers4.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(19:25), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_1.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(0:6), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_2.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(7:12), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_3.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(13:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_4.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(19:25), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_1.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(0:6), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_2.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(7:12), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_3.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(13:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_4.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(19:25), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(0:6), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_2.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(7:12), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_3.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(13:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_4.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(19:25), split.by="sex")
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Cckar_featureplot.pdf"))
FeaturePlot(mySeurat, features = c("Cckar"), pt.size=0)
dev.off()
pdf(paste0(output, "Phf21b_featureplot.pdf"))
FeaturePlot(mySeurat, features = c("Phf21b"), pt.size=0)
dev.off()
pdf(paste0(output, "Cckar_featureplot_sexsplit.pdf"))
FeaturePlot(mySeurat, features = c("Cckar"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "Phf21b_featureplot_sexsplit.pdf"))
FeaturePlot(mySeurat, features = c("Phf21b"), pt.size=0, split.by="sex")
dev.off()


