#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
Esr1BNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_fullGFP_retry2/outs/filtered_feature_bc_matrix")
Esr1BNST <- CreateSeuratObject(counts = Esr1BNST.data, project ="MaleBNST", min.cells=3, min.features=200)
Esr1BNST <- subset(Esr1BNST, subset = nCount_RNA > 3000 & nCount_RNA < 28000)
Esr1BNST <- SCTransform(Esr1BNST, verbose=TRUE)
Esr1BNST <- RunPCA(Esr1BNST, verbose=TRUE)
Esr1BNST <- RunUMAP(Esr1BNST, dims=1:30, verbose=TRUE)
Esr1BNST <- FindNeighbors(Esr1BNST, dims=1:30, verbose=TRUE)
Esr1BNST <- FindClusters(Esr1BNST, verbose=TRUE, resolution=0.4)
pdf(file="Seurat/MaleEsr1_Sctransformexploratory/Seurat_Genesvdepth_stringent2.pdf")
plot1 <- FeatureScatter(Esr1BNST, feature1="nCount_RNA", feature2="Esr1")
plot2 <- FeatureScatter(Esr1BNST, feature1="nCount_RNA", feature2="Ar")
plot3 <- FeatureScatter(Esr1BNST, feature1="nCount_RNA", feature2="Esr2")
plot4 <- FeatureScatter(Esr1BNST, feature1="nCount_RNA", feature2="sfGFP-myc")
CombinePlots(plots=list(plot1,plot2,plot3,plot4))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Seurat_MaleEsr1BNST_SctransformUMAP_stringent_lowres2.pdf")
DimPlot(Esr1BNST, label=TRUE)
dev.off()
cluster.markers <- FindAllMarkers(Esr1BNST)
write.csv(cluster.markers, file="Seurat/MaleEsr1_Sctransformexploratory/MaleEsr1BNST_clusters_stringent_lowres2.csv")
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_violin_stringent2.pdf")
VlnPlot(Esr1BNST, features = c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_featureplot_stringent2.pdf")
FeaturePlot(Esr1BNST, features =c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_Ridgeplot_stringent2.pdf")
RidgePlot(Esr1BNST, features=c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_Dotplot_stringent2.pdf")
markers.to.plot <- c("Esr1","Cyp19a1","Pappa","St18","Pdzrn4","Greb1","Ar","Sytl4","Cckar","Tac1","Tac2","Cck")
DotPlot(Esr1BNST, genes.plot=makers.to.plot)
dev.off()
top10 <- cluster.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
pdf("Seurat/MaleEsr1_Sctransformexploratory/Clusterheatmap_stringent2.pdf")
DoHeatmap(Esr1BNST, features = top10$gene) + NoLegend()
dev.off()
