#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/MaleBNST_Preprocessing/MaleBNST_filtered_redo"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/MaleBNST_Preprocessing/MaleBNST_preprocessing_redo.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("0","23"), invert=TRUE)
filteredSeurat
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat <- FindClusters(filteredSeurat, verbose=TRUE, resolution=1.5)
filteredSeurat <- RunUMAP(filteredSeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat, reduction="umap", do.label=TRUE)
dev.off()
saveRDS(filteredSeurat, file=(paste0(output, ".rds")))
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(filteredSeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(filteredSeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(filteredSeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(filteredSeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(filteredSeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(filteredSeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(filteredSeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(filteredSeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(filteredSeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(filteredSeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(filteredSeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
filteredSeurat[["percent.mt"]] <- PercentageFeatureSet(filteredSeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(filteredSeurat, features = c("percent.mt"), pt.size=0)
dev.off()
DefaultAssay(filteredSeurat) <- "RNA"
filteredSeurat.markers <- FindAllMarkers(filteredSeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(filteredSeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- filteredSeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(filteredSeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(filteredSeurat, file=(paste0(output, ".rds")))
