#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
Esr1BNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_antisenseGFP_v3-1_local_long/outs/filtered_feature_bc_matrix")
LigerMale1a.data <- Read10X(data.dir = "BNST_LIGER_Male1a_patch/outs/filtered_feature_bc_matrix")
LigerMale2a.data <- Read10X(data.dir = "BNST_LIGER_Male2a_patch/outs/filtered_feature_bc_matrix")
LigerMale3a.data <- Read10X(data.dir = "BNST_LIGER_Male3a_patch/outs/filtered_feature_bc_matrix")
LigerMale4a.data <- Read10X(data.dir = "BNST_LIGER_Male4a_patch/outs/filtered_feature_bc_matrix")
Esr1BNST <- CreateSeuratObject(counts = Esr1BNST.data, project ="MaleBNST", min.cells=3, min.features=200)
LigerMale1 <- CreateSeuratObject(counts = LigerMale1a.data, project="LIGER", min.cells=3, min.features=200)
LigerMale2 <- CreateSeuratObject(counts = LigerMale2a.data, project="LIGER", min.cells=3, min.features=200)
LigerMale3 <- CreateSeuratObject(counts = LigerMale3a.data, project="LIGER", min.cells=3, min.features=200)
LigerMale4 <- CreateSeuratObject(counts = LigerMale4a.data, project="LIGER", min.cells=3, min.features=200)
Esr1BNST <- SCTransform(Esr1BNST, verbose=TRUE)
LigerMale1 <- SCTransform(LigerMale1, verbose=TRUE)
LigerMale2 <- SCTransform(LigerMale2, verbose=TRUE)
LigerMale3 <- SCTransform(LigerMale3, verbose=TRUE)
LigerMale4 <- SCTransform(LigerMale4, verbose=TRUE)
Esr1BNST$library <- "Shah"
LigerMale1$library <- "Liger"
LigerMale2$library <- "Liger"
LigerMale3$library <- "Liger"
LigerMale4$library <- "Liger"
BNST.features <- SelectIntegrationFeatures(object.list=list(LigerMale1,LigerMale2,LigerMale3,LigerMale4,Esr1BNST), nfeatures=3000)
BNST.list <- PrepSCTIntegration(object.list=list(LigerMale1,LigerMale2,LigerMale3,LigerMale4,Esr1BNST), anchor.features=BNST.features, verbose=TRUE)
BNST.anchors <- FindIntegrationAnchors(object.list=BNST.list, normalization.method="SCT", anchor.features=BNST.features, verbose=TRUE)
BNST.integrated <- IntegrateData(anchorset=BNST.anchors, normalization.method="SCT", verbose=FALSE)
BNST.integrated <- RunPCA(BNST.integrated, verbose=TRUE)
BNST.integrated <- RunUMAP(BNST.integrated, dims=1:30)
BNST.integrated <- FindNeighbors(BNST.integrated, dims=1:30)
BNST.integrated <- FindClusters(BNST.integrated, resolution=0.5)
pdf("Seurat/Seurat_BNST_FullLigerUmap_Sctransform.pdf")
DimPlot(BNST.integrated, reduction="umap", label=TRUE)
dev.off()
pdf("Seurat/Seurat_BNST_FullLigerUmap_Sctransform_split.pdf")
DimPlot(BNST.integrated, reduction="umap", split.by="library")
dev.off()
cluster.markers <- FindAllMarkers(BNST.integrated)
write.csv(cluster.markers, file="Seurat/MaleEsr1_Sctransformexploratory/MaleBNST_FullLiger_clusters_integrated.csv")
