
#!/usr/bin/env Rscript

sampleID <- "IntactPOA"
directory <- "IntactPOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/FullPOA_Diff/FullPOA_IntactvUnprimed_res0.5"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/FullPOA_Integrated/FullPOA_furtherfilteredunnormalized.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("21","24","28"), invert=TRUE)
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat1 <- FindClusters(filteredSeurat, verbose=TRUE, resolution=0.5)
filteredSeurat1 <- RunUMAP(filteredSeurat1, dims=1:30)
DefaultAssay(filteredSeurat) <- "RNA"
filteredSeurat <- NormalizeData(filteredSeurat)
filteredSeurat$celltype.state <- paste(Idents(filteredSeurat), filteredSeurat$state, sep="_")
filteredSeurat$celltype <- Idents(filteredSeurat)
Idents(filteredSeurat) <- "celltype.state"
sex.dimorphism0 <- FindMarkers(filteredSeurat, ident.1 = "0_Intact", ident.2="0_Unprimed", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism0, file=paste0(output, "_cluster0MalevUnprimeddimorphisms.csv"))
sex.dimorphism1 <- FindMarkers(filteredSeurat, ident.1 = "1_Intact", ident.2="1_Unprimed", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism1, file=paste0(output, "_cluster1MalevUnprimeddimorphisms.csv"))
sex.dimorphism2 <- FindMarkers(filteredSeurat, ident.1 = "2_Intact", ident.2="2_Unprimed", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism2, file=paste0(output, "_cluster2MalevUnprimeddimorphisms.csv"))
sex.dimorphism3 <- FindMarkers(filteredSeurat, ident.1 = "3_Intact", ident.2="3_Unprimed", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism3, file=paste0(output, "_cluster3MalevUnprimeddimorphisms.csv"))
sex.dimorphism4 <- FindMarkers(filteredSeurat, ident.1 = "4_Intact", ident.2="4_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism4, file=paste0(output, "_cluster4MalevUnprimeddimorphisms.csv"))
sex.dimorphism5 <- FindMarkers(filteredSeurat, ident.1 = "5_Intact", ident.2="5_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism5, file=paste0(output, "_cluster5MalevUnprimeddimorphisms.csv"))
sex.dimorphism6 <- FindMarkers(filteredSeurat, ident.1 = "6_Intact", ident.2="6_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism6, file=paste0(output, "_cluster6MalevUnprimeddimorphisms.csv"))
sex.dimorphism7 <- FindMarkers(filteredSeurat, ident.1 = "7_Intact", ident.2="7_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism7, file=paste0(output, "_cluster7MalevUnprimeddimorphisms.csv"))
sex.dimorphism8 <- FindMarkers(filteredSeurat, ident.1 = "8_Intact", ident.2="8_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism8, file=paste0(output, "_cluster8MalevUnprimeddimorphisms.csv"))
sex.dimorphism9 <- FindMarkers(filteredSeurat, ident.1 = "9_Intact", ident.2="9_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism9, file=paste0(output, "_cluster9MalevUnprimeddimorphisms.csv"))
sex.dimorphism10 <- FindMarkers(filteredSeurat, ident.1 = "10_Intact", ident.2="10_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism10, file=paste0(output, "_cluster10MalevUnprimeddimorphisms.csv"))
sex.dimorphism11 <- FindMarkers(filteredSeurat, ident.1 = "11_Intact", ident.2="11_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism11, file=paste0(output, "_cluster11MalevUnprimeddimorphisms.csv"))
sex.dimorphism12 <- FindMarkers(filteredSeurat, ident.1 = "12_Intact", ident.2="12_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism12, file=paste0(output, "_cluster12MalevUnprimeddimorphisms.csv"))
sex.dimorphism13 <- FindMarkers(filteredSeurat, ident.1 = "13_Intact", ident.2="13_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism13, file=paste0(output, "_cluster1MalevUnprimeddimorphisms.csv"))
sex.dimorphism14 <- FindMarkers(filteredSeurat, ident.1 = "14_Intact", ident.2="14_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism14, file=paste0(output, "_cluster14MalevUnprimeddimorphisms.csv"))
sex.dimorphism15 <- FindMarkers(filteredSeurat, ident.1 = "15_Intact", ident.2="15_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism15, file=paste0(output, "_cluster15MalevUnprimeddimorphisms.csv"))
sex.dimorphism16 <- FindMarkers(filteredSeurat, ident.1 = "16_Intact", ident.2="16_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism16, file=paste0(output, "_cluster16MalevUnprimeddimorphisms.csv"))
sex.dimorphism17 <- FindMarkers(filteredSeurat, ident.1 = "17_Intact", ident.2="17_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism17, file=paste0(output, "_cluster17MalevUnprimeddimorphisms.csv"))
sex.dimorphism18 <- FindMarkers(filteredSeurat, ident.1 = "18_Intact", ident.2="18_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism18, file=paste0(output, "_cluster18MalevUnprimeddimorphisms.csv"))
sex.dimorphism19 <- FindMarkers(filteredSeurat, ident.1 = "19_Intact", ident.2="19_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism19, file=paste0(output, "_cluster19MalevUnprimeddimorphisms.csv"))
sex.dimorphism20 <- FindMarkers(filteredSeurat, ident.1 = "20_Intact", ident.2="20_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism20, file=paste0(output, "_cluster20MalevUnprimeddimorphisms.csv"))
sex.dimorphism21 <- FindMarkers(filteredSeurat, ident.1 = "21_Intact", ident.2="21_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism21, file=paste0(output, "_cluster21MalevUnprimeddimorphisms.csv"))
sex.dimorphism22 <- FindMarkers(filteredSeurat, ident.1 = "22_Intact", ident.2="22_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism22, file=paste0(output, "_cluster22MalevUnprimeddimorphisms.csv"))
sex.dimorphism23 <- FindMarkers(filteredSeurat, ident.1 = "23_Intact", ident.2="23_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism23, file=paste0(output, "_cluster23MalevUnprimeddimorphisms.csv"))
sex.dimorphism24 <- FindMarkers(filteredSeurat, ident.1 = "24_Intact", ident.2="24_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism24, file=paste0(output, "_cluster24MalevUnprimeddimorphisms.csv"))
sex.dimorphism25 <- FindMarkers(filteredSeurat, ident.1 = "25_Intact", ident.2="25_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism25, file=paste0(output, "_cluster25MalevUnprimeddimorphisms.csv"))
sex.dimorphism26 <- FindMarkers(filteredSeurat, ident.1 = "26_Intact", ident.2="26_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism26, file=paste0(output, "_cluster26MalevUnprimeddimorphisms.csv"))
sex.dimorphism27 <- FindMarkers(filteredSeurat, ident.1 = "27_Intact", ident.2="27_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism27, file=paste0(output, "_cluster26MalevUnprimeddimorphisms.csv"))

