#!/usr/bin/env Rscript
output <- "Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate_filtered1_ExcludeDE_Niraoplots_0.6res_10pcs_superfileteredfiltered"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate.rds")
mySeurat <- subset(mySeurat, idents=c("0","39","36","26","25","12","11","15"), invert=TRUE)
genelist <- read.table("Genelists/Sexchrom.txt", header=FALSE)
mySeurat <- RunPCA(mySeurat)
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:10)
mySeurat <- FindClusters(mySeurat, resolution=0.6)
mySeurat <- RunUMAP(mySeurat, dims=1:10)
mySeurat <- RunTSNE(mySeurat, dims=1:10)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_TSNE.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_umap.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="umap", cols=c("light blue","dark red"), label=FALSE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_tsne.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="tsne", cols=c("light blue","dark red"),  label=FALSE)
dev.off()
pdf(file=paste0(output, "Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1","Pgr","Cckar"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output, "Slc17a6Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Slc17a6"), pt.size=0)
dev.off()
pdf(file=paste0(output, "Slc17a7Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Slc17a7"), pt.size=0)
dev.off()
pdf(file=paste0(output, "Slc32a1Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat,reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_statussplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="status")
dev.off()
pdf(paste0(output,"_UMAP_statuslabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="status")
dev.off()
pdf(paste0(output,"_TSNE_sexplit.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_TSNE_sexlabel.pdf"))
DimPlot(mySeurat,reduction="tsne", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_TSNE_statussplit.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE, split.by="status")
dev.off()
pdf(paste0(output,"_TSNE_statuslabel.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE, group.by="status")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))

