#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(reticulate)
Esr1pos.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_antisenseGFP_v3-1_local_long/outs/filtered_feature_bc_matrix")
LigerMale3a.data <- Read10X(data.dir= "BNST_LIGER_Male3a/outs/filtered_feature_bc_matrix")
L <- CreateSeuratObject(counts = MaleBNST.data, project ="MaleBNST", min.cells=3, min.features=200)
LIGERmale <- CreateSeuratObject(counts = LigerMale3a.data, project="LIGER", min.cells=3, min.features=200)
Male <- subset(Male, subset = nFeature_RNA > 500)
Male <- NormalizeData(Male, verbose=TRUE)
Male <- FindVariableFeatures(Male, selection.method= "vst", nfeatures=2000)
Female <- subset(Female, subset = nFeature_RNA > 500) 
Female <- NormalizeData(Female, verbose=TRUE)
Female <- FindVariableFeatures(Female, selection.method= "vst", nfeatures=2000)
sex.anchors <- FindIntegrationAnchors(object.list=list(Male,Female), dims=1:20)
sex.combined <- IntegrateData(anchorset = sex.anchors, dims=1:20)
DefaultAssay(sex.combined) <- "integrated"
sex.combined <- ScaleData(sex.combined, verbose=TRUE)
sex.combined <- RunPCA(sex.combined, npcs=30, verbose=TRUE)
sex.combined <- RunUMAP(sex.combined, reduction="pca", dim=1:20)
sex.combined <- FindNeighbors(sex.combined, reduction ="pca", dims=1:20)
sex.combined <- FindClusters(sex.combined, resolution=0.5)
pdf(file="Seurat_Sex_Combined_Test.pdf")
p1 <- DimPlot(sex.combined, reduction="umap", group.by ="Sex")
p2 <- DimPlot(sex.combined, reduction="umap", label=TRUE)
plot_grid(p1, p2)
dev.off()
pdf(file="Seurat_Sidebyside.pdf")
DimPlot(sex.combined, reduction="umap", split.by="Sex")
dev.off()

