#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_filtered_SCmerge_candidategenes_SCT"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/POA_MalevUnprimed_Exploratory.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("0", "21","22"), invert=TRUE)
filteredSeurat <- SCTransform(filteredSeurat)
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat <- FindClusters(filteredSeurat, verbose=TRUE, resolution=0.5)
filteredSeurat <- RunUMAP(filteredSeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
filteredSeurat2 <- RunTSNE(filteredSeurat, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(filteredSeurat2, reduction="tsne", do.label=TRUE)
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Esr1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Smoc2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Smoc2"), split.by="sex")
dev.off()
pdf(paste0(output,"_Acvr1cfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Acvr1c"), split.by="sex")
dev.off()
pdf(paste0(output,"_Pappafeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Pappa"), split.by="sex")
dev.off()
pdf(paste0(output,"_Slitrk6featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Slitrk6"), split.by="sex")
dev.off()
pdf(paste0(output,"_Pdzrn4featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Pdzrn4"), split.by="sex")
dev.off()
pdf(paste0(output,"_Col25a1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Col25a1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Kirrelfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Kirrel"), split.by="sex")
dev.off()
pdf(paste0(output,"_Npy2rfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Npy2r"), split.by="sex")
dev.off()
pdf(paste0(output,"_Zeb2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Zeb2"), split.by="sex")
dev.off()
pdf(paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Cckar"), split.by="sex")
dev.off()
pdf(paste0(output,"_Galfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Gal"), split.by="sex")
dev.off()
pdf(paste0(output,"_Ecel1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Ecel1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Garem1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Garem1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Crim1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Crim1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Shisa6featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Shisa6"), split.by="sex")
dev.off()
pdf(paste0(output,"_Tnxbfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Tnxb"), split.by="sex")
dev.off()

