#!/usr/bin/env Rscript
output <- "Seurat/MeA_SCTPostMerge/MeA_SCTpostmerge"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(Matrix)
library(matrixStats)
library(qlcMatrix)
library(igraph)
library(RANN)
MaleMeA.data <- Read10X(data.dir= "FemaleBNSTPrimed_Putative_retry/outs/filtered_feature_bc_matrix")
MaleMeA <- CreateSeuratObject(counts = MaleMeA.data, project = "MaleMeA", min.cells=3, min.features=200)
PrimedMeA.data <- Read10X(data.dir= "FemaleMeAPrimed/outs/filtered_feature_bc_matrix")
PrimedMeA <- CreateSeuratObject(counts = PrimedMeA.data, project = "PrimedMeA", min.cells=3, min.features=200)
MaleMeA$sex <- "Male"
PrimedMeA$sex <- "Female"
mySeurat <- merge(MaleMeA, y=c(PrimedMeA), add.cell.ids=c("MaleMeA","PrimedMeA"), project="Merged")
mySeurat <- subset(mySeurat, subset=nCount_RNA < 60000)
mySeurat <- SCTransform(mySeurat, verbose=TRUE, vars.to.regress="orig.ident")
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat))
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1.5)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat,reduction="umap", label=TRUE, group.by="sex")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))


