#!/usr/bin/env Rscript
output <- "Seurat/PrimedVMH_Bus/PrimedVMH_Exploratory_filtered3"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/PrimedVMH_Bus/PrimedVMH_Exploratory_filtered2.rds")
mySeurat <- subset(mySeurat, idents=c("13"), invert=TRUE)
mySeurat <- RunPCA(mySeurat)
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=c(1:8,10))
mySeurat <- FindClusters(mySeurat, resolution=0.5)
mySeurat <- RunUMAP(mySeurat, dims=c(1:8,10))
mySeurat <- RunTSNE(mySeurat, dims=c(1:8,10))
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_TSNE.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE)
dev.off()
pdf(file=paste0(output, "Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1","Pgr","Cckar"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_umap.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="umap", cols=c("light blue","red"), label=FALSE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_tsne.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="tsne", cols=c("light blue","red"),  label=FALSE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))

saveRDS(mySeurat, file=(paste0(output, ".rds")))

