#!/usr/bin/env Rscript

output <- "Seurat/POA_PrimedvUnprimed_doubletsremoved/POA_PrimedvUnprimed_Exploratory_unfiltered"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Primed <- readRDS(file = "Seurat/PrimedPOA_Preprocessing/PrimedPOA_doubletsremoved_.rds")
Unprimed <- readRDS(file = "Seurat/UnprimedPOA_Preprocessing/UnprimedPOA_doubletsremoved_.rds")
Primed$state <- "Primed"
Unprimed$state <- "Unprimed"
Shared.features <- SelectIntegrationFeatures(object.list=list(Primed,Unprimed), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(Primed,Unprimed), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
Sex.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=FALSE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=1.2)
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(Sex.integrated, feature1="nCount_RNA", feature2="nFeature_RNA")
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(Sex.integrated, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(Sex.integrated, reduction="pca")
dev.off()
pdf(paste0(output,"_UMAP_1.5.pdf"))
DimPlot(Sex.integrated, reduction="umap", do.label=TRUE)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
