#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimedMerged_Exploratory/Doubletsremoved_unfiltered_plots"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(Cairo)
mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/POA_MalevUnprimed_Exploratory_doubletsremovedexploratory.rds")
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
png(paste0(output,"_Gad1featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gad1"))
dev.off()
png(paste0(output,"_Gad2featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Fosfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Fos"))
dev.off()
pdf(paste0(output,"_Egr1featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Egr1"))
dev.off()
pdf(paste0(output,"_Fosl2featureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Fosl2"))
dev.off()
pdf(paste0(output,"_Junfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Jun"))
dev.off()
pdf(paste0(output,"_Fosbfeatureplot.pdf"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Fosb"))
dev.off()
png(paste0(output,"_Slc32a1featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc32a1"))
dev.off()
png(paste0(output,"_Slc17a6featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc17a6"))
dev.off()
png(paste0(output,"_Slc17a8featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc17a8"))
dev.off()
png(paste0(output,"_Chatfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Chat"))
dev.off()
png(paste0(output,"_Thfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Th"))
dev.off()
png(paste0(output,"_Olig1featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Olig1"))
dev.off()
png(paste0(output,"_Mobpfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Mobp"))
dev.off()
png(paste0(output,"_Gfapfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gfap"))
dev.off()
png(paste0(output,"_Esr1featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Esr1"))
dev.off()
png(paste0(output,"_Prr5lfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Prr5l"))
dev.off()
png(paste0(output,"_Slc18a2featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc18a2"))
dev.off()
png(paste0(output,"_Smoc2featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Smoc2"))
dev.off()
png(paste0(output,"_Opn5featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Opn5"))
dev.off()
png(paste0(output,"_Elf4featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Elf4"))
dev.off()
png(paste0(output,"_St18featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("St18"))
dev.off()
png(paste0(output,"_Slc1a3featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Slc1a3"))
dev.off()
png(paste0(output,"_Inpp5dfeatureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Inpp5d"))
dev.off()
png(paste0(output,"_Gnrh1featureplot.png"))
FeaturePlot(mySeurat, blend.threshold=0.1, min.cutoff="q10",max.cutoff="q90", cols=c("lightgrey","red"), features=c("Gnrh1"))
dev.off()
png(paste0(output, "_Vln_Gad1.png"))
VlnPlot(mySeurat, features =c("Gad1"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Gad2.png"))
VlnPlot(mySeurat, features =c("Gad2"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Slc32a1.png"))
VlnPlot(mySeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Mobp.png"))
VlnPlot(mySeurat, features = c("Mobp"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Gfap.png"))
VlnPlot(mySeurat, features = c("Gfap"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Olig1markers.png"))
VlnPlot(mySeurat, features = c("Olig1"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Esr1.png"))
VlnPlot(mySeurat, features = c("Esr1"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Ar.png"))
VlnPlot(mySeurat, features = c("Ar"), pt.size=0)
dev.off()
png(paste0(output, "_Vln_Pgr.png"))
VlnPlot(mySeurat, features = c("Pgr"), pt.size=0)
dev.off()
png(paste0(output, "Vln_UMIcluster.png"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
png(paste0(output, "Vln_GeneCountcluster.png"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
png(paste0(output, "Vln_mitocluster.png"))
VlnPlot(mySeurat, features = c("percent.mt"), pt.size=0)
saveRDS(mySeurat, file=(paste0(output, ".rds")))
