output <- "Seurat/MeA_IndependentAnalysis/MeA_IndependentFiltered2_20pcs_0.6res_plots_"

library(BUSpaRse)
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Intact <- readRDS("Seurat/MeA_IndependentAnalysis/MeA_IndependentFiltered2_20pcs_0.6res_Intact.rds")
DefaultAssay <- "RNA"
Intact <- NormalizeData(Intact)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Esr1", "Slc17a6","Gad1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Nxph2", "Crym","G630016G05Rik","Fam20a"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers2.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Sim1", "Meis2","Gm27199","Prox1"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers3.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Sst", "Cd36","Chd7","Gypa"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers4.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Pappa", "St18","Gpr149","Drd3","Npffr2"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Vln_Markers5.pdf"), width=14, height=14)
VlnPlot(Intact, features=c("Igf1", "Col5a1","Eya4","Pappa2","Frmpd1"), pt.size=0, ncol=1)
dev.off()
