#!/usr/bin/env Rscript

output <- "Seurat/Unprimed_POAvBNST/Unprimed_POAvBNST"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
BNST <- readRDS(file = "Seurat/UnprimedBNST_Preprocessing/UnprimedBNST_doubletsremoved_.rds")
POA <- readRDS(file = "Seurat/UnprimedPOA_Preprocessing/UnprimedPOA_doubletsremoved_.rds")
BNST$region <- "BNST"
POA$region <- "POA"
Shared.features <- SelectIntegrationFeatures(object.list=list(BNST,POA), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(BNST,POA), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
Sex.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=FALSE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=1.2)
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(Sex.integrated, feature1="nCount_RNA", feature2="nFeature_RNA")
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(Sex.integrated, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(Sex.integrated, reduction="pca")
dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_regionsplit.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, split.by="region")
dev.off()
pdf(paste0(output,"_UMAP_regionlabel.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, group.by="region")
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
