#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimed_Doubletsremoved/MalevUnprimed_Fineclusters_Doubletsremoved_filtered5"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_doubletsremoved_filtered5.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
Sharedmarkers0 <- FindConservedMarkers(mySeurat, ident.1=0, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers0, file=paste0(output,"cluster0markers.csv"))
Sharedmarkers1 <- FindConservedMarkers(mySeurat, ident.1=1, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers1, file=paste0(output,"cluster1markers.csv"))
Sharedmarkers2 <- FindConservedMarkers(mySeurat, ident.1=2, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers2, file=paste0(output,"cluster2markers.csv"))
Sharedmarkers3 <- FindConservedMarkers(mySeurat, ident.1=3, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers3, file=paste0(output,"cluster3markers.csv"))
Sharedmarkers4 <- FindConservedMarkers(mySeurat, ident.1=4, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers4, file=paste0(output,"cluster4markers.csv"))
Sharedmarkers5 <- FindConservedMarkers(mySeurat, ident.1=5, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers5, file=paste0(output,"cluster5markers.csv"))
Sharedmarkers6 <- FindConservedMarkers(mySeurat, ident.1=6, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers6, file=paste0(output,"cluster6markers.csv"))
Sharedmarkers7 <- FindConservedMarkers(mySeurat, ident.1=7, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers7, file=paste0(output,"cluster7markers.csv"))
Sharedmarkers8 <- FindConservedMarkers(mySeurat, ident.1=8, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers8, file=paste0(output,"cluster8markers.csv"))
Sharedmarkers9 <- FindConservedMarkers(mySeurat, ident.1=9, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers9, file=paste0(output,"cluster9markers.csv"))
Sharedmarkers10 <- FindConservedMarkers(mySeurat, ident.1=10, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers10, file=paste0(output,"cluster10markers.csv"))
Sharedmarkers11 <- FindConservedMarkers(mySeurat, ident.1=11, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers11, file=paste0(output,"cluster11markers.csv"))
Sharedmarkers12 <- FindConservedMarkers(mySeurat, ident.1=12, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers12, file=paste0(output,"cluster12markers.csv"))
Sharedmarkers13 <- FindConservedMarkers(mySeurat, ident.1=13, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers13, file=paste0(output,"cluster13markers.csv"))
Sharedmarkers14 <- FindConservedMarkers(mySeurat, ident.1=14, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers14, file=paste0(output,"cluster14markers.csv"))
Sharedmarkers15 <- FindConservedMarkers(mySeurat, ident.1=15, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers15, file=paste0(output,"cluster15markers.csv"))
Sharedmarkers16 <- FindConservedMarkers(mySeurat, ident.1=16, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers16, file=paste0(output,"cluster16markers.csv"))
Sharedmarkers17 <- FindConservedMarkers(mySeurat, ident.1=17, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers17, file=paste0(output,"cluster17markers.csv"))
Sharedmarkers18 <- FindConservedMarkers(mySeurat, ident.1=18, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers18, file=paste0(output,"cluster18markers.csv"))
Sharedmarkers19 <- FindConservedMarkers(mySeurat, ident.1=19, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers19, file=paste0(output,"cluster19markers.csv"))
Sharedmarkers20 <- FindConservedMarkers(mySeurat, ident.1=20, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers20, file=paste0(output,"cluster20markers.csv"))
Sharedmarkers21 <- FindConservedMarkers(mySeurat, ident.1=21, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers21, file=paste0(output,"cluster21markers.csv"))
Sharedmarkers22 <- FindConservedMarkers(mySeurat, ident.1=22, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers22, file=paste0(output,"cluster22markers.csv"))
Sharedmarkers23 <- FindConservedMarkers(mySeurat, ident.1=23, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers23, file=paste0(output,"cluster23markers.csv"))
Sharedmarkers24 <- FindConservedMarkers(mySeurat, ident.1=24, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers24, file=paste0(output,"cluster24markers.csv"))
Sharedmarkers25 <- FindConservedMarkers(mySeurat, ident.1=25, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers25, file=paste0(output,"cluster25markers.csv"))
Sharedmarkers26 <- FindConservedMarkers(mySeurat, ident.1=26, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers26, file=paste0(output,"cluster26markers.csv"))
Sharedmarkers27 <- FindConservedMarkers(mySeurat, ident.1=27, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers27, file=paste0(output,"cluster27markers.csv"))
Sharedmarkers28 <- FindConservedMarkers(mySeurat, ident.1=28, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers28, file=paste0(output,"cluster28markers.csv"))
Sharedmarkers29 <- FindConservedMarkers(mySeurat, ident.1=29, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers29, file=paste0(output,"cluster29markers.csv"))
Sharedmarkers30 <- FindConservedMarkers(mySeurat, ident.1=30, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers30, file=paste0(output,"cluster30markers.csv"))
Sharedmarkers31 <- FindConservedMarkers(mySeurat, ident.1=31, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers31, file=paste0(output,"cluster31markers.csv"))
Sharedmarkers32 <- FindConservedMarkers(mySeurat, ident.1=32, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers32, file=paste0(output,"cluster32markers.csv"))
Sharedmarkers33 <- FindConservedMarkers(mySeurat, ident.1=33, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers33, file=paste0(output,"cluster33markers.csv"))
Sharedmarkers34 <- FindConservedMarkers(mySeurat, ident.1=34, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers34, file=paste0(output,"cluster34markers.csv"))
Sharedmarkers35 <- FindConservedMarkers(mySeurat, ident.1=35, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers35, file=paste0(output,"cluster35markers.csv"))
Sharedmarkers36 <- FindConservedMarkers(mySeurat, ident.1=36, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers36, file=paste0(output,"cluster36markers.csv"))
Sharedmarkers37 <- FindConservedMarkers(mySeurat, ident.1=37, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers37, file=paste0(output,"cluster37markers.csv"))
Sharedmarkers38 <- FindConservedMarkers(mySeurat, ident.1=38, grouping.var="sex", verbose=FALSE)
write.csv(Sharedmarkers38, file=paste0(output,"cluster38markers.csv"))
