#!/usr/bin/env Rscript

output <- "Seurat/MalevUnprimed_ScaledIntegrated/POA_MalevUnprimed_normalized"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
MalePOA <- readRDS("Seurat/MalePOA_Preprocessing/MalePOA_filtered_scaled.rds")
UnprimedPOA <- readRDS("Seurat/UnprimedPOA_Preprocessing/UnprimedPOA_filtered_scaled.rds")
MalePOA$sex <- "Male"
UnprimedPOA$sex <- "Female"
sex.anchors <- FindIntegrationAnchors(object.list=list(MalePOA,UnprimedPOA), dims=1:30)
to_integrate <- Reduce(intersect, lapply(sex.anchors@object.list, rownames))
Sex.integrated <- IntegrateData(anchorset = sex.anchors, dims=1:30, features.to.integrate=to_integrate)
DefaultAssay(Sex.integrated) <- "integrated"
Sex.integrated <- ScaleData(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, reduction="pca", dim=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, reduction ="pca", dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=0.5)
pdf(paste0(output, "_basic_counts.pdf"))
VlnPlot(Sex.integrated, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(Sex.integrated, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
pdf(paste0(output, "_Esr1counts.pdf"))
VlnPlot(Sex.integrated, features = c("Esr1"))
dev.off()
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(Sex.integrated, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(Sex.integrated, reduction="pca")
dev.off()
pdf(paste0(output,"_PC1-3.pdf"))
DimHeatmap(Sex.integrated, dims=1:3, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC4-6.pdf"))
DimHeatmap(Sex.integrated, dims=4:6, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC7-9.pdf"))
DimHeatmap(Sex.integrated, dims=7:9, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC10-12.pdf"))
DimHeatmap(Sex.integrated, dims=10:12, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC13-15.pdf"))
DimHeatmap(Sex.integrated, dims=13:15, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC16-18.pdf"))
DimHeatmap(Sex.integrated, dims=16:18, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC19-21.pdf"))
DimHeatmap(Sex.integrated, dims=19:21, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC25-27.pdf"))
DimHeatmap(Sex.integrated, dims=25:27, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC28-30.pdf"))
DimHeatmap(Sex.integrated, dims=28:30, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC31-33.pdf"))
DimHeatmap(Sex.integrated, dims=31:33, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC34-36.pdf"))
DimHeatmap(Sex.integrated, dims=34:36, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC37-39.pdf"))
DimHeatmap(Sex.integrated, dims=37:39, balanced=TRUE, cells=500)
dev.off()
#Sex.integrated <- JackStraw(Sex.integrated, dims=100, num.replicate=200)
#Sex.integrated <- ScoreJackStraw(Sex.integrated, dims=1:100)
#pdf(paste0(output,"_JackStrawplot_.pdf"))
#JackStrawPlot(Sex.integrated, dims=1:100)
#dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(Sex.integrated, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(Sex.integrated, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(Sex.integrated, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(Sex.integrated, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(Sex.integrated, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(Sex.integrated, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(Sex.integrated, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(Sex.integrated, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(Sex.integrated, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
Sex.integrated.markers <- FindAllMarkers(Sex.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Sex.integrated.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- Sex.integrated.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Sex.integrated, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
