#!/usr/bin/env Rscript
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
Esr1BNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_fullGFP_retry2/outs/filtered_feature_bc_matrix")
Esr1BNST <- CreateSeuratObject(counts = Esr1BNST.data, project ="MaleBNST", min.cells=3, min.features=200)
Esr1BNST <- subset(Esr1BNST, subset = nCount_RNA > 1000 & nCount_RNA < 28000)
Esr1BNST <- SCTransform(Esr1BNST, verbose=TRUE)
Esr1BNST[["percent.mt"]] <- PercentageFeatureSet(Esr1BNST, pattern = "^mt-")
pdf("Seurat/MaleEsr1_Sctransformexploratory/Seurat_MalBNST_sctransform_mt.pdf")
FeatureScatter(Esr1BNST, feature1= "nCount_RNA", feature2="percent.mt")
dev.off()
Esr1BNST <- RunPCA(Esr1BNST, verbose=TRUE)
Esr1BNST <- RunUMAP(Esr1BNST, dims=1:30, verbose=TRUE)
Esr1BNST <- FindNeighbors(Esr1BNST, dims=1:30, verbose=TRUE)
Esr1BNST <- FindClusters(Esr1BNST, verbose=TRUE)
pdf("Seurat/MaleEsr1_Sctransformexploratory/Seurat_MaleEsr1BNST_SctransformUMAP.pdf")
DimPlot(Esr1BNST, label=TRUE)
dev.off()
cluster.markers <- FindAllMarkers(Esr1BNST)
write.csv(cluster.markers, file="Seurat/MaleEsr1_Sctransformexploratory/MaleEsr1BNST_clusters.csv")
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_violin.pdf")
VlnPlot(Esr1BNST, features = c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_featureplot.pdf")
FeaturePlot(Esr1BNST, features =c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_Ridgeplot.pdf")
RidgePlot(Esr1BNST, features=c("Esr1","Cyp19a1","Pappa"))
dev.off()
pdf("Seurat/MaleEsr1_Sctransformexploratory/Esr1_Cyp19a1_Pappa_Dotplot.pdf")
markers.to.plot <- c("Esr1","Cyp19a1","Pappa","St18","Pdzrn4","Greb1","Ar","Sytl4","Cckar","Tac1","Tac2","Cck")
DotPlot(Esr1BNST, genes.plot=makers.to.plot)
dev.off()
top10 <- cluster.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
pdf("Seurat/MaleEsr1_Sctransformexploratory/Clusterheatmap.pdf")
DoHeatmap(Esr1BNST, features = top10$gene) + NoLegend()
dev.off()
