#!/usr/bin/env Rscript

sampleID <- "UnprimedPOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/UnprimedPOA_Exploratory/UnprimedPOA"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Sampledata.data <- Read10X(data.dir = "FemalePOAUnprimed/outs/filtered_feature_bc_matrix")
mySeurat <- CreateSeuratObject(counts = Sampledata.data, project = sampleID, min.cells=3, min.features=200)
sampleID
pdf(paste0(output, "_basic_counts.pdf"))
VlnPlot(mySeurat, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(mySeurat, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
pdf(paste0(output, "_Esr1counts.pdf"))
VlnPlot(mySeurat, features = c("Esr1"))
dev.off()
mySeurat <- NormalizeData(mySeurat)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeature=2000)
top50 <- head (VariableFeatures(mySeurat), 50)
pdf(paste0(output, "_Variablefeatures.pdf"))
plot1 <- VariableFeaturePlot(mySeurat)
LabelPoints(plot=plot1, points=top50, repel=TRUE)
dev.off()
VariableFeatures <- (VariableFeatures(mySeurat))
write.csv(paste0(output, "_variablefeactures.csv"))
mySeurat <- ScaleData(mySeurat)
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat))
print(mySeurat[["pca"]], dims=1:20, nfeatures=10)
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(mySeurat, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(mySeurat, reduction="pca")
dev.off()
pdf(paste0(output,"_PC1.pdf"))
DimHeatmap(mySeurat, dims=1, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC1-3.pdf"))
DimHeatmap(mySeurat, dims=1:3, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC4-6.pdf"))
DimHeatmap(mySeurat, dims=4:6, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC7-9.pdf"))
DimHeatmap(mySeurat, dims=7:9, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC10-12.pdf"))
DimHeatmap(mySeurat, dims=10:12, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC13-15.pdf"))
DimHeatmap(mySeurat, dims=13:15, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC16-18.pdf"))
DimHeatmap(mySeurat, dims=16:18, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC19-21.pdf"))
DimHeatmap(mySeurat, dims=19:21, balanced=TRUE)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(mySeurat, dims=22:24, balanced=TRUE)
dev.off()
mySeurat <- JackStraw(mySeurat, num.replicate=200)
mySeurat <- ScoreJackStraw(mySeurat, dims=1:20)
pdf(paste0(output,"_JackStrawplot_.pdf"))
JackStrawPlot(mySeurat, dims=1:20)
dev.off()
pdf(paste0(output,"_elbowplot.pdf"))
ElbowPlot(mySeurat, ndims=40)
dev.off()
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=0.4)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat <- RunTSNE(mySeurat, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(mySeurat, reduction="tsne", do.label=TRUE)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top20 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=20, wt=avg_logFC)
DoHeatmap(mySeurat, features=top20$gene) + NoLegend()
dev.off()

