#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/Anderson/SingleHoused1_mergetest"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Rep1.data <- Read10X(data.dir = "2019_0330")
Rep1 <- CreateSeuratObject(counts = Rep1.data, project = "Rep1", min.cells=3, min.features=200)
Rep1
Rep2.data <- Read10X(data.dir= "2018_0812_1")
Rep2 <- CreateSeuratObject(counts = Rep2.data, project = "Rep2", min.cells=3, min.features=200)
Rep2
mySeurat <- merge(Rep1, y=Rep2, add.cell.ids=c("Rep1","Rep2"), project="SingleHouseMerge") 
mySeurat
head(mySeurat[[]])
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern = "^mt-")
mySeurat <- subset(mySeurat, subset = nFeature_RNA >600 & nCount_RNA < 30000 & percent.mt < 15)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeatures=2000)
mySeurat <- ScaleData(mySeurat, vars.to.regress="percent.mt")
mySeurat <- RunPCA(mySeurat, features=VariableFeatures(object=mySeurat))
pdf(paste0(output,"_PCAplot.pdf"))
DimPlot(mySeurat, reduction="pca", group.by="orig.ident")
dev.off()
pdf(paste0(output,"_PCAplot_dims23.pdf"))
DimPlot(mySeurat, reduction="pca", dim.1=2,dim.2=3,  group.by="orig.ident")
dev.off()
pdf(paste0(output,"_PCAplot_dims45.pdf"))
DimPlot(mySeurat, reduction="pca",dim.1=4,dim.2=5, group.by="orig.ident")
dev.off()
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_origsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="orig.ident")
dev.off()
pdf(paste0(output,"_UMAP_origlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="orig.ident")
dev.off()
mySeurat <- RunTSNE(mySeurat, features=VariableFeatures(object=mySeurat))
pdf(paste0(output,"_tsne.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE)
dev.off()
pdf(paste0(output,"_tsne_origsplit.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE, split.by="orig.ident")
dev.off()
pdf(paste0(output,"_tsne_origlabel.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE, group.by="orig.ident")
dev.off()
Rep1 <- SCTransform(Rep1, verbose=TRUE)
Rep2 <- SCTransform(Rep2, verbose=TRUE)
Shared.features <- SelectIntegrationFeatures(object.list=list(Rep1,Rep2), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(Rep1,Rep2), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
mySeurat <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=FALSE)
warnings()
mySeurat <- RunPCA(mySeurat, verbose=TRUE)
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat2 <- RunTSNE(mySeurat, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(mySeurat2, reduction="tsne", do.label=TRUE)
dev.off()
DefaultAssay(mySeurat) <- "RNA"
NormalizeData(mySeurat)
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Th"))
dev.off()
pdf(paste0(output,"_Avpfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Avp"))
dev.off()
pdf(paste0(output,"_Hcrtfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Hcrt"))
dev.off()
pdf(paste0(output,"_Gnrh1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gnrh1"))
dev.off()
pdf(paste0(output,"_Trhfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Trh"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc18a2"))
dev.off()
pdf(paste0(output,"_Nr5a1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Nr5a1"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(mySeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(mySeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(mySeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(mySeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Avp.pdf"))
VlnPlot(mySeurat, features = c("Avp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Qfrp.pdf"))
VlnPlot(mySeurat, features = c("Qrfp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Trh.pdf"))
VlnPlot(mySeurat, features = c("Trh"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Nr5a1.pdf"))
VlnPlot(mySeurat, features = c("Nr5a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Hcrt.pdf"))
VlnPlot(mySeurat, features = c("Hcrt"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gnrh1.pdf"))
VlnPlot(mySeurat, features = c("Gnrh1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(mySeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(mySeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(mySeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(mySeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(mySeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(mySeurat, features = c("percent.mt"), pt.size=0)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
