#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimed_Doubletsremoved/MalevUnprimed_Clustereval"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_doubletsremoved_filtered3.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(paste0(output, "Moxd1_.pdf"))
VlnPlot(mySeurat, features=c("Moxd1"), pt.size=0)
dev.off()
pdf(paste0(output, "Mob3b_.pdf"))
VlnPlot(mySeurat, features=c("Mob3b"), pt.size=0)
dev.off()
pdf(paste0(output, "Tmem215_.pdf"))
VlnPlot(mySeurat, features=c("Tmem215"), pt.size=0)
dev.off()
pdf(paste0(output, "Smoc2_.pdf"))
VlnPlot(mySeurat, features=c("Smoc2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Sytl4.pdf"))
VlnPlot(mySeurat, features=c("Sytl4"), pt.size=0)
dev.off()
pdf(paste0(output, "_Hpse2.pdf"))
VlnPlot(mySeurat, features=c("Hpse2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Tnxb.pdf"))
VlnPlot(mySeurat, features=c("Tnxb"), pt.size=0)
dev.off()
pdf(paste0(output, "_Cckar.pdf"))
VlnPlot(mySeurat, features=c("Cckar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Slitrk6.pdf"))
VlnPlot(mySeurat, features=c("Slitrk6"), pt.size=0)
dev.off()
pdf(paste0(output, "_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), pt.size=0)
dev.off()
pdf(paste0(output, "_Pdzrn4.pdf"))
VlnPlot(mySeurat, features=c("Pdzrn4"), pt.size=0)
dev.off()
pdf(paste0(output, "_Esr2.pdf"))
VlnPlot(mySeurat, features=c("Esr2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Shisa6.pdf"))
VlnPlot(mySeurat, features=c("Shisa6"), pt.size=0)
dev.off()
pdf(paste0(output, "_Sv2c.pdf"))
VlnPlot(mySeurat, features=c("Sv2c"), pt.size=0)
dev.off()
pdf(paste0(output, "_Egr3.pdf"))
VlnPlot(mySeurat, features=c("Egr3"), pt.size=0)
dev.off()
pdf(paste0(output, "_Egr4.pdf"))
VlnPlot(mySeurat, features=c("Egr4"), pt.size=0)
dev.off()
pdf(paste0(output, "_Slc18a2.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Pou3f3.pdf"))
VlnPlot(mySeurat, features=c("Pou3f3"), pt.size=0)
dev.off()
pdf(paste0(output, "_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), pt.size=0)
dev.off()
pdf(paste0(output, "_Nptx2.pdf"))
VlnPlot(mySeurat, features=c("Nptx2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Apoe.pdf"))
VlnPlot(mySeurat, features=c("Apoe"), pt.size=0)
dev.off()
pdf(paste0(output, "_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), pt.size=0)
dev.off()
pdf(paste0(output, "_Cited2.pdf"))
VlnPlot(mySeurat, features=c("Cited2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Zeb2.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Nptx1.pdf"))
VlnPlot(mySeurat, features=c("Nptx1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Penk.pdf"))
VlnPlot(mySeurat, features=c("Penk"), pt.size=0)
dev.off()
pdf(paste0(output, "_Rpl31.pdf"))
VlnPlot(mySeurat, features=c("Rpl31"), pt.size=0)
dev.off()
pdf(paste0(output, "_Ar.pdf"))
VlnPlot(mySeurat, features=c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Gal.pdf"))
VlnPlot(mySeurat, features=c("Gal"), pt.size=0)
dev.off()
pdf(paste0(output, "_Gpr165.pdf"))
VlnPlot(mySeurat, features=c("Gpr165"), pt.size=0)
dev.off()
pdf(paste0(output, "_Hpcal1.pdf"))
VlnPlot(mySeurat, features=c("Hpcal1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Ywhah.pdf"))
VlnPlot(mySeurat, features=c("Ywhah"), pt.size=0)
dev.off()
pdf(paste0(output, "_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), pt.size=0)
dev.off()
