#!/usr/bin/env Rscript

output <- "Seurat/POA_PrimedvUnprimed_doubletsremoved/POA_PrimedvUnprimed_Exploratory_doubletsremovedexploratory"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
State.integrated <- readRDS("Seurat/POA_PrimedvUnprimed_doubletsremoved/POA_PrimedvUnprimed_Exploratory_unfiltered.rds")
State.integrated
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(State.integrated, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(State.integrated, reduction="pca")
dev.off()
pdf(paste0(output,"_PC1-3.pdf"))
DimHeatmap(State.integrated, dims=1:3, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC4-6.pdf"))
DimHeatmap(State.integrated, dims=4:6, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC7-9.pdf"))
DimHeatmap(State.integrated, dims=7:9, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC10-12.pdf"))
DimHeatmap(State.integrated, dims=10:12, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC13-15.pdf"))
DimHeatmap(State.integrated, dims=13:15, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC16-18.pdf"))
DimHeatmap(State.integrated, dims=16:18, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC19-21.pdf"))
DimHeatmap(State.integrated, dims=19:21, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(State.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC25-27.pdf"))
DimHeatmap(State.integrated, dims=25:27, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(State.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC28-30.pdf"))
DimHeatmap(State.integrated, dims=28:30, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC31-33.pdf"))
DimHeatmap(State.integrated, dims=31:33, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC34-36.pdf"))
DimHeatmap(State.integrated, dims=34:36, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC37-39.pdf"))
DimHeatmap(State.integrated, dims=37:39, balanced=TRUE, cells=500)
dev.off()
#State.integrated <- JackStraw(State.integrated, dims=100, num.replicate=200)
#State.integrated <- ScoreJackStraw(State.integrated, dims=1:100)
#pdf(paste0(output,"_JackStrawplot_.pdf"))
#JackStrawPlot(State.integrated, dims=1:100)
#dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(State.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_Stateplit.pdf"))
DimPlot(State.integrated, reduction="umap", label=TRUE, split.by="state")
dev.off()
pdf(paste0(output,"_UMAP_Statelabel.pdf"))
DimPlot(State.integrated,reduction="umap", label=TRUE, group.by="state")
dev.off()
State.integrated.markers <- FindAllMarkers(State.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(State.integrated.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(State.integrated, file=(paste0(output, ".rds")))
pdf(paste0(output,"_Gad1featureplot.pdf"))
DefaultAssay(State.integrated) <- "RNA"
NormalizeData(State.integrated)
FeaturePlot(State.integrated, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(State.integrated, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(State.integrated, features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(State.integrated, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(State.integrated, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(State.integrated, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(State.integrated, features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(State.integrated, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(State.integrated, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(State.integrated, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(State.integrated, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(State.integrated, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(State.integrated, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(State.integrated, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(State.integrated, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(State.integrated, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(State.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(State.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
saveRDS(State.integrated, file=(paste0(output, "2.rds")))
