output <- "Seurat/VMH_PrimedvMale_AparnaNorm/VMH_origregress"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(Matrix)
library(matrixStats)
library(qlcMatrix)
library(igraph)
library(RANN)
MaleVMH.data <- Read10X(data.dir = "FemalePOAPrimed_Putative2/outs/filtered_feature_bc_matrix")
MaleVMH <- CreateSeuratObject(counts = MaleVMH.data, project = "MaleVMH", min.cells=3, min.features=200)
MaleVMHtotal <- colSums(MaleVMH[["RNA"]]@counts[rownames(MaleVMH[["RNA"]]@counts),])
MaleVMH_median <- median(MaleVMHtotal)
MaleVMHmaxes <- colMax(MaleVMH[["RNA"]]@counts[rownames(MaleVMH[["RNA"]]@counts),])
MaleVMHnorm <- MaleVMH[["RNA"]]@counts[rownames(MaleVMH[["RNA"]]@counts),]/as.numeric(MaleVMHmaxes)
MaleVMHcorrected <- MaleVMHnorm * MaleVMH_median
MaleVMHfinal <- CreateSeuratObject(counts = MaleVMHcorrected, project = "MaleVMH")
MaleVMHfinal
PrimedVMH.data <- Read10X(data.dir= "FemaleVMHPrimed/outs/filtered_feature_bc_matrix")
PrimedVMH <- CreateSeuratObject(counts = PrimedVMH.data, project = "PrimedVMH", min.cells=3, min.features=200)
PrimedVMHtotal <- colSums(PrimedVMH[["RNA"]]@counts[rownames(PrimedVMH[["RNA"]]@counts),])
PrimedVMH_median <- median(PrimedVMHtotal)
PrimedVMHmaxes <- colMax(PrimedVMH[["RNA"]]@counts[rownames(PrimedVMH[["RNA"]]@counts),])
PrimedVMHnorm <- PrimedVMH[["RNA"]]@counts[rownames(PrimedVMH[["RNA"]]@counts),]/as.numeric(PrimedVMHmaxes)
PrimedVMHcorrected <- PrimedVMHnorm * PrimedVMH_median
PrimedVMHfinal <- CreateSeuratObject(counts = PrimedVMHcorrected, project = "PrimedVMH")
PrimedVMHfinal
MaleVMHfinal$sex <- "Male"
PrimedVMHfinal$sex <- "Female"
mySeurat <- merge(MaleVMHfinal, y=c(PrimedVMHfinal), add.cell.ids=c("MaleVMH","PrimedVMH"), project="Merged")
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern = "^mt-")
mySeurat <- subset(mySeurat)
mySeurat <- NormalizeData(mySeurat)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeatures=2000)
mySeurat <- ScaleData(mySeurat, vars.to.regress="orig.ident")
mySeurat <- RunPCA(mySeurat)
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.1, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
pdf(paste0(output, "topmarkerheatmap.pdf"))
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
