#!/usr/bin/env Rscript

output <- "Seurat/VMH_MalevPrimedMerged_Exploratory/VMH_MalevPrimed_Exploratory_Vlns"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Sex.integrated <- readRDS("Seurat/VMH_MalevPrimedMerged_Exploratory/VMH_MalevPrimed_Exploratory_filtered1.rds")
DefaultAssay(Sex.integrated) <- "RNA"
Sex.integrated <- NormalizeData(Sex.integrated)
pdf(paste0(output, "_NRs1.pdf"))
VlnPlot(Sex.integrated, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs2.pdf"))
VlnPlot(Sex.integrated, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs3.pdf"))
VlnPlot(Sex.integrated, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs4.pdf"))
VlnPlot(Sex.integrated, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_markers1.pdf"))
VlnPlot(Sex.integrated, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_markers2.pdf"))
VlnPlot(Sex.integrated, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_markers3.pdf"))
VlnPlot(Sex.integrated, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_markers4.pdf"))
VlnPlot(Sex.integrated, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_1.pdf"))
VlnPlot(Sex.integrated, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_2.pdf"))
VlnPlot(Sex.integrated, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_3.pdf"))
VlnPlot(Sex.integrated, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_4.pdf"))
VlnPlot(Sex.integrated, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_1.pdf"))
VlnPlot(Sex.integrated, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_2.pdf"))
VlnPlot(Sex.integrated, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_3.pdf"))
VlnPlot(Sex.integrated, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_4.pdf"))
VlnPlot(Sex.integrated, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(Sex.integrated, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_2.pdf"))
VlnPlot(Sex.integrated, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_3.pdf"))
VlnPlot(Sex.integrated, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_4.pdf"))
VlnPlot(Sex.integrated, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(Sex.integrated, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()

