#!/usr/bin/env Rscript
output <- "Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate_filtered4_10pcs_res0.5_retransformed"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Sex.integrated <- readRDS("Seurat/VMH_BusMergeTest/VMH_BusMergeTest_nocastrate_filtered4_10pcs_res0.5_retransformed.rds")
pdf(paste0(output,"_PC1-3.pdf"))
DimHeatmap(Sex.integrated, dims=1:3, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC4-6.pdf"))
DimHeatmap(Sex.integrated, dims=4:6, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC7-9.pdf"))
DimHeatmap(Sex.integrated, dims=7:9, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC10-12.pdf"))
DimHeatmap(Sex.integrated, dims=10:12, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC13-15.pdf"))
DimHeatmap(Sex.integrated, dims=13:15, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC16-18.pdf"))
DimHeatmap(Sex.integrated, dims=16:18, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC19-21.pdf"))
DimHeatmap(Sex.integrated, dims=19:21, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC25-27.pdf"))
DimHeatmap(Sex.integrated, dims=25:27, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC28-30.pdf"))
DimHeatmap(Sex.integrated, dims=28:30, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC31-33.pdf"))
DimHeatmap(Sex.integrated, dims=31:33, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC34-36.pdf"))
DimHeatmap(Sex.integrated, dims=34:36, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC37-39.pdf"))
DimHeatmap(Sex.integrated, dims=37:39, balanced=TRUE, cells=500)
dev.off()
