#!/usr/bin/env Rscript

output <- "Seurat/POA_MalevUnprimedMerged_Exploratory/POA_MalevUnprimed_Exploratory_doubleltsremoved_naivemerge"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Male.data <- Read10X(data.dir = "MalePOAIntact/outs/filtered_feature_bc_matrix")
Male <- CreateSeuratObject(counts = Male.data, project = "MalePOA", min.cells=3, min.features=200)
Female.data <- Read10X(data.dir = "FemalePOAUnprimed/outs/filtered_feature_bc_matrix")
Unprimed <- CreateSeuratObject(counts = Female.data, project = "UnprimedPOA", min.cells=3, min.features=200)
Male <- subset(Male, subset=nFeature_RNA < 60000)
Unprimed <- subset(Unprimed, subset=nFeature_RNA <55000)
Male$sex <- "Male"
Unprimed$sex <- "Female"
mySeurat <- merge(Male, y=Unprimed, project="Merged", add.cell.ids =c("Male","Unprimed"))
mySeurat <- NormalizeData(mySeurat)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeatures=2000)
mySeurat <- ScaleData(mySeurat)
mySeurat <- RunPCA(mySeurat, features=VariableFeatures(object=mySeurat))
pdf(paste0(output,"_PCAplot.pdf"))
DimPlot(mySeurat, reduction="pca", group.by="sex")
dev.off()
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_origlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
mySeuratSeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeuratSeurat.markers, file=paste0(output, "_allposmarkers.csv"))
saveRDS(mySeurat, file=(paste0(output, ".rds")))
