#!/usr/bin/env Rscript
library(Seurat)
MaleBNST.data <- Read10X(data.dir = "Male_BNST_Esr1_10x_Pilot_antisenseGFP_v3-1_local_long/outs/raw_feature_bc_matrix")
MaleBNST <- CreateSeuratObject(counts = MaleBNST.data, project ="MaleBNST", min.cells=3, min.features=200)
MaleBNST
pdf(file="Seuratmetrics.pdf")
VlnPlot(MaleBNST, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(file="Seurat_Featurescatter_complexity.pdf")
FeatureScatter(MaleBNST, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
MaleBNST <- subset(MaleBNST, subset = nCount_RNA > 1000 & nCount_RNA < 28000)
pdf(file="Seurat_Markers_Esr1.pdf")
VlnPlot(MaleBNST, features = c("Esr1"))
dev.off()
pdf(file="Seurat_Genesvdepth.pdf")
plot1 <- FeatureScatter(MaleBNST, feature1="nCount_RNA", feature2="Esr1")
plot2 <- FeatureScatter(MaleBNST, feature1="nCount_RNA", feature2="St18")
plot3 <- FeatureScatter(MaleBNST, feature1="nCount_RNA", feature2="Rarb")
plot4 <- FeatureScatter(MaleBNST, feature1="nCount_RNA", feature2="Syn1")
CombinePlots(plots=list(plot1,plot2,plot3,plot4))
dev.off()
MaleBNST <- NormalizeData(MaleBNST)
MaleBNST <- FindVariableFeatures(MaleBNST, selection.method="vst", nfeature=2000)
top50 <- head (VariableFeatures(MaleBNST), 50)
pdf(file="Seurat_BNSTMaleVariablefeatures.pdf")
plot1 <- VariableFeaturePlot(MaleBNST)
LabelPoints(plot=plot1, points=top50, repel=TRUE)
dev.off()
MaleBNST <- ScaleData(MaleBNST)
MaleBNST <- RunPCA(MaleBNST, feature=VariableFeatures(object=MaleBNST))
print(MaleBNST[["pca"]], dims=1:20, nfeatures=10)
pdf("Seurat_MaleBNSTloadings")
VizDimLoadings(MaleBNST, dims=1:2, reduction="pca")
dev.off()
pdf("Seurat_MaleBNSTDimplot.pdf")
DimPlot(MaleBNST, reduction="pca")
dev.off()
pdf("Seurat_MaleBNST_PC1.pdf")
DimHeatmap(MaleBNST, dims=1, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC1-3.pdf")
DimHeatmap(MaleBNST, dims=1:3, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC4-6.pdf")
DimHeatmap(MaleBNST, dims=4:6, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC7-9.pdf")
DimHeatmap(MaleBNST, dims=7:9, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC10-12.pdf")
DimHeatmap(MaleBNST, dims=10:12, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC13-15.pdf")
DimHeatmap(MaleBNST, dims=13:15, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC16-18.pdf")
DimHeatmap(MaleBNST, dims=16:18, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC19-21.pdf")
DimHeatmap(MaleBNST, dims=19:21, balanced=TRUE)
dev.off()
pdf("Seurat_MaleBNST_PC22-24.pdf")
DimHeatmap(MaleBNST, dims=22:24, balanced=TRUE)
dev.off()
MaleBNST <- JackStraw(MaleBNST, num.replicate=200)
MaleBNST <- ScoreJackStraw(MaleBNST, dims=1:20)
pdf("Seurat_JackStrawplot_MaleBNST.pdf")
JackStrawPlot(MaleBNST, dims=1:20)
dev.off()
pdf("Seurat_MaleBNST_elbowplot.pdf")
ElbowPlot(MaleBNST, ndims=40)
dev.off()
MaleBNST <- FindNeighbors(MaleBNST, dims=1:30)
MaleBNST <- FindClusters(MaleBNST, resolution=0.3)
MaleBNST <- RunUMAP(MaleBNST, dims=1:30)
pdf("Seurat_MaleBNST_UMAP.pdf")
DimPlot(MaleBNST, reduction="umap", do.label=TRUE)
dev.off()
MaleBNST <- RunTSNE(MaleBNST, dims=1:30)
pdf("Seurat_MaleBNST_tSNE.pdf")
DimPlot(MaleBNST, reduction="tsne", do.label=TRUE)
dev.off()
MaleBNST.markers <- FindAllMarkers(MaleBNST)
head(MaleBNST.markers, n=20)

