#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/MalePOA_Exploratory/MalePOA_sctransform_50PCs"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Seurat.data <- Read10X(data.dir = "MalePOAIntact/outs/filtered_feature_bc_matrix")
mySeurat <- CreateSeuratObject(counts = Seurat.data, project = sampleID, min.cells=3, min.features=200)
pdf(paste0(output, "_basic_counts.pdf"))
VlnPlot(mySeurat, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(mySeurat, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
pdf(paste0(output, "_Esr1counts.pdf"))
VlnPlot(mySeurat, features = c("Esr1"))
dev.off()
mySeurat <- SCTransform(mySeurat, verbose=TRUE)
warnings()
mySeurat <- RunPCA(mySeurat, verbose=TRUE)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeature=2000)
top50 <- head (VariableFeatures(mySeurat), 50)
pdf(paste0(output, "_Variablefeatures.pdf"))
plot1 <- VariableFeaturePlot(mySeurat)
LabelPoints(plot=plot1, points=top50, repel=TRUE)
dev.off()
VariableFeatures <- (VariableFeatures(mySeurat))
write.csv(paste0(output, "_variablefeatures.csv"))
mySeurat <- ScaleData(mySeurat)
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat))
print(mySeurat[["pca"]], dims=1:20, nfeatures=10)
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(mySeurat, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(mySeurat, reduction="pca")
dev.off()
pdf(paste0(output,"_elbowplot.pdf"))
ElbowPlot(mySeurat, ndims=100)
dev.off()
mySeurat <- FindNeighbors(mySeurat, dims=1:50)
mySeurat <- FindClusters(mySeurat, resolution=1)
mySeurat <- RunUMAP(mySeurat, dims=1:50)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat2 <- RunTSNE(mySeurat, dims=1:30)
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(mySeurat2, reduction="tsne", do.label=TRUE)
dev.off()
pdf(paste0(output,"_Gad1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"))
dev.off()
pdf(paste0(output,"_Gad2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad2"))
dev.off()
pdf(paste0(output,"_Slc32a1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc32a1"))
dev.off()
pdf(paste0(output,"_Slc17a6featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"))
dev.off()
pdf(paste0(output,"_Slc17a8featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a8"))
dev.off()
pdf(paste0(output,"_Chatfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Chat"))
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Th"))
dev.off()
pdf(paste0(output,"_Olig1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Olig1"))
dev.off()
pdf(paste0(output,"_Mobpfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Mobp"))
dev.off()
pdf(paste0(output,"_Gfapfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gfap"))
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"))
dev.off()
pdf(paste0(output,"_Prr5lfeatureplot.pdf"))
FeaturePlot(mySeurat, features=c("Prr5l"))
dev.off()
pdf(paste0(output,"_Slc18a2featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc18a2"))
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(mySeurat, features =c("Gad1"))
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(mySeurat, features =c("Gad2"))
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(mySeurat, features =c("Slc32a1"))
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(mySeurat, features = c("Mobp"))
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(mySeurat, features = c("Gfap"))
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(mySeurat, features = c("Olig1"))
dev.off()
pdf(paste0(output, "_Vln_NRs.pdf"))
VlnPlot(mySeurat, features = c("Esr1","Ar","Pgr"))
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(mySeurat, features = c("Esr1"))
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(mySeurat, features = c("Ar"))
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(mySeurat, features = c("Pgr"))
dev.off()
pdf(paste0(output, "Vln_excitatorymarkers.pdf"))
VlnPlot(mySeurat, features = c("Slc17a6","Slc17a8"))
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(mySeurat, features = c("nCount_RNA"))
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(mySeurat, features = c("nFeature_RNA"))
dev.off()
mySeurate[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern="mt-")
pdf(paste0(output, "Vln_mitocluster.pdf"))
VlnPlot(mySeurat, features = c("percent.mt"))
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top20 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=20, wt=avg_logFC)
DoHeatmap(mySeurat, features=top20$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds"))
