#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/MalePOA_Exploratory/MalePOA_perplexity"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Sampledata.data <- Read10X(data.dir = "MalePOAIntact/outs/filtered_feature_bc_matrix")
mySeurat <- CreateSeuratObject(counts = Sampledata.data, project = sampleID, min.cells=3, min.features=200)
sampleID
mySeurat <- SCTransform(mySeurat, verbose=TRUE)
warnings()
mySeurat <- RunPCA(mySeurat, feature=VariableFeatures(object=mySeurat), npcs=30)
mySeurat <- FindNeighbors(mySeurat, dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=0.5)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP_0.5.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers_0.5.csv"))
pdf(paste0(output,"_TopMarkerheatmap_0.5.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
mySeurat <- FindClusters(mySeurat, resolution=1)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP_1.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers_1.csv"))
pdf(paste0(output,"_TopMarkerheatmap_1.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
mySeurat <- FindClusters(mySeurat, resolution=1.5)
mySeurat <- RunUMAP(mySeurat, dims=1:30)
pdf(paste0(output,"_UMAP_1.5.pdf"))
DimPlot(mySeurat, reduction="umap", do.label=TRUE)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers_1.5.csv"))
pdf(paste0(output,"_TopMarkerheatmap_1.5.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
