#!/usr/bin/env Rscript

output <- "Seurat/VMH_MalevPrimed_StandardCCA/VMH_MalevPrimed_StandardCCA_"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

MaleVMH.data <- Read10X(data.dir = "FemalePOAPrimed_Putative2/outs/filtered_feature_bc_matrix")
MaleVMH <- CreateSeuratObject(counts = MaleVMH.data, project = "MaleVMH", min.cells=3, min.features=200)
PrimedVMH.data <- Read10X(data.dir= "FemaleVMHPrimed/outs/filtered_feature_bc_matrix")
PrimedVMH <- CreateSeuratObject(counts = PrimedVMH.data, project = "PrimedVMH", min.cells=3, min.features=200)
MaleVMH$sex <- "Male"
PrimedVMH$sex <- "Female"
MaleVMH <- subset(MaleVMH, subset = nFeature_RNA >600 & nCount_RNA < 60000)
PrimedVMH <- subset(PrimedVMH, subset=nFeature_RNA > 600 & nCount_RNA < 60000)
MaleVMH <- NormalizeData(MaleVMH)
MaleVMH <- FindVariableFeatures(MaleVMH, selection.method="vst", nfeatures=2000)
PrimedVMH <- NormalizeData(PrimedVMH)
PrimedVMH <- FindVariableFeatures(PrimedVMH, selection.method="vst", nfeatures=2000)

sex.anchors <- FindIntegrationAnchors(object.list=list(PrimedVMH,MaleVMH), dims=1:30)
mySeurat <- IntegrateData(anchorset=sex.anchors, dims=1:30)
mySeurat <- ScaleData(mySeurat)
mySeurat <- RunPCA(mySeurat)
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.1, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
pdf(paste0(output, "topmarkerheatmap.pdf"))
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(paste0(output, "_NRs1.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs2.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs3.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs4.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_markers1.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_markers2.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_markers3.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_markers4.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_1.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_2.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_3.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_4.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_1.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_2.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_3.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_4.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_2.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_3.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_4.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()

