#!/usr/bin/env Rscript

output <- "Seurat/POA_PrimedvUnprimed_Exploratory/POA_PrimedUnprimed_Exploratory_minimal"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Primed.data <- Read10X(data.dir = "FemalePOAPrimed/outs/filtered_feature_bc_matrix")
PrimedPOA <- CreateSeuratObject(counts = Primed.data, project = "MalePOA", min.cells=3, min.features=200)
Unprimed.data <- Read10X(data.dir = "FemalePOAUnprimed/outs/filtered_feature_bc_matrix")
UnprimedPOA <- CreateSeuratObject(counts = Unprimed.data, project = "UnprimedPOA", min.cells=3, min.features=200)
UnprimedPOA <- RenameCells(UnprimedPOA, add.cell.id="Unprimed", for.merge=TRUE)
PrimedPOA <- SCTransform(PrimedPOA, verbose=TRUE, return.only.var.genes=FALSE)
UnprimedPOA <- SCTransform(UnprimedPOA, verbose=TRUE, return.only.var.genes=FALSE)
PrimedPOA$state <- "Primed"
UnprimedPOA$state <- "Unprimed"
Shared.features <- SelectIntegrationFeatures(object.list=list(PrimedPOA,UnprimedPOA), nfeatures=3000)
Shared.list <- PrepSCTIntegration(object.list=list(PrimedPOA,UnprimedPOA), anchor.features=Shared.features, verbose=TRUE)
Shared.anchors <- FindIntegrationAnchors(object.list=Shared.list, normalization.method="SCT", anchor.features=Shared.features, verbose=TRUE)
Sex.integrated <- IntegrateData(anchorset=Shared.anchors, normalization.method="SCT", verbose=TRUE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, dims=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=0.5)
pdf(paste0(output, "_basic_counts.pdf"))
VlnPlot(Sex.integrated, features=c("nFeature_RNA", "nCount_RNA"))
dev.off()
pdf(paste0(output, "_Featurescatter_complexity.pdf"))
FeatureScatter(Sex.integrated, feature1="nCount_RNA", feature2="nFeature_RNA")
dev.off()
pdf(paste0(output, "_Esr1counts.pdf"))
VlnPlot(Sex.integrated, features = c("Esr1"))
dev.off()
pdf(paste0(output, "_loadings.pdf"))
VizDimLoadings(Sex.integrated, dims=1:2, reduction="pca")
dev.off()
pdf(paste0(output,"_Dimplot.pdf"))
DimPlot(Sex.integrated, reduction="pca")
dev.off()
pdf(paste0(output,"_PC1-3.pdf"))
DimHeatmap(Sex.integrated, dims=1:3, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC4-6.pdf"))
DimHeatmap(Sex.integrated, dims=4:6, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC7-9.pdf"))
DimHeatmap(Sex.integrated, dims=7:9, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC10-12.pdf"))
DimHeatmap(Sex.integrated, dims=10:12, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC13-15.pdf"))
DimHeatmap(Sex.integrated, dims=13:15, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC16-18.pdf"))
DimHeatmap(Sex.integrated, dims=16:18, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC19-21.pdf"))
DimHeatmap(Sex.integrated, dims=19:21, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC25-27.pdf"))
DimHeatmap(Sex.integrated, dims=25:27, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC22-24.pdf"))
DimHeatmap(Sex.integrated, dims=22:24, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC28-30.pdf"))
DimHeatmap(Sex.integrated, dims=28:30, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC31-33.pdf"))
DimHeatmap(Sex.integrated, dims=31:33, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC34-36.pdf"))
DimHeatmap(Sex.integrated, dims=34:36, balanced=TRUE, cells=500)
dev.off()
pdf(paste0(output,"_PC37-39.pdf"))
DimHeatmap(Sex.integrated, dims=37:39, balanced=TRUE, cells=500)
dev.off()
#Sex.integrated <- JackStraw(Sex.integrated, dims=100, num.replicate=200)
#Sex.integrated <- ScoreJackStraw(Sex.integrated, dims=1:100)
#pdf(paste0(output,"_JackStrawplot_.pdf"))
#JackStrawPlot(Sex.integrated, dims=1:100)
#dev.off()
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(Sex.integrated, reduction="umap", do.label=TRUE)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(Sex.integrated, features = c("nFeature_RNA"), pt.size=0)
dev.off()
Sex.integrated.markers <- FindAllMarkers(Sex.integrated, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(Sex.integrated.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- Sex.integrated.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Sex.integrated, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Sex.integrated, file=(paste0(output, ".rds")))
