output <- "Seurat/PrimedPOA_Preprocessing/PrimedPOA_Doubletfinder"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(DoubletFinder)
mySeurat <- readRDS("Seurat/PrimedPOA_Exploratory/PrimedPOA_perplexity.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("1"), invert=TRUE)
filteredSeurat
filteredSeurat <- subset(filteredSeurat, subset=nCount_RNA < 55000)
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat <- FindClusters(filteredSeurat, verbose=TRUE, resolution=1.5)
filteredSeurat <- RunUMAP(filteredSeurat, dims=1:30)
filteredSeurat <- RunTSNE(filteredSeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_tSNE.pdf"))
DimPlot(filteredSeurat, reduction="tsne", label=TRUE)
dev.off()
sweep.res.list_Male <- paramSweep_v3(filteredSeurat, PCs=1:30, sct=TRUE)
sweep.stats_Male <- summarizeSweep(sweep.res.list_Male, GT=FALSE)
bcmvn_Male <- find.pK(sweep.stats_Male)
annotations <- filteredSeurat@meta.data$ClusteringResults
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.04*5500)
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
seu_Male <- doubletFinder_v3(mySeurat, PCs=1:30, pN=0.25, pK= 0.09, nExp=nExp_poi , reuse.pANN=FALSE, sct=TRUE)
seu_Male <- doubletFinder_v3(mySeurat, PCs=1:30, pN=0.25,	pK= 0.09, nExp=nExp_poi.adj , reuse.pANN=FALSE, sct=TRUE)
head(seu_Male[[]])
saveRDS(seu_Male, paste0(output,"doublets.RDS"))
