#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/FullPOA_Integrated/FullPOA_deepfilter_"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/FullPOA_Integrated/FullPOA_furtherfilteredunnormalized.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("21","24"), invert=TRUE)
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat <- FindClusters(filteredSeurat, verbose=TRUE, resolution=0.5)
filteredSeurat <- RunUMAP(filteredSeurat, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_statesplit.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, split.by="state")
dev.off()
pdf(paste0(output,"_UMAP_statelabel.pdf"))
DimPlot(filteredSeurat, reduction="umap", label=TRUE, group.by="state")
dev.off()
DefaultAssay(filteredSeurat) <- "RNA"
filteredSeurat <- NormalizeData(filteredSeurat)
pdf(paste0(output,"_pappafeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Pappa"), split.by="state")
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Esr1"), split.by="state")
dev.off()
pdf(paste0(output,"_Sytl4featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Sytl4"), split.by="state")
dev.off()
pdf(paste0(output,"_Ovgp1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Ovgp1"), split.by="state")
dev.off()
pdf(paste0(output,"_Crim1featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Crim1"), split.by="state")
dev.off()
pdf(paste0(output,"_Esr2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Esr2"), split.by="state")
dev.off()
pdf(paste0(output,"_Arfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Ar"), split.by="state")
dev.off()
pdf(paste0(output,"_Pgrfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Pgr"), split.by="state")
dev.off()
pdf(paste0(output,"_Thfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Th"), split.by="state")
dev.off()
pdf(paste0(output,"_Shisa6featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Shisa6"), split.by="state")
dev.off()
pdf(paste0(output,"_Tnxbfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Tnxb"), split.by="state")
dev.off()
pdf(paste0(output,"_Kirrelfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Kirrel"), split.by="state")
dev.off()
pdf(paste0(output,"_Zeb2featureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Zeb2"), split.by="state")
dev.off()
pdf(paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Cckar"), split.by="state")
dev.off()
pdf(paste0(output,"_Apoefeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Apoe"), split.by="state")
dev.off()
pdf(paste0(output,"_Npy2rfeatureplot.pdf"))
FeaturePlot(filteredSeurat, features=c("Npy2r"), split.by="state")
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(filteredSeurat, features =c("Gad1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(filteredSeurat, features =c("Gad2"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Slc32a1.pdf"))
VlnPlot(filteredSeurat, features =c("Slc32a1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Mobp.pdf"))
VlnPlot(filteredSeurat, features = c("Mobp"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Gfap.pdf"))
VlnPlot(filteredSeurat, features = c("Gfap"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Olig1markers.pdf"))
VlnPlot(filteredSeurat, features = c("Olig1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Esr1.pdf"))
VlnPlot(filteredSeurat, features = c("Esr1"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(filteredSeurat, features = c("Ar"), pt.size=0)
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(filteredSeurat, features = c("Pgr"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_UMIcluster.pdf"))
VlnPlot(filteredSeurat, features = c("nCount_RNA"), pt.size=0)
dev.off()
pdf(paste0(output, "Vln_GeneCountcluster.pdf"))
VlnPlot(filteredSeurat, features = c("nFeature_RNA"), pt.size=0)
dev.off()
saveRDS(filteredSeurat, file=(paste0(output, ".rds")))
filteredSeurat.markers <- FindAllMarkers(filteredSeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(filteredSeurat.markers, file=paste0(output, "_allposmarkers.csv"))
pdf(paste0(output, "_TopMarkerheatmap.pdf"))
top10 <- filteredSeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(filteredSeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(filteredSeurat, file=(paste0(output, ".rds")))
