
#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/FullPOA_Integrated/FullPOA_deepfilter_clustertest_sctransform"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/FullPOA_Integrated/FullPOA_furtherfilteredunnormalized.rds")
mySeurat
filteredSeurat <- subset(mySeurat, idents=c("21","24","28"), invert=TRUE)
filteredSeurat <- SCTransform(filteredSeurat)
filteredSeurat <- RunPCA(filteredSeurat, verbose=TRUE)
filteredSeurat <- FindNeighbors(filteredSeurat, dims=1:30, verbose=TRUE)
filteredSeurat1 <- FindClusters(filteredSeurat, verbose=TRUE, resolution=0.5)
filteredSeurat1 <- RunUMAP(filteredSeurat1, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat1, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_0.5_sexsplit.pdf"))
DimPlot(filteredSeurat1, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_0.5_sexlabel.pdf"))
DimPlot(filteredSeurat1, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_0.5_statesplit.pdf"))
DimPlot(filteredSeurat1, reduction="umap", label=TRUE, split.by="state")
dev.off()
pdf(paste0(output,"_UMAP_0.5_statelabel.pdf"))
DimPlot(filteredSeurat1, reduction="umap", label=TRUE, group.by="state")
dev.off()
filteredSeurat1.markers <- FindAllMarkers(filteredSeurat1, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(filteredSeurat1.markers, file=paste0(output, "_0.5_allposmarkers.csv"))
saveRDS(Full.integrated, file=(paste0(output, "_05.rds")))
filteredSeurat2 <- FindClusters(filteredSeurat, verbose=TRUE, resolution=1)
filteredSeurat2 <- RunUMAP(filteredSeurat2, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat2, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_1_sexsplit.pdf"))
DimPlot(filteredSeurat2, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_1_sexlabel.pdf"))
DimPlot(filteredSeurat2, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_1_statesplit.pdf"))
DimPlot(filteredSeurat2, reduction="umap", label=TRUE, split.by="state")
dev.off()
pdf(paste0(output,"_UMAP_1_statelabel.pdf"))
DimPlot(filteredSeurat2, reduction="umap", label=TRUE, group.by="state")
dev.off()
filteredSeurat2.markers <- FindAllMarkers(filteredSeurat2, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(filteredSeurat2.markers, file=paste0(output, "_1_allposmarkers.csv"))
saveRDS(Full.integrated, file=(paste0(output, "_1.rds")))
filteredSeurat3 <- FindClusters(filteredSeurat, verbose=TRUE, resolution=1.5)
filteredSeurat3 <- RunUMAP(filteredSeurat3, dims=1:30)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(filteredSeurat3, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_1.5_sexsplit.pdf"))
DimPlot(filteredSeurat3, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_1.5_sexlabel.pdf"))
DimPlot(filteredSeurat3, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_1.5_statesplit.pdf"))
DimPlot(filteredSeurat3, reduction="umap", label=TRUE, split.by="state")
dev.off()
pdf(paste0(output,"_UMAP_1.5_statelabel.pdf"))
DimPlot(filteredSeurat3, reduction="umap", label=TRUE, group.by="state")
dev.off()
filteredSeurat3.markers <- FindAllMarkers(filteredSeurat3, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(filteredSeurat3.markers, file=paste0(output, "_1.5_allposmarkers.csv"))
saveRDS(Full.integrated, file=(paste0(output, "_1.5.rds")))
