#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimed_Doubletsremoved/MalevUnprimed_Fineclusters_Doubletsremoved_filtered"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_doubletsremoved_filtered3.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
mySeurat$celltype.sex <- paste(Idents(mySeurat), mySeurat$sex, sep="_")
mySeurat$celltype <- Idents(mySeurat)
Idents(mySeurat) <- "celltype.sex"
pdf(paste0(output, "_Cluster1_Smoc2.pdf"))
VlnPlot(mySeurat, features=c("Smoc2"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Shisa6.pdf"))
VlnPlot(mySeurat, features=c("Shisa6"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Pcsk2.pdf"))
VlnPlot(mySeurat, features=c("Pcsk2"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Peg10.pdf"))
VlnPlot(mySeurat, features=c("Peg10"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Arhgef26.pdf"))
VlnPlot(mySeurat, features=c("Arhgef26"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Moxd1.pdf"))
VlnPlot(mySeurat, features=c("Moxd1"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster9_Moxd1.pdf"))
VlnPlot(mySeurat, features=c("Moxd1"), idents=c("9_Male","9_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Tmem215.pdf"))
VlnPlot(mySeurat, features=c("Tmem215"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Sytl4.pdf"))
VlnPlot(mySeurat, features=c("Sytl4"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster10_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("10_Male","10_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster5_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("5_Male","5_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Drd2.pdf"))
VlnPlot(mySeurat, features=c("Drd2"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster8_Pou3f3.pdf"))
VlnPlot(mySeurat, features=c("Pou3f3"), idents=c("8_Male","8_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster22_Pou3f3.pdf"))
VlnPlot(mySeurat, features=c("Pou3f3"), idents=c("22_Male","22_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster32_Pou3f3.pdf"))
VlnPlot(mySeurat, features=c("Pou3f3"), idents=c("32_Male","32_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster4_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), idents=c("4_Male","4_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster5_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), idents=c("5_Male","5_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster8_Kirrel.pdf"))
VlnPlot(mySeurat, features=c("Kirrel"), idents=c("8_Male","8_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster4_Slc18a2.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), idents=c("4_Male","4_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Slc18a2.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster28_Slc18a2.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), idents=c("28_Male","28_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster38_Slc18a2.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), idents=c("38_Male","38_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster10_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("10_Male","10_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster12_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("12_Male","12_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster16_Sulf1.pdf"))
VlnPlot(mySeurat, features=c("Sulf1"), idents=c("16_Male","16_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Apoe.pdf"))
VlnPlot(mySeurat, features=c("Apoe"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Apoe.pdf"))
VlnPlot(mySeurat, features=c("Apoe"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Apoe.pdf"))
VlnPlot(mySeurat, features=c("Apoe"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Apoe.pdf"))
VlnPlot(mySeurat, features=c("Apoe"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster4_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), idents=c("4_Male","4_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster5_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), idents=c("5_Male","5_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Gpr50.pdf"))
VlnPlot(mySeurat, features=c("Gpr50"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Cited2.pdf"))
VlnPlot(mySeurat, features=c("Cited2"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Cited2.pdf"))
VlnPlot(mySeurat, features=c("Cited2"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Cited2.pdf"))
VlnPlot(mySeurat, features=c("Cited2"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Nptx2.pdf"))
VlnPlot(mySeurat, features=c("Nptx2"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Nptx2.pdf"))
VlnPlot(mySeurat, features=c("Nptx2"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster33_Nptx2.pdf"))
VlnPlot(mySeurat, features=c("Nptx2"), idents=c("33_Male","33_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster16_Nptx2.pdf"))
VlnPlot(mySeurat, features=c("Nptx2"), idents=c("16_Male","16_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster5_Penk.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), idents=c("5_Male","5_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster5_Zeb2.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), idents=c("5_Male","5_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster22_Zeb2.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), idents=c("22_Male","22_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster26_Zeb2.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), idents=c("26_Male","26_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster31_Zeb2.pdf"))
VlnPlot(mySeurat, features=c("Zeb2"), idents=c("31_Male","31_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster24_Penk.pdf"))
VlnPlot(mySeurat, features=c("Penk"), idents=c("24_Male","24_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster31_Penk.pdf"))
VlnPlot(mySeurat, features=c("Penk"), idents=c("31_Male","31_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster20_Nptx1.pdf"))
VlnPlot(mySeurat, features=c("Nptx1"), idents=c("20_Male","20_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Nptx1.pdf"))
VlnPlot(mySeurat, features=c("Nptx1"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Nptx1.pdf"))
VlnPlot(mySeurat, features=c("Nptx1"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Nptx1.pdf"))
VlnPlot(mySeurat, features=c("Nptx1"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster9_Rpl31.pdf"))
VlnPlot(mySeurat, features=c("Rpl31"), idents=c("9_Male","9_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster11_Rpl31.pdf"))
VlnPlot(mySeurat, features=c("Rpl31"), idents=c("11_Male","11_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Ar.pdf"))
VlnPlot(mySeurat, features=c("Ar"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Ar.pdf"))
VlnPlot(mySeurat, features=c("Ar"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster7_Ar.pdf"))
VlnPlot(mySeurat, features=c("Ar"), idents=c("7_Male","7_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Hpcal1.pdf"))
VlnPlot(mySeurat, features=c("Hpcal1"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Hpcal1.pdf"))
VlnPlot(mySeurat, features=c("Hpcal1"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster6_Hpcal1.pdf"))
VlnPlot(mySeurat, features=c("Hpcal1"), idents=c("6_Male","6_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Hpcal1.pdf"))
VlnPlot(mySeurat, features=c("Hpcal1"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Ywhah.pdf"))
VlnPlot(mySeurat, features=c("Ywhah"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Ywhah.pdf"))
VlnPlot(mySeurat, features=c("Ywhah"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster2_Ywhah.pdf"))
VlnPlot(mySeurat, features=c("Ywhah"), idents=c("2_Male","2_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Ywhah.pdf"))
VlnPlot(mySeurat, features=c("Ywhah"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster0_Gal.pdf"))
VlnPlot(mySeurat, features=c("Gal"), idents=c("0_Male","0_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster3_Gal.pdf"))
VlnPlot(mySeurat, features=c("Gal"), idents=c("3_Male","3_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster28_Gal.pdf"))
VlnPlot(mySeurat, features=c("Gal"), idents=c("28_Male","28_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster1_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("1_Male","1_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster4_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("4_Male","4_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster13_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("13_Male","13_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster14_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("14_Male","14_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster24_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("24_Male","24_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster25_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("25_Male","25_Female"), pt.size=1, combine=TRUE)
dev.off()
pdf(paste0(output, "_Cluster40_Pappa.pdf"))
VlnPlot(mySeurat, features=c("Pappa"), idents=c("40_Male","40_Female"), pt.size=1, combine=TRUE)
dev.off()
