#!/usr/bin/env Rscript

output <- "Seurat/POA_MalevPrimed_Filteredintegration/POA_MalevUnprimed_filtered_scaled_unfiltered"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
UnprimedPOA <- Read10X(data.dir = "FemalePOAUnprimed/outs/filtered_feature_bc_matrix")
UnprimedPOA
MalePOA <- Read10X(data.dir = "MalePOAIntact/outs/filtered_feature_bc_matrix")
MalePOA
MalePOA$sex <- "Male"
UnprimedPOA$sex <- "Female"
MalePOA <- NormalizeData(MalePOA, verbose=TRUE)
MalePOA <- FindVariableFeatures(MalePOA, selection.method= "vst", nfeatures=2000)
UnprimedPOA <- NormalizeData(UnprimedPOA, verbose=TRUE)
UnprimedPOA <- FindVariableFeatures(UnprimedPOA, selection.method= "vst", nfeatures=2000)
sex.anchors <- FindIntegrationAnchors(object.list=list(MalePOA,UnprimedPOA), dims=1:30)
to_integrate <- Reduce(intersect, lapply(sex.anchors@object.list, rownames))
Sex.integrated <- IntegrateData(anchorset = sex.anchors, dims=1:30, features.to.integrate=to_integrate)
DefaultAssay(Sex.integrated) <- "integrated"
Sex.integrated <- ScaleData(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunPCA(Sex.integrated, verbose=TRUE)
Sex.integrated <- RunUMAP(Sex.integrated, reduction="pca", dim=1:30)
Sex.integrated <- FindNeighbors(Sex.integrated, reduction ="pca", dims=1:30)
Sex.integrated <- FindClusters(Sex.integrated, resolution=0.5)
pdf(paste0(output, "_umap_sctransform.pdf"))
DimPlot(Sex.integrated, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output, "_umap_sctransform_sexsplit.pdf"))
DimPlot(Sex.integrated, reduction="umap", split.by="sex")
dev.off()
pdf(paste0(output, "_umap_ctransform_sexlabel.pdf"))
DimPlot(Sex.integrated, reduction="umap", group.by="sex")
dev.off()
pdf(paste0(output,"_Pappafeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Pappa"), split.by="sex")
dev.off()
pdf(paste0(output,"_Arfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Ar"), split.by="sex")
dev.off()
pdf(paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Esr1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Cckar"), split.by="sex")
dev.off()
pdf(paste0(output,"_Sytl4featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Sytl4"), split.by="sex")
dev.off()
pdf(paste0(output,"_Cyp19a1featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Cyp19a1"), split.by="sex")
dev.off()
pdf(paste0(output,"_Nptx2featureplot.pdf"))
FeaturePlot(Sex.integrated, features=c("Nptx2"), split.by="sex")
dev.off()
Idents(Sex.integrated) <-  factor(Idents(Sex.integrated))
markers.to.plot <- c("Esr1", "Ar", "Pappa", "Nptx2","Apoe","Cenpb","Ntsr1","Rpl27a","Penk","Rpl31","St3gal2","Sytl4","Acvr1c","Tnxb","Cckar","Pdzrn4","Col25a1","Gpr165","Xkr4","Sv2c","Gal","Moxd1","Ecel1")
pdf(paste0(output, "_DotPlot.pdf"))
DotPlot(Sex.integrated, features = rev(markers.to.plot), cols=c("red","blue"), dot.scale=8, split.by="sex") + RotatedAxis()
dev.off()
pdf(paste0(output, "_Vln_Gad1.pdf"))
VlnPlot(Sex.integrated, features =c("Gad1"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Gad2.pdf"))
VlnPlot(Sex.integrated, features =c("Gad2"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Pappa.pdf"))
VlnPlot(Sex.integrated, features =c("Pappa"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Ar.pdf"))
VlnPlot(Sex.integrated, features =c("Ar"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Pgr.pdf"))
VlnPlot(Sex.integrated, features =c("Pgr"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Sytl4.pdf"))
VlnPlot(Sex.integrated, features =c("Sytl4"), pt.size=0, split.by="sex")
dev.off()
pdf(paste0(output, "_Vln_Penk.pdf"))
VlnPlot(Sex.integrated, features =c("Penk"), pt.size=0, split.by="sex")
dev.off()
write.csv(paste0(output, "_integratedmarkers.csv"))
Sex.integrated$celltype.sex <- paste(Idents(Sex.integrated), Sex.integrated$sex, sep="_")
Sex.integrated$celltype <- Idents(Sex.integrated)
Idents(Sex.integrated) <- "celltype.sex"
sex.dimorphism1 <- FindMarkers(Sex.integrated, ident.1 = "1_Male", ident.2="1_Female", verbose=FALSE)
write.csv(sex.dimorphism1, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism2 <- FindMarkers(Sex.integrated, ident.1 = "2_Male", ident.2="2_Female", verbose=FALSE)
write.csv(sex.dimorphism2, file=paste0(output, "_cluster2dimorphisms.csv"))
sex.dimorphism3 <- FindMarkers(Sex.integrated, ident.1 = "3_Male", ident.2="3_Female", verbose=FALSE)
write.csv(sex.dimorphism3, file=paste0(output, "_cluster3dimorphisms.csv"))
sex.dimorphism4 <- FindMarkers(Sex.integrated, ident.1 = "4_Male", ident.2="4_Female", verbose=FALSE)
write.csv(sex.dimorphism4, file=paste0(output, "_cluster4dimorphisms.csv"))
sex.dimorphism5 <- FindMarkers(Sex.integrated, ident.1 = "5_Male", ident.2="5_Female", verbose=FALSE)
write.csv(sex.dimorphism5, file=paste0(output, "_cluster5dimorphisms.csv"))
sex.dimorphism6 <- FindMarkers(Sex.integrated, ident.1 = "6_Male", ident.2="6_Female", verbose=FALSE)
write.csv(sex.dimorphism6, file=paste0(output, "_cluster6dimorphisms.csv"))
sex.dimorphism7 <- FindMarkers(Sex.integrated, ident.1 = "7_Male", ident.2="7_Female", verbose=FALSE)
write.csv(sex.dimorphism7, file=paste0(output, "_cluster7dimorphisms.csv"))
sex.dimorphism8 <- FindMarkers(Sex.integrated, ident.1 = "8_Male", ident.2="8_Female", verbose=FALSE)
write.csv(sex.dimorphism8, file=paste0(output, "_cluster8dimorphisms.csv"))
sex.dimorphism9 <- FindMarkers(Sex.integrated, ident.1 = "9_Male", ident.2="9_Female", verbose=FALSE)
write.csv(sex.dimorphism9, file=paste0(output, "_cluster9dimorphisms.csv"))
sex.dimorphism10 <- FindMarkers(Sex.integrated, ident.1 = "10_Male", ident.2="10_Female", verbose=FALSE)
write.csv(sex.dimorphism10, file=paste0(output, "_cluster10dimorphisms.csv"))
sex.dimorphism11 <- FindMarkers(Sex.integrated, ident.1 = "11_Male", ident.2="11_Female", verbose=FALSE)
write.csv(sex.dimorphism11, file=paste0(output, "_cluster11dimorphisms.csv"))
sex.dimorphism12 <- FindMarkers(Sex.integrated, ident.1 = "12_Male", ident.2="12_Female", verbose=FALSE)
write.csv(sex.dimorphism12, file=paste0(output, "_cluster12dimorphisms.csv"))
sex.dimorphism13 <- FindMarkers(Sex.integrated, ident.1 = "13_Male", ident.2="13_Female", verbose=FALSE)
write.csv(sex.dimorphism13, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism14 <- FindMarkers(Sex.integrated, ident.1 = "14_Male", ident.2="14_Female", verbose=FALSE)
write.csv(sex.dimorphism14, file=paste0(output, "_cluster14dimorphisms.csv"))
sex.dimorphism15 <- FindMarkers(Sex.integrated, ident.1 = "15_Male", ident.2="15_Female", verbose=FALSE)
write.csv(sex.dimorphism15, file=paste0(output, "_cluster15dimorphisms.csv"))
sex.dimorphism16 <- FindMarkers(Sex.integrated, ident.1 = "16_Male", ident.2="16_Female", verbose=FALSE)
write.csv(sex.dimorphism16, file=paste0(output, "_cluster16dimorphisms.csv"))
sex.dimorphism17 <- FindMarkers(Sex.integrated, ident.1 = "17_Male", ident.2="17_Female", verbose=FALSE)
write.csv(sex.dimorphism17, file=paste0(output, "_cluster17dimorphisms.csv"))
sex.dimorphism18 <- FindMarkers(Sex.integrated, ident.1 = "18_Male", ident.2="18_Female", verbose=FALSE)
write.csv(sex.dimorphism18, file=paste0(output, "_cluster18dimorphisms.csv"))
sex.dimorphism19 <- FindMarkers(Sex.integrated, ident.1 = "19_Male", ident.2="19_Female", verbose=FALSE)
write.csv(sex.dimorphism19, file=paste0(output, "_cluster19dimorphisms.csv"))
sex.dimorphism20 <- FindMarkers(Sex.integrated, ident.1 = "20_Male", ident.2="20_Female", verbose=FALSE)
write.csv(sex.dimorphism20, file=paste0(output, "_cluster20dimorphisms.csv"))
sex.dimorphism21 <- FindMarkers(Sex.integrated, ident.1 = "21_Male", ident.2="21_Female", verbose=FALSE)
write.csv(sex.dimorphism21, file=paste0(output, "_cluster21dimorphisms.csv"))
sex.dimorphism22 <- FindMarkers(Sex.integrated, ident.1 = "22_Male", ident.2="22_Female", verbose=FALSE)
write.csv(sex.dimorphism22, file=paste0(output, "_cluster22dimorphisms.csv"))
sex.dimorphism23 <- FindMarkers(Sex.integrated, ident.1 = "23_Male", ident.2="23_Female", verbose=FALSE)
write.csv(sex.dimorphism23, file=paste0(output, "_cluster23dimorphisms.csv"))
sex.dimorphism24 <- FindMarkers(Sex.integrated, ident.1 = "24_Male", ident.2="24_Female", verbose=FALSE)
write.csv(sex.dimorphism24, file=paste0(output, "_cluster24dimorphisms.csv"))
sex.dimorphism25 <- FindMarkers(Sex.integrated, ident.1 = "25_Male", ident.2="25_Female", verbose=FALSE)
write.csv(sex.dimorphism25, file=paste0(output, "_cluster25dimorphisms.csv"))
sex.dimorphism26 <- FindMarkers(Sex.integrated, ident.1 = "26_Male", ident.2="26_Female", verbose=FALSE)
write.csv(sex.dimorphism26, file=paste0(output, "_cluster26dimorphisms.csv"))
sex.dimorphism27 <- FindMarkers(Sex.integrated, ident.1 = "27_Male", ident.2="27_Female", verbose=FALSE)
write.csv(sex.dimorphism27, file=paste0(output, "_cluster27dimorphisms.csv"))
sex.dimorphism28 <- FindMarkers(Sex.integrated, ident.1 = "28_Male", ident.2="28_Female", verbose=FALSE)
write.csv(sex.dimorphism28, file=paste0(output, "_cluster28dimorphisms.csv"))
