#!/usr/bin/env Rscript

output <- "Seurat/POA_FullmergeTest/POA_Fullmerge_Exploratory_DEexclude"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

MalePOA.data <- Read10X(data.dir= "MalePOAIntact/outs/filtered_feature_bc_matrix")
MalePOA <- CreateSeuratObject(counts = MalePOA.data, project = "MalePOA", min.cells=3, min.features=200)
PrimedPOA.data <- Read10X(data.dir= "MaleMeAIntact/outs/filtered_feature_bc_matrix")
PrimedPOA <- CreateSeuratObject(counts = PrimedPOA.data, project = "PrimedPOA", min.cells=3, min.features=200)
UnprimedPOA.data <- Read10X(data.dir= "FemalePOAUnprimed/outs/filtered_feature_bc_matrix")
UnprimedPOA <- CreateSeuratObject(counts = UnprimedPOA.data, project = "UnprimedPOA", min.cells=3, min.features=200)
MalePOA$sex <- "Male"
MalePOA$Hormone <- "Intact"
PrimedPOA$sex <- "Female"
PrimedPOA$Hormone <- "Primed"
UnprimedPOA$sex <- "Female"
UnprimedPOA$Hormone <- "Unprimed"
mySeurat <- merge(MalePOA, y=c(PrimedPOA,UnprimedPOA), add.cell.ids=c("MalePOA","PrimedPOA","UnprimedPOA"), project="Merged")
mySeurat[["percent.mt"]] <- PercentageFeatureSet(mySeurat, pattern = "^mt-")
mySeurat <- subset(mySeurat, subset = nFeature_RNA >600 & nCount_RNA < 60000 & percent.mt < 15)
mySeurat <- NormalizeData(mySeurat)
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeatures=2000)
genelist <- read.table("Genelists/POA_DEall.txt", header=FALSE)
genelist
genelist <- unlist(genelist)
genelist
genelist <- as.matrix(genelist)
genelist
mySeurat <- FindVariableFeatures(mySeurat, selection.method="vst", nfeatures=2000)
mySeurat
head(mySeurat[[]])
hvg <- mySeurat@assays$RNA@var.features
hvg <- unlist(hvg)
hvg
hvg <- as.matrix(hvg)
hvg.final <- setdiff(hvg, genelist)
hvg.final
mySeurat <- ScaleData(mySeurat)
mySeurat <- RunPCA(mySeurat)
mySeurat <- RunUMAP(mySeurat, reduction="pca", dim=1:30)
mySeurat <- FindNeighbors(mySeurat, reduction ="pca", dims=1:30)
mySeurat <- FindClusters(mySeurat, resolution=1)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))
saveRDS(mySeurat, file=(paste0(output, ".rds")))
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(paste0(output, "_NRs1.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs2.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs3.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_NRs4.pdf"))
VlnPlot(mySeurat, features=c("Esr1","Pgr","Ar"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_markers1.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_markers2.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_markers3.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_markers4.pdf"))
VlnPlot(mySeurat, features=c("Nr5a1","Satb2","Dlk1"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_1.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_2.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_3.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic1_4.pdf"))
VlnPlot(mySeurat, features=c("Cckar","Setdb2","Phf21b"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_1.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_2.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_3.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic2_4.pdf"))
VlnPlot(mySeurat, features=c("Rprm","Mical2","Ezr"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_2.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(10:18), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_3.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(19:27), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_4.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(28:34), split.by="sex")
dev.off()
pdf(paste0(output, "_dimorphic3_1.pdf"))
VlnPlot(mySeurat, features=c("Pdyn","Cckbr","Stxbp6"), pt.size=0, ncol=1, idents=c(1:9), split.by="sex")
dev.off()

