#!/usr/bin/env Rscript
output <- "Seurat/VMH_BusMergeTest/VMH_PostmergeAgreementTest"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
Unprimed <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered3_Unprimed_30pcs_res1.rds")
Primed <- readRDS("
mySeurat <- subset(mySeurat, idents=c("12","18"), invert=TRUE)
mySeurat <- RunPCA(mySeurat)
warnings()
mySeurat <- FindNeighbors(mySeurat, dims=1:10)
mySeurat <- FindClusters(mySeurat, resolution=1)
mySeurat <- RunUMAP(mySeurat, dims=1:10)
mySeurat <- RunTSNE(mySeurat, dims=1:10)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_TSNE.pdf"))
DimPlot(mySeurat, reduction="tsne", label=TRUE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_umap.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="umap", cols=c("yellow","purple"), label=FALSE)
dev.off()
pdf(paste0(output,"_Cckarfeatureplot_tsne.pdf"))
FeaturePlot(mySeurat, features="Cckar", reduction="tsne", cols=c("yellow","purple"),  label=FALSE)
dev.off()
pdf(file=paste0(output, "Vln.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Esr1","Pgr","Cckar"), pt.size=0, ncol=1)
dev.off()
pdf(paste0(output,"_UMAP_sexplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat,reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_statussplit.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, split.by="status")
dev.off()
pdf(paste0(output,"_UMAP_statuslabel.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, group.by="status")
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25)
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_TopMarkerheatmap.pdf"))
top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
dev.off()
saveRDS(mySeurat, file=(paste0(output, ".rds")))

