#!/usr/bin/env Rscript

output <- "Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered3_Primed_20pcs_res1"

library(BUSpaRse)
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

Primed <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered2_Primed_20pcs_res1_Primed.rds")
Primed <- subset(Primed, idents=c("15"), invert=TRUE)
Primed <- SCTransform(Primed, verbose=TRUE)
Primed <- RunPCA(Primed)
warnings()
Primed <- FindNeighbors(Primed, dims=1:20)
Primed <- FindClusters(Primed, resolution=1)
Primed <- RunUMAP(Primed, dims=1:20)
pdf(paste0(output,"_Primed_UMAP.pdf"))
DimPlot(Primed, reduction="umap", label=TRUE)
dev.off()
Primed <- BuildClusterTree(Primed, dims=1:20)
pdf(paste0(output,"_Primed_clustertree.pdf"))
PlotClusterTree(object=Primed)
dev.off()
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=14)
VlnPlot(Primed, features=c("Esr1", "Slc17a6","Gad1","Cyp19a1"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindAllMarkers(Primed, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.1, logfc.threshold = 0.25, test.use="MAST")
write.csv(Primed.markers, file=paste0(output,"_Primed_allposmarkers.csv"))
pdf(paste0(output,"_Primed_TopMarkerheatmap.pdf"))
top10 <- Primed.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(Primed, features=top10$gene) + NoLegend()
dev.off()
saveRDS(Primed, file=(paste0(output, "_Primed.rds")))
