#!/usr/bin/env Rscript

output <- "Seurat/VMH_IndependentAnalysis/VMH_Fullmerge_Test_CCAtestallDEGbiaspca_filtered4"
library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)
mySeurat2 <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_Fullmerge_Test_CCAtestallDEGbiaspca_filtered3.rds")
mySeurat2 <- subset(mySeurat2, idents=c("38","33","16","21"), invert=TRUE)
allgenes <- (x=rownames(x=mySeurat2))
DefaultAssay(mySeurat2) <- "integrated"

VMH.features <- read.csv("Seurat/VMH_IndependentAnalysis/VMH_integrationfeatures.txt", header=FALSE)
VMH.features <- unlist(VMH.features)
VMH.features <- unique(VMH.features)
anchors.filtered <- intersect(VMH.features, allgenes)
genelist <- read.table("ExcludeIDs.txt", header=FALSE)
genelist <- unlist(genelist)
genelist <- as.matrix(genelist)
anchors.final <- setdiff(anchors.filtered, genelist)
mySeurat2 <- RunPCA(mySeurat2, features=anchors.final)
mySeurat2 <- RunUMAP(mySeurat2, reduction="pca", dim=1:40)
mySeurat2 <- FindNeighbors(mySeurat2, reduction ="pca", dims=1:40)
mySeurat2 <- FindClusters(mySeurat2, resolution=1.5)
pdf(paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat2, reduction="umap", label=TRUE)
dev.off()
pdf(paste0(output,"_UMAP_sexsplit.pdf"))
DimPlot(mySeurat2, reduction="umap", label=TRUE, split.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_sexlabel.pdf"))
DimPlot(mySeurat2, reduction="umap", label=TRUE, group.by="sex")
dev.off()
pdf(paste0(output,"_UMAP_hormonesplit.pdf"))
DimPlot(mySeurat2, reduction="umap", label=TRUE, split.by="Hormone")
dev.off()
pdf(paste0(output,"_UMAP_hormonelabel.pdf"))
DimPlot(mySeurat2, reduction="umap", label=TRUE, group.by="Hormone")
dev.off()
DefaultAssay(mySeurat2) <- "RNA"
mySeurat2 <- NormalizeData(mySeurat2)
pdf(file=paste0(output,"MarkerVln.pdf"), width=40, height=20)
VlnPlot(mySeurat2, features=c("Esr1","Pgr","Slc17a6","Gad1","Cckar"), pt.size=0, ncol=1)
dev.off()
mySeurat.markers <- FindAllMarkers(mySeurat2, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25, test.use="MAST")
write.csv(mySeurat.markers, file=paste0(output,"_allposmarkers.csv"))
pdf(paste0(output,"_Cckarvln.pdf"), width=20)
VlnPlot(mySeurat2, features=c("Cckar"), split.by="sex", pt.size=0)
dev.off()
#top10 <- mySeurat.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
#DoHeatmap(mySeurat, features=top10$gene) + NoLegend()
#dev.off()
saveRDS(mySeurat2, file=(paste0(output, ".rds")))