#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/VMH_IndependentAnalysis/VMH_Intact_Curated_30pcs"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered1_Intact_30pcs_res1_Primed.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpMale <- read.table("Genelists/VMH_MalevPrimed_Maleup_New.txt")
unlist(UpMale)
UpMale <- as.matrix(UpMale)
UpMale.filtered <- intersect(UpMale, genes.10x)
#Egflam.use <- WhichCells(mySeurat, idents=c("3","17"))
#mySeurat <- SetIdent(mySeurat, cells=Egflam.use, value="Egflam")
#Prckq.use <- WhichCells(mySeurat, idents=c("6","14"))
#mySeurat <- SetIdent(mySeurat, cells=Prckq.use, value="Prkcq")
#Sema3e.use <- WhichCells(mySeurat, idents=c("5","13"))
#mySeurat <- SetIdent(mySeurat, cells=Sema3e.use, value="Sema3e")
#Nr5a1.use <- WhichCells(mySeurat, idents=c("11","15","16"))
#mySeurat <- SetIdent(mySeurat, cells=Nr5a1.use, value="Nr5a1")
#Sst.use <- WhichCells(mySeurat, idents=c("1","20"))
#mySeurat <- SetIdent(mySeurat, cells=Sst.use, value="Sst")
#Tnnt2.use <- WhichCells(mySeurat, idents=c("4","10"))
#mySeurat <- SetIdent(mySeurat, cells=Tnnt2.use, value="Tnnt2")
#cells.use <- WhichCells(mySeurat, idents=c("19"))
#mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Qrfp")
#cells.use <- WhichCells(mySeurat, idents=c("2"))
#mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Ebf3")
#cells.use <- WhichCells(mySeurat, idents=c("9"))
#mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Egflam")
#cells.use <- WhichCells(mySeurat, idents=c("18","3"))
#mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Lepr_Nfix")
#cells.use <- WhichCells(mySeurat, idents=c("0"))
#mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Onecut2")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=18)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Pgr","Phf21b","Setdb2","Tmem215","Cckar"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE)
dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:30)
pdf(paste0(output,"_Intact_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
Pct <- DotPlot(mySeurat, features=UpMale.filtered)
sink(file=paste0(output,"_Pct_by_cluster.txt"), append=FALSE, type=c("output","message"), split=FALSE)
Pct$data
sink()
pdf(file=paste0(output,"_NSForestmarkers.pdf"), width = 14, height=100)
VlnPlot(mySeurat, features=c("Pex5l","Bcl11b","Col25a1","Abi3bp","Arhgap6","Pdzrn3","Satb2","9130024F11Rik","Cyp19a1","Pdzrn4","Alk","Plcl1","Epha6","Lmx1a","Lmx1b","Dlx1os","Nfib","Necab1","Grm8","AC129186.1","Gm28928","Tcf4","Ust","Fam19a1","Ntng1","Zfhx3","Ebf3","Angpt1","Adamts9","9530026P05Rik","Caprin2","Pdzph1","Rai14","Megf11","Gulp1","Etl4","Onecut2","Onecut3","Gm32647","Sema3e","Syndig1","Pou6f1","Grik1","Pomc","Ust","Soxot2","Qrfp","Sst","Gpc3","Adamtsl1","Gm36431","Lepr","St18","Ghrh","Mbnl3"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Egflam","Sst","Cckar","Tnnt2","Abtb2","Lepr","Setdb2","Onecut2","Sema3e","Ebf3","Prkcq","Nr5a1","Nfix","Qrfp"), pt.size=0, ncol=1)
dev.off()
#Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Primed.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(mySeurat, file=paste0(output,"Intact_Merged.rds"))