#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/VMH_IndependentAnalysis/VMH_Intact_Curated"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered1_Intact_10pcs_res1_Primed.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpMale <- read.table("Genelists/VMH_MalevPrimed_Maleup_New.txt")
unlist(UpMale)
UpMale <- as.matrix(UpMale)
UpMale.filtered <- intersect(UpMale, genes.10x)
mySeurat <- subset(mySeurat, idents=c("8"), invert=TRUE)
cells.use <- WhichCells(mySeurat, idents=c("9"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Egflam")
Nr5a1.use <- WhichCells(mySeurat, idents=c("11","15","16"))
mySeurat <- SetIdent(mySeurat, cells=Nr5a1.use, value="Nr5a1")
cells.use <- WhichCells(mySeurat, idents=c("18","3"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Lepr_Nfix")
Sst.use <- WhichCells(mySeurat, idents=c("1","20"))
mySeurat <- SetIdent(mySeurat, cells=Sst.use, value="Sst")
Tnnt2.use <- WhichCells(mySeurat, idents=c("4","10"))
mySeurat <- SetIdent(mySeurat, cells=Tnnt2.use, value="Tnnt2")
Sema3e.use <- WhichCells(mySeurat, idents=c("5","13"))
mySeurat <- SetIdent(mySeurat, cells=Sema3e.use, value="Sema3e")
cells.use <- WhichCells(mySeurat, idents=c("2"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Ebf3")
Prckq.use <- WhichCells(mySeurat, idents=c("6","14"))
mySeurat <- SetIdent(mySeurat, cells=Prckq.use, value="Prkcq")
cells.use <- WhichCells(mySeurat, idents=c("0"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Onecut2")
cells.use <- WhichCells(mySeurat, idents=c("19"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Qrfp")
Cyp19a1.use <- WhichCells(mySeurat, idents=c("17"))
mySeurat <- SetIdent(mySeurat, cells=Cyp19a1.use, value="Cyp19a1")
Fign.use <- WhichCells(mySeurat, idents=c("7"))
mySeurat <- SetIdent(mySeurat, cells=Fign.use, value="Fign")
Phf21b.use <- WhichCells(mySeurat, idents=c("12"))
mySeurat <- SetIdent(mySeurat, cells=Phf21b.use, value="Phf21b")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=22)
VlnPlot(mySeurat, features=c("Ar","Esr1", "Slc17a6","Pgr","Phf21b","Setdb2","Tmem215","Cckar","Rpl41"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Cckbrfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Cckbr", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features="Esr1", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Cckar", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Gldnfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Gldn", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Maml2featureplot.pdf"))
FeaturePlot(mySeurat, features="Maml2", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Rpl41_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Rpl41"))
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap",  cols=c("darkorchid1","darkolivegreen","aquamarine","blue","red","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"), label=TRUE)
dev.off()
pdf(file=paste0(output,"_Dotplot.pdf"), width=10,height=10)
DotPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"))
dev.off()
Pct <- DotPlot(mySeurat, features=UpMale.filtered)
sink(file=paste0(output,"_Pct_by_cluster.txt"), append=FALSE, type=c("output","message"), split=FALSE)
Pct$data
sink()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"), cols=c("darkorchid1","darkolivegreen","aquamarine","blue","red","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"), pt.size=0, ncol=1)
dev.off()
#Primed.markers <- FindAllMarkers(mySeurat, only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Primed.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(mySeurat, file=paste0(output,"Intact_Merged.rds"))