#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/VMH_IndependentAnalysis/VMH_Primed_Curated"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered3_Primed_10pcs_res1_Primed.rds")
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
UpPrimed <- read.table("Genelists/VMH_MalevPrimed_Primedup_New.txt")
unlist(UpPrimed)
UpPrimed <- as.matrix(UpPrimed)
UpPrimed.filtered <- intersect(UpPrimed, genes.10x)
Egflam.use <- WhichCells(mySeurat, idents=c("3","17"))
mySeurat <- SetIdent(mySeurat, cells=Egflam.use, value="Egflam")
Nr5a1.use <- WhichCells(mySeurat, idents=c("9","13"))
mySeurat <- SetIdent(mySeurat, cells=Nr5a1.use, value="Nr5a1")
Lepr.use <- WhichCells(mySeurat, idents=c("2","6"))
mySeurat <- SetIdent(mySeurat, cells=Lepr.use, value="Lepr")
Sst.use <- WhichCells(mySeurat, idents=c("0","15"))
mySeurat <- SetIdent(mySeurat, cells=Sst.use, value="Sst")
Tnnt2.use <- WhichCells(mySeurat, idents=c("4","11"))
mySeurat <- SetIdent(mySeurat, cells=Tnnt2.use, value="Tnnt2")
cells.use <- WhichCells(mySeurat, idents=c("5"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Sema3e")
cells.use <- WhichCells(mySeurat, idents=c("7"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Ebf3")
cells.use <- WhichCells(mySeurat, idents=c("8"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Prkcq")
cells.use <- WhichCells(mySeurat, idents=c("10"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Nfix")
Cckar.use <- WhichCells(mySeurat, idents=c("12"))
mySeurat <- SetIdent(mySeurat, cells=Cckar.use, value="Cckar")
cells.use <- WhichCells(mySeurat, idents=c("1"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Abtb2")
cells.use <- WhichCells(mySeurat, idents=c("14"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Onecut2")
cells.use <- WhichCells(mySeurat, idents=c("16"))
mySeurat <- SetIdent(mySeurat, cells=cells.use, value="Qrfp")
DefaultAssay(mySeurat) <- "RNA"
SDEGs <- AverageExpression(mySeurat, features=UpPrimed.filtered)
SDEGs <- SDEGs["RNA"]
write.csv(SDEGs, file=paste0(output,"Upprimed_SDEG_raw.csv"))
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=18, height=30)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Gad1","Phf21b","Setdb2","Tmem215","Pgr","Rpl41","Ywhah","Robo1","Peg10","Rprm","Mug1","Mug2"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Cacna1g.pdf"), width=12, height=5)
VlnPlot(mySeurat, features=c("Cacna1g"), pt.size=0)
dev.off()
pdf(file=paste0(output,"_Slc32a1.pdf"), width=12, height=5)
VlnPlot(mySeurat, features=c("Slc32a1"), pt.size=0)
dev.off()
pdf(file=paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features="Esr1", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Rprmfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Rprm", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Cckarfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Cckar", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Gldnfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Gldn", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Maml2featureplot.pdf"))
FeaturePlot(mySeurat, features="Maml2", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap", cols=c("blue","red","green","orange","pink","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"), label=TRUE)
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"), cols=c("blue","red","green","orange","pink","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Dotplot.pdf"), width=10,height=10)
DotPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"))
dev.off()
pdf(file=paste0(output,"_Myh7_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Myh7"))
dev.off()
pdf(file=paste0(output,"_Trpa1_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Trpa1"))
dev.off()
pdf(file=paste0(output,"_Rpl41_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Rpl41"))
dev.off()
#pdf(file=paste0(output,"_Cckbrfeatureplot.pdf"))
#p1 <- FeaturePlot(mySeurat, features="Cckbr", order=TRUE)
#fix.sc <- scale_color_gradientn(colors =c("light blue", "red"), limits=c(0,0.9))
#p2 <- lapply(p1, function(x) x+fix.sc)
#dev.off()
mySeurat <- BuildClusterTree(mySeurat, dims=1:10)
pdf(paste0(output,"_clustertree.pdf"))
PlotClusterTree(object=mySeurat)
dev.off()
pdf(file=paste0(output,"exptest.pdf"), width=14, height=80)
VlnPlot(mySeurat, features=c("Irs4","Cntnap2","Pdzrn4","Ak5","Eps15","Tmem13","Hcn1","Foxo1","Polr3d","Ppih","Id2","Cntnap2","Nyap2","Esr1","Phf21b","Ptp4a1","Ksr1"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"Irs4featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Irs4"))
dev.off()
SDEGs <- AverageExpression(mySeurat, features=UpPrimed.filtered)
SDEGs <- SDEGs["RNA"]
Pct <- DotPlot(mySeurat, features=UpPrimed.filtered)
sink(file="Sinktest2.txt", append=FALSE, type=c("output","message"), split=FALSE)
Pct$data
sink()
#write.csv(SDEGs, file=paste0(output,"Upprimedvmale_SDEG.csv"))
#DiffMarks <- FindMarkers(mySeurat, ident.1="Cckar", ident.2 = "Abtb2", min.pct=0.25, only.pos=FALSE, logfc.threshold=0.25, test.use="MAST")
#write.csv(DiffMarks, file=paste0(output,"_CckarvAbtb2.csv"))
#DiffMarks2 <- FindMarkers(mySeurat, ident.1="Sema3e", ident.2 = "Tnnt2", min.pct=0.25, only.pos=FALSE, logfc.threshold=0.25, test.use="MAST")
#write.csv(DiffMarks2, file=paste0(output,"_Sema3evTnnt2.csv"))
#DiffMarks <- FindMarkers(mySeurat, ident.1="Egflam", ident.2 = "Nr5a1", min.pct=0.25, only.pos=FALSE, logfc.threshold=0.25, test.use="MAST")
#write.csv(DiffMarks, file=paste0(output,"_EgflamvNr5a1.csv"))
#DiffMarks2 <- FindMarkers(mySeurat, ident.1="Sema3e", ident.2 = "Tnnt2", min.pct=0.25, only.pos=FALSE, logfc.threshold=0.25, test.use="MAST")
#write.csv(DiffMarks2, file=paste0(output,"_Sema3evTnnt2.csv"))
#Primed.markers <- FindMarkers(mySeurat, ident.1="Unknown", only.pos=TRUE, min.pct=0.25, min.diff.pct=0.2, logfc.threshold = 0.25, test.use="MAST")
#write.csv(Primed.markers, file=paste0(output,"_allposmarkers.csv"))
saveRDS(mySeurat, file=paste0(output,"Primed_Merged_2.rds"))