#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/VMH_IndependentAnalysis/VMH_Unprimed_Curated"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)

mySeurat <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_IndependentFiltered3_Unprimed_10pcs_res1.rds")
Egflam.use <- WhichCells(mySeurat, idents=c("1"))
mySeurat <- SetIdent(mySeurat, cells=Egflam.use, value="Egflam")
Nr5a1.use <- WhichCells(mySeurat, idents=c("6","10","12"))
mySeurat <- SetIdent(mySeurat, cells=Nr5a1.use, value="Nr5a1")
Lepr.use <- WhichCells(mySeurat, idents=c("0"))
mySeurat <- SetIdent(mySeurat, cells=Lepr.use, value="Lepr")
Sst.use <- WhichCells(mySeurat, idents=c("8","13"))
mySeurat <- SetIdent(mySeurat, cells=Sst.use, value="Sst")
Tnnt2.use <- WhichCells(mySeurat, idents=c("2"))
mySeurat <- SetIdent(mySeurat, cells=Tnnt2.use, value="Tnnt2")
Sema3e.use <- WhichCells(mySeurat, idents=c("3"))
mySeurat <- SetIdent(mySeurat, cells=Sema3e.use, value="Sema3e")
Ebf3.use <- WhichCells(mySeurat, idents=c("9","11"))
mySeurat <- SetIdent(mySeurat, cells=Ebf3.use, value="Ebf3")
Prkcq.use <- WhichCells(mySeurat, idents=c("5"))
mySeurat <- SetIdent(mySeurat, cells=Prkcq.use, value="Prkcq")
Nfix.use <- WhichCells(mySeurat, idents=c("7"))
mySeurat <- SetIdent(mySeurat, cells=Nfix.use, value="Nfix")
Cckar.use <- WhichCells(mySeurat, idents=c("14"))
mySeurat <- SetIdent(mySeurat, cells=Cckar.use, value="Cckar")
Abtb2.use <- WhichCells(mySeurat, idents=c("4"))
mySeurat <- SetIdent(mySeurat, cells=Abtb2.use, value="Abtb2")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"_Esr1Vln.pdf"), width=14, height=28)
VlnPlot(mySeurat, features=c("Esr1", "Slc17a6","Gad1","Phf21b","Setdb2","Myh7","Boc","Ywhah","Robo1","Peg10"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Cacna1g.pdf"), width=12, height=5)
VlnPlot(mySeurat, features=c("Cacna1g"), pt.size=0)
dev.off()
pdf(file=paste0(output,"_Myh7_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Myh7"))
dev.off()
pdf(file=paste0(output,"_Boc_Featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Boc"))
dev.off()
pdf(file=paste0(output,"_UMAP.pdf"))
DimPlot(mySeurat, reduction="umap",cols=c("green","orange","pink","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"),  label=TRUE)
dev.off()
pdf(file=paste0(output,"_Cckbrfeatureplot.pdf"))
FeaturePlot(mySeurat, features="Cckbr", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Esr1featureplot.pdf"))
FeaturePlot(mySeurat, features="Esr1", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Trpa1featureplot.pdf"))
FeaturePlot(mySeurat, features="Trpa1", order=TRUE, cols = c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"_Vln_Markers1.pdf"), width=14, height=40)
VlnPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"), cols=c("green","orange","pink","brown","gray","purple","cyan","darkgoldenrod","yellow","deeppink4","coral2"), pt.size=0, ncol=1)
dev.off()
pdf(file=paste0(output,"_Dotplot.pdf"), width=10,height=10)
DotPlot(mySeurat, features=c("Phf21b","Fign","Cyp19a1","Cckar","Abtb2","Qrfp","Onecut2","Prkcq","Ebf3","Sema3e","Tnnt2","Sst","Lepr","Nfix","Nr5a1","Egflam"))
dev.off()
pdf(file=paste0(output,"_Vln_LeprSema3e.pdf"), width=14, height=14)
VlnPlot(mySeurat, features=c("Lepr","Sema3e"), pt.size=0, ncol=1)
dev.off()
Primed.markers <- FindMarkers(mySeurat, ident.1="14", only.pos=TRUE, min.pct=0.05, min.diff.pct=0, logfc.threshold = 0.05)
write.csv(Primed.markers, file=paste0(output,"_14markers.csv"))