library(viper)
library(tidyr)
library(dplyr)
regdata <- file("ARACHNE/AllBulk/Expressionmtx.txt")
adjfile <- file("ARACHNE/AllBulk/network.txt")
regul <- aracne2regulon(adjfile, data, verbose=TRUE)
print(regul)
data <- file("ARACHNE/VMH/VMH_Matrixtest.txt")
#signature <- rowTtest(data)
#nullmodel <- ttestNull(data, y=NULL, per=10, repos=TRUE, verbose=FALSE)
vpres <- viper(data, regul, verbose=TRUE, cores=8)
summary(vpres)
saveRDS(vpres, file="ViperOut/VMH/VMH_vipertest.rds")
pdf(file="Vipertest.pdf")
plot(mrs, cex = .7)
mrsl <- ledge(mrs)
summary(mrsl)
write.csv(mrsl, file="ViperOut/VMH/Leading_Edge_Test.csv")
mrshadow <- shadow(mrs, regulators=25, verbose=TRUE)
summary(mrshadow)
write.csv(mrshadow, file="ViperOut/VMH/Shadow_test.csv")

syn <- msviperSynergy(mrs, verbose=FALSE)