#!/usr/bin/env Rscript

sampleID <- "PrimedPOA"
directory <- "PrimedPOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_PrimedvUnprimed_DiffExp/POA_PrimedvUnprimed_integrated_normalized_postSCT_RNAassay_"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_PrimedvUnprimed_Exploratory/POA_PrimedUnprimed_Exploratory_minimal_filtered.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
mySeurat$celltype.state <- paste(Idents(mySeurat), mySeurat$state, sep="_")
mySeurat$celltype <- Idents(mySeurat)
Idents(mySeurat) <- "celltype.state"
sex.dimorphism0 <- FindMarkers(mySeurat, ident.1 = "0_Primed", ident.2="0_Unprimed", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism0, file=paste0(output, "_cluster0dimorphisms.csv"))
sex.dimorphism1 <- FindMarkers(mySeurat, ident.1 = "1_Primed", ident.2="1_Unprimed", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism1, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism2 <- FindMarkers(mySeurat, ident.1 = "2_Primed", ident.2="2_Unprimed", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism2, file=paste0(output, "_cluster2dimorphisms.csv"))
sex.dimorphism3 <- FindMarkers(mySeurat, ident.1 = "3_Primed", ident.2="3_Unprimed", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism3, file=paste0(output, "_cluster3dimorphisms.csv"))
sex.dimorphism4 <- FindMarkers(mySeurat, ident.1 = "4_Primed", ident.2="4_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism4, file=paste0(output, "_cluster4dimorphisms.csv"))
sex.dimorphism5 <- FindMarkers(mySeurat, ident.1 = "5_Primed", ident.2="5_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism5, file=paste0(output, "_cluster5dimorphisms.csv"))
sex.dimorphism6 <- FindMarkers(mySeurat, ident.1 = "6_Primed", ident.2="6_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism6, file=paste0(output, "_cluster6dimorphisms.csv"))
sex.dimorphism7 <- FindMarkers(mySeurat, ident.1 = "7_Primed", ident.2="7_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism7, file=paste0(output, "_cluster7dimorphisms.csv"))
sex.dimorphism8 <- FindMarkers(mySeurat, ident.1 = "8_Primed", ident.2="8_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism8, file=paste0(output, "_cluster8dimorphisms.csv"))
sex.dimorphism9 <- FindMarkers(mySeurat, ident.1 = "9_Primed", ident.2="9_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism9, file=paste0(output, "_cluster9dimorphisms.csv"))
sex.dimorphism10 <- FindMarkers(mySeurat, ident.1 = "10_Primed", ident.2="10_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism10, file=paste0(output, "_cluster10dimorphisms.csv"))
sex.dimorphism11 <- FindMarkers(mySeurat, ident.1 = "11_Primed", ident.2="11_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism11, file=paste0(output, "_cluster11dimorphisms.csv"))
sex.dimorphism12 <- FindMarkers(mySeurat, ident.1 = "12_Primed", ident.2="12_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism12, file=paste0(output, "_cluster12dimorphisms.csv"))
sex.dimorphism13 <- FindMarkers(mySeurat, ident.1 = "13_Primed", ident.2="13_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism13, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism14 <- FindMarkers(mySeurat, ident.1 = "14_Primed", ident.2="14_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism14, file=paste0(output, "_cluster14dimorphisms.csv"))
sex.dimorphism15 <- FindMarkers(mySeurat, ident.1 = "15_Primed", ident.2="15_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism15, file=paste0(output, "_cluster15dimorphisms.csv"))
sex.dimorphism16 <- FindMarkers(mySeurat, ident.1 = "16_Primed", ident.2="16_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism16, file=paste0(output, "_cluster16dimorphisms.csv"))
sex.dimorphism17 <- FindMarkers(mySeurat, ident.1 = "17_Primed", ident.2="17_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism17, file=paste0(output, "_cluster17dimorphisms.csv"))
sex.dimorphism18 <- FindMarkers(mySeurat, ident.1 = "18_Primed", ident.2="18_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism18, file=paste0(output, "_cluster18dimorphisms.csv"))
sex.dimorphism19 <- FindMarkers(mySeurat, ident.1 = "19_Primed", ident.2="19_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism19, file=paste0(output, "_cluster19dimorphisms.csv"))
sex.dimorphism20 <- FindMarkers(mySeurat, ident.1 = "20_Primed", ident.2="20_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism20, file=paste0(output, "_cluster20dimorphisms.csv"))
sex.dimorphism21 <- FindMarkers(mySeurat, ident.1 = "21_Primed", ident.2="21_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism21, file=paste0(output, "_cluster21dimorphisms.csv"))
sex.dimorphism22 <- FindMarkers(mySeurat, ident.1 = "22_Primed", ident.2="22_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism22, file=paste0(output, "_cluster22dimorphisms.csv"))
sex.dimorphism23 <- FindMarkers(mySeurat, ident.1 = "23_Primed", ident.2="23_Unprimed",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism23, file=paste0(output, "_cluster23dimorphisms.csv"))
sex.dimorphism24 <- FindMarkers(mySeurat, ident.1 = "24_Primed", ident.2="24_Unprimed",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism24, file=paste0(output, "_cluster24dimorphisms.csv"))
sex.dimorphism25 <- FindMarkers(mySeurat, ident.1 = "25_Primed", ident.2="25_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism25, file=paste0(output, "_cluster25dimorphisms.csv"))
sex.dimorphism26 <- FindMarkers(mySeurat, ident.1 = "26_Primed", ident.2="26_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism26, file=paste0(output, "_cluster26dimorphisms.csv"))
sex.dimorphism27 <- FindMarkers(mySeurat, ident.1 = "27_Primed", ident.2="27_Unprimed", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism27, file=paste0(output, "_cluster27dimorphisms.csv"))
