#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimed_DiffExp/POA_MalevUnprimed_integrated_normalize_postSCT_RNAassay_"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_filtered.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
mySeurat$celltype.sex <- paste(Idents(mySeurat), mySeurat$sex, sep="_")
mySeurat$celltype <- Idents(mySeurat)
Idents(mySeurat) <- "celltype.sex"
sex.dimorphism0 <- FindMarkers(mySeurat, ident.1 = "0_Male", ident.2="0_Female", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism0, file=paste0(output, "_cluster0dimorphisms.csv"))
sex.dimorphism1 <- FindMarkers(mySeurat, ident.1 = "1_Male", ident.2="1_Female", min.pct=0.01, logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism1, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism2 <- FindMarkers(mySeurat, ident.1 = "2_Male", ident.2="2_Female", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism2, file=paste0(output, "_cluster2dimorphisms.csv"))
sex.dimorphism3 <- FindMarkers(mySeurat, ident.1 = "3_Male", ident.2="3_Female", min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism3, file=paste0(output, "_cluster3dimorphisms.csv"))
sex.dimorphism4 <- FindMarkers(mySeurat, ident.1 = "4_Male", ident.2="4_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism4, file=paste0(output, "_cluster4dimorphisms.csv"))
sex.dimorphism5 <- FindMarkers(mySeurat, ident.1 = "5_Male", ident.2="5_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism5, file=paste0(output, "_cluster5dimorphisms.csv"))
sex.dimorphism6 <- FindMarkers(mySeurat, ident.1 = "6_Male", ident.2="6_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism6, file=paste0(output, "_cluster6dimorphisms.csv"))
sex.dimorphism7 <- FindMarkers(mySeurat, ident.1 = "7_Male", ident.2="7_Female",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism7, file=paste0(output, "_cluster7dimorphisms.csv"))
sex.dimorphism8 <- FindMarkers(mySeurat, ident.1 = "8_Male", ident.2="8_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism8, file=paste0(output, "_cluster8dimorphisms.csv"))
sex.dimorphism9 <- FindMarkers(mySeurat, ident.1 = "9_Male", ident.2="9_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism9, file=paste0(output, "_cluster9dimorphisms.csv"))
sex.dimorphism10 <- FindMarkers(mySeurat, ident.1 = "10_Male", ident.2="10_Female",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism10, file=paste0(output, "_cluster10dimorphisms.csv"))
sex.dimorphism11 <- FindMarkers(mySeurat, ident.1 = "11_Male", ident.2="11_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism11, file=paste0(output, "_cluster11dimorphisms.csv"))
sex.dimorphism12 <- FindMarkers(mySeurat, ident.1 = "12_Male", ident.2="12_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism12, file=paste0(output, "_cluster12dimorphisms.csv"))
sex.dimorphism13 <- FindMarkers(mySeurat, ident.1 = "13_Male", ident.2="13_Female",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism13, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism14 <- FindMarkers(mySeurat, ident.1 = "14_Male", ident.2="14_Female",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism14, file=paste0(output, "_cluster14dimorphisms.csv"))
sex.dimorphism15 <- FindMarkers(mySeurat, ident.1 = "15_Male", ident.2="15_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism15, file=paste0(output, "_cluster15dimorphisms.csv"))
sex.dimorphism16 <- FindMarkers(mySeurat, ident.1 = "16_Male", ident.2="16_Female",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism16, file=paste0(output, "_cluster16dimorphisms.csv"))
sex.dimorphism17 <- FindMarkers(mySeurat, ident.1 = "17_Male", ident.2="17_Female",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism17, file=paste0(output, "_cluster17dimorphisms.csv"))
sex.dimorphism18 <- FindMarkers(mySeurat, ident.1 = "18_Male", ident.2="18_Female",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism18, file=paste0(output, "_cluster18dimorphisms.csv"))
sex.dimorphism19 <- FindMarkers(mySeurat, ident.1 = "19_Male", ident.2="19_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism19, file=paste0(output, "_cluster19dimorphisms.csv"))
sex.dimorphism20 <- FindMarkers(mySeurat, ident.1 = "20_Male", ident.2="20_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism20, file=paste0(output, "_cluster20dimorphisms.csv"))
sex.dimorphism21 <- FindMarkers(mySeurat, ident.1 = "21_Male", ident.2="21_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism21, file=paste0(output, "_cluster21dimorphisms.csv"))
sex.dimorphism22 <- FindMarkers(mySeurat, ident.1 = "22_Male", ident.2="22_Female",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism22, file=paste0(output, "_cluster22dimorphisms.csv"))
sex.dimorphism23 <- FindMarkers(mySeurat, ident.1 = "23_Male", ident.2="23_Female",min.pct=0.01, logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism23, file=paste0(output, "_cluster23dimorphisms.csv"))
sex.dimorphism24 <- FindMarkers(mySeurat, ident.1 = "24_Male", ident.2="24_Female",min.pct=0.01,logfc.threshold=0.1, verbose=TRUE)
write.csv(sex.dimorphism24, file=paste0(output, "_cluster24dimorphisms.csv"))
sex.dimorphism25 <- FindMarkers(mySeurat, ident.1 = "25_Male", ident.2="25_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism25, file=paste0(output, "_cluster25dimorphisms.csv"))
sex.dimorphism26 <- FindMarkers(mySeurat, ident.1 = "26_Male", ident.2="26_Female", min.pct=0.01,logfc.threshold=0.1,verbose=TRUE)
write.csv(sex.dimorphism26, file=paste0(output, "_cluster26dimorphisms.csv"))
