#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/POA_MalevUnprimed_Doubletsremoved/MalevUnprimed_Fineclusters_Doubletsremoved_filtered_DESeq2_unnormalized_filtered3"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(DESeq2)

mySeurat <- readRDS("Seurat/POA_MalevUnprimedMerged_Exploratory/MaleUnprimed_doubletsremoved_filtered3.rds")
DefaultAssay(mySeurat) <- "RNA"
mySeurat$celltype.sex <- paste(Idents(mySeurat), mySeurat$sex, sep="_")
mySeurat$celltype <- Idents(mySeurat)
Idents(mySeurat) <- "celltype.sex"
sex.dimorphism0 <- FindMarkers(mySeurat, ident.1 = "0_Male", ident.2="0_Female", min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism0, file=paste0(output, "_cluster0dimorphisms.csv"))
sex.dimorphism1 <- FindMarkers(mySeurat, ident.1 = "1_Male", ident.2="1_Female", min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism1, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism2 <- FindMarkers(mySeurat, ident.1 = "2_Male", ident.2="2_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism2, file=paste0(output, "_cluster2dimorphisms.csv"))
sex.dimorphism3 <- FindMarkers(mySeurat, ident.1 = "3_Male", ident.2="3_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism3, file=paste0(output, "_cluster3dimorphisms.csv"))
sex.dimorphism4 <- FindMarkers(mySeurat, ident.1 = "4_Male", ident.2="4_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism4, file=paste0(output, "_cluster4dimorphisms.csv"))
sex.dimorphism5 <- FindMarkers(mySeurat, ident.1 = "5_Male", ident.2="5_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism5, file=paste0(output, "_cluster5dimorphisms.csv"))
sex.dimorphism6 <- FindMarkers(mySeurat, ident.1 = "6_Male", ident.2="6_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism6, file=paste0(output, "_cluster6dimorphisms.csv"))
sex.dimorphism7 <- FindMarkers(mySeurat, ident.1 = "7_Male", ident.2="7_Female",min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism7, file=paste0(output, "_cluster7dimorphisms.csv"))
sex.dimorphism8 <- FindMarkers(mySeurat, ident.1 = "8_Male", ident.2="8_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism8, file=paste0(output, "_cluster8dimorphisms.csv"))
sex.dimorphism9 <- FindMarkers(mySeurat, ident.1 = "9_Male", ident.2="9_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism9, file=paste0(output, "_cluster9dimorphisms.csv"))
sex.dimorphism10 <- FindMarkers(mySeurat, ident.1 = "10_Male", ident.2="10_Female",min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism10, file=paste0(output, "_cluster10dimorphisms.csv"))
sex.dimorphism11 <- FindMarkers(mySeurat, ident.1 = "11_Male", ident.2="11_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism11, file=paste0(output, "_cluster11dimorphisms.csv"))
sex.dimorphism12 <- FindMarkers(mySeurat, ident.1 = "12_Male", ident.2="12_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism12, file=paste0(output, "_cluster12dimorphisms.csv"))
sex.dimorphism13 <- FindMarkers(mySeurat, ident.1 = "13_Male", ident.2="13_Female",min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism13, file=paste0(output, "_cluster1dimorphisms.csv"))
sex.dimorphism14 <- FindMarkers(mySeurat, ident.1 = "14_Male", ident.2="14_Female",min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism14, file=paste0(output, "_cluster14dimorphisms.csv"))
sex.dimorphism15 <- FindMarkers(mySeurat, ident.1 = "15_Male", ident.2="15_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism15, file=paste0(output, "_cluster15dimorphisms.csv"))
sex.dimorphism16 <- FindMarkers(mySeurat, ident.1 = "16_Male", ident.2="16_Female",min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism16, file=paste0(output, "_cluster16dimorphisms.csv"))
sex.dimorphism17 <- FindMarkers(mySeurat, ident.1 = "17_Male", ident.2="17_Female",min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism17, file=paste0(output, "_cluster17dimorphisms.csv"))
sex.dimorphism18 <- FindMarkers(mySeurat, ident.1 = "18_Male", ident.2="18_Female",min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism18, file=paste0(output, "_cluster18dimorphisms.csv"))
sex.dimorphism19 <- FindMarkers(mySeurat, ident.1 = "19_Male", ident.2="19_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism19, file=paste0(output, "_cluster19dimorphisms.csv"))
sex.dimorphism20 <- FindMarkers(mySeurat, ident.1 = "20_Male", ident.2="20_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism20, file=paste0(output, "_cluster20dimorphisms.csv"))
sex.dimorphism21 <- FindMarkers(mySeurat, ident.1 = "21_Male", ident.2="21_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism21, file=paste0(output, "_cluster21dimorphisms.csv"))
sex.dimorphism22 <- FindMarkers(mySeurat, ident.1 = "22_Male", ident.2="22_Female",min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism22, file=paste0(output, "_cluster22dimorphisms.csv"))
sex.dimorphism23 <- FindMarkers(mySeurat, ident.1 = "23_Male", ident.2="23_Female",min.pct=0.01, logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism23, file=paste0(output, "_cluster23dimorphisms.csv"))
sex.dimorphism24 <- FindMarkers(mySeurat, ident.1 = "24_Male", ident.2="24_Female",min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2", verbose=TRUE)
write.csv(sex.dimorphism24, file=paste0(output, "_cluster24dimorphisms.csv"))
sex.dimorphism25 <- FindMarkers(mySeurat, ident.1 = "25_Male", ident.2="25_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism25, file=paste0(output, "_cluster25dimorphisms.csv"))
sex.dimorphism26 <- FindMarkers(mySeurat, ident.1 = "26_Male", ident.2="26_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism26, file=paste0(output, "_cluster26dimorphisms.csv"))
sex.dimorphism27 <- FindMarkers(mySeurat, ident.1 = "27_Male", ident.2="27_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism27, file=paste0(output, "_cluster27dimorphisms.csv"))
sex.dimorphism28 <- FindMarkers(mySeurat, ident.1 = "28_Male", ident.2="28_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism28, file=paste0(output, "_cluster28dimorphisms.csv"))
sex.dimorphism29 <- FindMarkers(mySeurat, ident.1 = "29_Male", ident.2="29_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism29, file=paste0(output, "_cluster29dimorphisms.csv"))
sex.dimorphism30 <- FindMarkers(mySeurat, ident.1 = "30_Male", ident.2="30_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism30, file=paste0(output, "_cluster30dimorphisms.csv"))
sex.dimorphism31 <- FindMarkers(mySeurat, ident.1 = "31_Male", ident.2="31_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism31, file=paste0(output, "_cluster31dimorphisms.csv"))
sex.dimorphism32 <- FindMarkers(mySeurat, ident.1 = "32_Male", ident.2="32_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism32, file=paste0(output, "_cluster32dimorphisms.csv"))
sex.dimorphism33 <- FindMarkers(mySeurat, ident.1 = "33_Male", ident.2="33_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism33, file=paste0(output, "_cluster33dimorphisms.csv"))
sex.dimorphism34 <- FindMarkers(mySeurat, ident.1 = "34_Male", ident.2="34_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism34, file=paste0(output, "_cluster34dimorphisms.csv"))
sex.dimorphism35 <- FindMarkers(mySeurat, ident.1 = "35_Male", ident.2="35_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism35, file=paste0(output, "_cluster35dimorphisms.csv"))
sex.dimorphism36 <- FindMarkers(mySeurat, ident.1 = "36_Male", ident.2="36_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism36, file=paste0(output, "_cluster36dimorphisms.csv"))
sex.dimorphism37 <- FindMarkers(mySeurat, ident.1 = "37_Male", ident.2="37_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism37, file=paste0(output, "_cluster37dimorphisms.csv"))
sex.dimorphism38 <- FindMarkers(mySeurat, ident.1 = "38_Male", ident.2="38_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism38, file=paste0(output, "_cluster38dimorphisms.csv"))
sex.dimorphism39 <- FindMarkers(mySeurat, ident.1 = "39_Male", ident.2="39_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism39, file=paste0(output, "_cluster39dimorphisms.csv"))
sex.dimorphism40 <- FindMarkers(mySeurat, ident.1 = "40_Male", ident.2="40_Female", min.pct=0.01,logfc.threshold=0.1, test.use="DESeq2",verbose=TRUE)
write.csv(sex.dimorphism40, file=paste0(output, "_cluster40dimorphisms.csv"))
