#!/usr/bin/env Rscript

sampleID <- "MalePOA"
directory <- "MalePOAIntact/outs/filtered_feature_bc_matrix"
output <- "Seurat/VMH_IndependentAnalysis/VMH_recluster"

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(MAST)
library(pheatmap)
library(viridis)
mySeurat <- readRDS("Seurat/VMH_IndependentAnalysis/VMH_Fullmerge_Test_prepaperreclusterRound2_sexclude_malat1regress_filtered5_30pcsres1.2.rds")
props <- prop.table(table(Idents(mySeurat), mySeurat$Hormone), margin=2)
write.csv(props, file=paste0(output, "propperclust.csv"))
counts <- table(Idents(mySeurat), mySeurat$Hormone)
write.csv(counts, file=paste0(output,"countsperclust.csv"))
pdf(file=paste0(output,"NewUMAPsize4.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, label.size=4)
dev.off()
pdf(file=paste0(output,"NewUMAPsize5.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, label.size=5)
dev.off()
pdf(file=paste0(output,"NewUMAPsize6.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, label.size=6)
dev.off()
pdf(file=paste0(output,"NewUMAPsize7.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, label.size=7)
dev.off()
pdf(file=paste0(output,"NewUMAPsize8.pdf"))
DimPlot(mySeurat, reduction="umap", label=TRUE, label.size=8)
dev.off()
pdf(file=paste0(output,"NewUMAP1.pdf"))
DimPlot(mySeurat, reduction="umap")
dev.off()
Abtb2overlap <- read.table("Genelists/Abtb2Myho1hoverlap.txt", header=FALSE)
Abtb2overlap <- unlist(Abtb2overlap)
Cckaroverlap <- read.table("Genelists/CckarMyo1hoverlap.txt", header=FALSE)
Cckaroverlap <- unlist(Cckaroverlap)
Female <- subset(x=mySeurat, subset=Hormone=="Intact", invert=TRUE)
pdf(file=paste0(output,"FemaleUmaphormonesplit.pdf"))
DimPlot(Female, reduction="umap", group.by="Hormone", cols=c("light green", "pink"))
dev.off()
pdf(file=paste0(output,"FemaleUmap.pdf"))
DimPlot(Female, reduction="umap")
dev.off()
pdf(file=paste0(output,"Femaleumap_Phf21b.pdf"))
FeaturePlot(Female, features=c("Phf21b"), cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"Femaleumap_Phf21bHormonesplit.pdf"), width=16)
FeaturePlot(Female, features=c("Phf21b"), split.by="Hormone", cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"Femaleumap_Cckar.pdf"))
FeaturePlot(Female, features=c("Cckar"), cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output,"Femaleumap_CckarHormonesplit.pdf"), width=16)
FeaturePlot(Female, features=c("Cckar"), split.by="Hormone",cols=c("light blue", "red"))
dev.off()

pdf(file=paste0(output,"Femaleumap_Abtb2.pdf"))
FeaturePlot(Female, features=c("Abtb2"), cols=c("light blue", "red"))
dev.off()

DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
pdf(file=paste0(output,"femaleupGad1.pdf"))
VlnPlot(mySeurat, features=c("Gad1"), idents=c("8","21","26"), pt.size=0,  cols=c("gray","gray","gray"))
dev.off()
pdf(file=paste0(output,"femaleupSlc17a6.pdf"))
VlnPlot(mySeurat, features=c("Slc17a6"), idents=c("8","21","26"), pt.size=0, cols=c("gray","gray","gray"))
dev.off()
pdf(file=paste0(output,"femaleupSlc17a8.pdf"))
VlnPlot(mySeurat, features=c("Slc18a2"), idents=c("8","21","26"), pt.size=0, cols=c("gray","gray","gray"))
dev.off()
pdf(file=paste0(output,"maleupGad1.pdf"))
VlnPlot(mySeurat, features=c("Gad1"), idents=c("19"), pt.size=0, cols=c("gray"))
dev.off()
pdf(file=paste0(output,"maleupSlc17a6.pdf"))
VlnPlot(mySeurat, features=c("Slc17a6"), idents=c("19"), pt.size=0, cols=c("gray"))
dev.off()
pdf(file=paste0(output,"maleupCyp19a1.pdf"))
VlnPlot(mySeurat, features=c("Cyp19a1"), idents=c("19"), pt.size=0, cols=c("gray"))
dev.off()
pdf(file=paste0(output,"biasmarkers.pdf"), width=10, height=24)
VlnPlot(mySeurat, idents=c("8","13","16","19","20","21","23","26"), features=rev(c("Gad1","Slc17a6","Abtb2","Eya1","Nup62cl","Cyp19a1","Exph5","Cckar","Steap3","Myo1h")), ncol=1, pt.size=0)
dev.off()

pdf(file=paste0(output,"MaleClustMarkers.pdf"), height=30)
VlnPlot(mySeurat, idents=c("19"), features=rev(c("Gad1","Slc17a6","Cyp19a1","Shisal2b","Ror1","Fbn2","Meis2","Rspo2")), cols=c("orange"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"EstrusClustMarkers.pdf"), height=20)
VlnPlot(mySeurat, idents=c("8","21","26"), features=rev(c("Gad1","Slc17a6","Isl1","Ebf3","Glra1","Lmo7","Abtb2","Cckar","Myo1h")), cols=c("orange","purple","pink"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"plotnolab_hormonelabel.pdf"))
DimPlot(mySeurat, label=FALSE, reduction="umap", group.by="Hormone", cols=c("light blue","pink","light green"))
dev.off()
genelist <- read.table("Genelists/VMH_PvU_1.5.txt", header=FALSE)
genelist <- unlist(genelist)
dim(x=mySeurat)
genes.10x <- (x=rownames(x=mySeurat))
unlist(genes.10x)
filtered.genelist <- intersect(genelist, genes.10x)
filtered.genelist
MvP <- read.table("Genelists/VMH_MvP_1.5.txt", header=FALSE)
MvU <- read.table("Genelists/VMH_MvU_1.5.txt", header=FALSE)
sDEGs <- rbind(MvP, MvU)
sDEGs <- unlist(sDEGs)
sDEGs <- unique(sDEGs)
filtered.sDEGs <- intersect(sDEGs, genes.10x)
all <- rbind(genelist, MvP, MvU)
all <- unlist(all)
all <- unique(all)
filtered.all <- intersect(all, genes.10x)
singlesig <- read.table("/scratch/users/knoedler/Heatmaps/Seurat/MetaDEGs/VMH_SingleDimorphic.txt", header=FALSE)
singlesig <- unlist(singlesig)
singlesig.filtered <- setdiff(filtered.all, singlesig)
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
Maleup <- read.table("Genelists/VMH_AllupMale.txt", header=FALSE)
Maleup <- unlist(Maleup)
Maleup <- unique(Maleup)
pdf(file=paste0(output,"cckarplot.pdf"), width=30)
VlnPlot(mySeurat, assay="RNA", features=c("Cckar"), pt.size=0)
dev.off()
pdf(file=paste0(output,"cckarverlap.pdf"), width=30, height=80)
VlnPlot(mySeurat, features=Cckaroverlap, ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"abtb2overlap.pdf"), width=30, height=10)
VlnPlot(mySeurat, features=Abtb2overlap, ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"compositecommon.pdf"), width=30, height=50)
VlnPlot(mySeurat, features=c("Kcnq5","Synpr","Igsf11","Megf11","Kcnh8","Abtb2"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"FigS7Vln.pdf"), height=45)
VlnPlot(mySeurat, features=c("Myo1h","Cckar","Abtb2","Synpr","Igsf11","Megf11","Kcnh8","Reln","Phf21b","Tmem215","Mad2l1","Samd9l","Foxo1","Ptp4a1","Ksr1","Mical2"), idents=c("8","21","26"), ncol=1, pt.size=0)
dev.off()
pdf(file=paste0(output,"FigS7Vlncol2.pdf"), height=45)
VlnPlot(mySeurat, features=c("Myo1h","Cckar","Abtb2","Synpr","Igsf11","Megf11","Kcnh8","Reln","Phf21b","Tmem215","Mad2l1","Samd9l","Foxo1","Ptp4a1","Ksr1","Mical2"), idents=c("8","21","26"), cols=c("dark green", "light green", "red"), ncol=1, pt.size=0)
dev.off()
#p <- VlnPlot(mySeurat
pdf(file=paste0(output,"FigS7Vlnall.pdf"), width=40, height=50)
VlnPlot(mySeurat, features=c("Abtb2","Myo1h","Cckar","Reln","Phf21b","Tmem215","Mad2l1","Samd9l","Foxo1","Kcnq5","Synpr","Igsf11","Megf11","Kcnh8"), ncol=1, pt.size=0)
dev.off()
#p
#sink(file=paste0(output,"cckarcounts.txt"), append=FALSE, type=c("output","message"), split=FALSE)
#p$data
#sink()
#dev.off()
pdf(file=paste0(output,"Fosb_featureplot.pdf"), width=30)
FeaturePlot(mySeurat, features=c("Fosb", "Fosl2", "Jun","Junb"), order=TRUE, cols=c("light blue", "red"))
dev.off()
sex.markers <- FindAllMarkers(mySeurat, features=filtered.all, only.pos=TRUE, min.pct=0.25, logfc.threshold = 0.25, test.use="MAST", return.thresh=1e-4)
write.csv(sex.markers, file=paste0(output,"Sexmarkerstats.csv"))
#mySeurat2 <- BuildClusterTree(mySeurat, reorder=TRUE, dims=1:30)
#ScaledSeurat <- ScaleData(mySeurat2, features=rownames(mySeurat), do.center=TRUE, do.scale=TRUE)
#pdf(paste0(output,"_SexMarkerheatmapreordered.pdf"))
top10 <- sex.markers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
#DoHeatmap(ScaledSeurat, features=top10$gene, raster=FALSE) 
#dev.off()
props <- prop.table(table(Idents(mySeurat), mySeurat$Hormone), margin=2)
write.csv(props, file=paste0(output, "propperclust.csv"))
counts <- table(Idents(mySeurat), mySeurat$Hormone)
write.csv(counts, file=paste0(output,"countsperclust.csv"))
top10genes <- top10$gene
top10genes <- unique(top10genes)
DefaultAssay(mySeurat) <- "RNA"
mySeurat <- NormalizeData(mySeurat)
Avg <- AverageExpression(mySeurat, assays=c("RNA"), features=top10genes)
write.csv(Avg, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/AllsigDEGclusteravgs.csv")

Avg2 <- AverageExpression(mySeurat, assays=c("RNA"), features=singlesig.filtered)
write.csv(Avg2, file="/scratch/users/knoedler/Heatmaps/Seurat/MetaDEGs/VMHMetaDEGs.csv")
Avg <- AverageExpression(mySeurat, assays=c("RNA"), features=top10genes)
write.csv(Avg, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/AllsigDEGclusteravgs2.csv")
DefaultAssay(mySeurat) <- "RNA"
pdf(file=paste0(output,"sexbias.pdf"))
DimPlot(mySeurat, cols=c("0"="light gray", "1"="light gray", "2"="light gray", "3"="light gray", "4"="light gray", "5"="light gray", "6"="light gray", 
	"7"="light gray", "8"="Dark Green", "9"="light gray", "10"="light gray", "11"="light gray", "12"="light gray", "13"="light gray", 
	"14"="light gray", "15"="light gray", "16"="light gray", "17"="light gray", "18"="light gray", "19"="light gray", "20"="light gray", 
	"21"="Light green", "22"="light gray", "23"="light gray", "24"="light gray", "25"="light gray", "26"="red", "27"="light gray"), label=FALSE, reduction="umap")
dev.off() 
pdf(file=paste0(output,"allsexbias.pdf"))
DimPlot(mySeurat, cols=c("0"="light gray", "1"="light gray", "2"="light gray", "3"="light gray", "4"="light gray", "5"="light gray", "6"="light gray", 
	"7"="light gray", "8"="red", "9"="light gray", "10"="light gray", "11"="light gray", "12"="light gray", "13"="blue", 
	"14"="light gray", "15"="light gray", "16"="blue", "17"="light gray", "18"="light gray", "19"="blue", "20"="light green", 
	"21"="red", "22"="light gray", "23"="light green", "24"="light gray", "25"="light gray", "26"="light green", "27"="light gray"), label=FALSE, reduction="umap")
dev.off() 
pdf(file=paste0(output,"plotnolab.pdf"))
DimPlot(mySeurat, label=FALSE, reduction="umap")
dev.off()
pdf(file=paste0(output,"plotnolab_hormonesplit.pdf"), width=20,height=10)
DimPlot(mySeurat, label=FALSE, reduction="umap", split.by="Hormone")
dev.off()
typemarkers <- read.table("DotPlotMarkerLists/VMH_Sexcluderegress_final.txt")
typemarkers <- unlist(typemarkers)
typemarkers <- as.matrix(typemarkers)
pdf(file=paste0(output, "Dotplot.pdf"))
DotPlot(mySeurat, features=typemarkers)
dev.off()

mySeurat <- NormalizeData(mySeurat)

pdf(file=paste0(output, "Slc17a6_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc17a6"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Slc32a1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Slc32a1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Gad1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gad1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Cyp19a1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Cyp19a1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Nfia_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Nfia"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Esr1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Esr1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Cyp19a1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Cyp19a1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Gldn_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Gldn"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Phf21b_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Phf21b"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Mad2l1_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Mad2l1"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(file=paste0(output, "Cckar_featureplot.pdf"))
FeaturePlot(mySeurat, features=c("Cckar"), order=TRUE, cols=c("light blue", "red"))
dev.off()
pdf(paste0(output,"Abtb2Vln.pdf"))
VlnPlot(mySeurat, features=c("Abtb2"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Phf21bVln.pdf"))
VlnPlot(mySeurat, features=c("Phf21b"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Myo1hVln.pdf"))
VlnPlot(mySeurat, features=c("Myo1h"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Samd9lVln.pdf"))
VlnPlot(mySeurat, features=c("Samd9l"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Foxn2Vln.pdf"))
VlnPlot(mySeurat, features=c("Foxn2"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Foxn2Vln.pdf"))
VlnPlot(mySeurat, features=c("Foxn2"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Vav3Vln.pdf"))
VlnPlot(mySeurat, features=c("Vav3"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Mad2l1Vln.pdf"))
VlnPlot(mySeurat, features=c("Mad2l1"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Trpc7Vln.pdf"))
VlnPlot(mySeurat, features=c("Trpc7"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Cntnap5c.pdf"))
VlnPlot(mySeurat, features=c("Cntnap5c"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Tmem108.pdf"))
VlnPlot(mySeurat, features=c("Tmem108"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Foxo1.pdf"))
VlnPlot(mySeurat, features=c("Foxo1"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Slit2.pdf"))
VlnPlot(mySeurat, features=c("Slit2"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Megf11.pdf"))
VlnPlot(mySeurat, features=c("Megf11"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Pde7b.pdf"))
VlnPlot(mySeurat, features=c("Pde7b"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Pde7b.pdf"))
VlnPlot(mySeurat, features=c("Pde7b"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Meg3.pdf"))
VlnPlot(mySeurat, features=c("Meg3"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Tmem215.pdf"))
VlnPlot(mySeurat, features=c("Tmem215"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Nell2.pdf"))
VlnPlot(mySeurat, features=c("Nell2"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Reln.pdf"))
VlnPlot(mySeurat, features=c("Reln"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Fam19a5.pdf"))
VlnPlot(mySeurat, features=c("Fam19a5"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Alcam.pdf"))
VlnPlot(mySeurat, features=c("Alcam"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Pbx3.pdf"))
VlnPlot(mySeurat, features=c("Pbx3"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Cckar.pdf"))
VlnPlot(mySeurat, features=c("Cckar"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Kcnq5.pdf"))
VlnPlot(mySeurat, features=c("Kcnq5"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
pdf(paste0(output,"Ksr1.pdf"))
VlnPlot(mySeurat, features=c("Ksr1"), idents=c("8","21","26"), pt.size=0, cols=c("Dark Green","Light Green","Red"))
dev.off()
mySeurat2 <- BuildClusterTree(mySeurat, reorder=TRUE, dims=1:30)
Avg <- AverageExpression(mySeurat2, features=filtered.genelist)
Avg
write.csv(Avg, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/PvU_avg.txt")
data <- mySeurat2@assays[["RNA"]]@data
AvgsDEGs <- AverageExpression(mySeurat2, features=filtered.sDEGs)
Avg
write.csv(AvgsDEGs, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/sDEGsavg.txt")


AvgAllDEGs <- AverageExpression(mySeurat2, features=filtered.all)
AvgAllDEGs
write.csv(AvgAllDEGs, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/AllDEGsavg.txt")
data <- read.csv(file="

data <- as.matrix(data)
dim(data)
head(data)
data <- scale(t(data))
idents <- mySeurat2@active.ident
idents <- as.matrix(idents)
head(idents)
DEGs <- data[,filtered.genelist]
pdf(file="VMH_sDEGheatmapt.pdf")
pheatmap(data, cluster_rows=FALSE, cluster_cols=FALSE, border_color=NA, color=viridis(500),annotation_col=idents)
dev.off()
idents <- mySeurat2@active.ident
df <- cbind(data, idents)
dim(df)
head(df)
DEGs <- df[,filtered.genelist]
dim(DEGs)
head(DEGs)
mySeurat2 <- ScaleData(mySeurat2, features=rownames(mySeurat2))
pdf(file=paste0(output,"PCAClust_sDEGheatmap.pdf"))
DoHeatmap(mySeurat2, features=filtered.genelist)
dev.off()

top10genes <- top10$gene
top10genes <- unique(top10genes)
Avg <- AverageExpression(mySeurat, assays=c("RNA"), features=top10genes)
Avg
write.csv(Avg, file="/scratch/users/knoedler/Heatmaps/Seurat/VMH/AllsigDEGclusteravgs.csv")

Hm <- DoHeatmap(mySeurat2, features=filtered.genelist, assay="RNA")
sink(file=paste0(output,"Hmsink.txt"), append=FALSE, type=c("output","message"), split=FALSE)
Hm$data
sink()

mySeurat3 <- BuildClusterTree(mySeurat, reorder=TRUE, features=filtered.genelist, slot="data")
pdf(file=paste0(output,"DEGClust_sDEGheatmap.pdf"))
DoHeatmap(mySeurat3, features=filtered.genelist, assay="RNA")
dev.off()